Repository nhsuk/manage-vaccinations-in-schools, pull requests merged in 2025-04, with the labels that each got.

#3273 Cache session status in database
  .rubocop.yml
  app/components/app_patient_session_search_result_card_component.rb
  app/components/app_programme_session_table_component.rb
  app/components/app_session_details_summary_component.rb
  app/controllers/patients_controller.rb
  app/controllers/session_attendances_controller.rb
  app/controllers/session_dates_controller.rb
  app/controllers/sessions/outcome_controller.rb
  app/controllers/sessions/register_controller.rb
  app/controllers/vaccination_records_controller.rb
  app/forms/search_form.rb
  app/forms/session_programmes_form.rb
  app/jobs/status_updater_job.rb
  app/lib/reports/careplus_exporter.rb
  app/lib/status_updater.rb
  app/models/concerns/patient_session_status_concern.rb
  app/models/patient.rb
  app/models/patient_session.rb
  app/models/patient_session/register_outcome.rb
  app/models/patient_session/session_outcome.rb
  app/models/patient_session/session_status.rb
  app/models/school_move.rb
  app/models/session_attendance.rb
  app/models/session_date.rb
  config/environments/production.rb
  config/locales/status.en.yml
  db/migrate/20250325065344_create_patient_session_session_status.rb
  db/schema.rb
  spec/components/app_programme_session_table_component_spec.rb
  spec/factories/patient_session_session_statuses.rb
  spec/factories/patient_sessions.rb
  spec/features/delete_vaccination_record_spec.rb
  spec/forms/search_form_spec.rb
  spec/jobs/status_updater_job_spec.rb
  spec/lib/status_updater_spec.rb
  spec/models/patient_session/session_outcome_spec.rb
  spec/models/patient_session/session_status_spec.rb
Labels: ⌛️ performance

#3275 Cache register status in database
  app/components/app_outcome_banner_component.rb
  app/components/app_patient_session_search_result_card_component.rb
  app/components/app_session_actions_component.rb
  app/components/app_vaccinate_form_component.rb
  app/controllers/sessions/record_controller.rb
  app/controllers/sessions/register_controller.rb
  app/forms/search_form.rb
  app/lib/status_updater.rb
  app/models/patient_session.rb
  app/models/patient_session/register_outcome.rb
  app/models/patient_session/registration_status.rb
  app/policies/session_attendance_policy.rb
  app/views/patient_sessions/_header.html.erb
  db/migrate/20250325213928_create_patient_session_registration_status.rb
  db/schema.rb
  spec/components/app_session_actions_component_spec.rb
  spec/factories/patient_session_registration_statuses.rb
  spec/factories/patient_sessions.rb
  spec/factories/patients.rb
  spec/features/doubles_vaccination_cannot_record_as_admin_spec.rb
  spec/lib/status_updater_spec.rb
  spec/models/patient_session/registration_status_spec.rb
  spec/models/patient_session_spec.rb
Labels: ⌛️ performance

#3283 Improve performance reporting by avoiding unnecessary preloading
  app/lib/reports/careplus_exporter.rb
  app/lib/reports/export_formatters.rb
  app/lib/reports/offline_session_exporter.rb
  app/lib/reports/programme_vaccinations_exporter.rb
  app/lib/reports/systm_one_exporter.rb
  app/models/patient_session.rb
  spec/lib/reports/programme_vaccinations_exporter_spec.rb
Labels: ⌛️ performance

#3280 Avoid unnecessary preloading
  app/components/app_imports_navigation_component.rb
  app/components/app_outcome_banner_component.rb
  app/components/app_patient_page_component.html.erb
  app/components/app_patient_page_component.rb
  app/components/app_patient_vaccination_table_component.rb
  app/components/app_session_actions_component.rb
  app/components/app_session_details_summary_component.rb
  app/components/app_simple_status_banner_component.rb
  app/components/app_triage_form_component.rb
  app/controllers/concerns/vaccination_mailer_concern.rb
  app/controllers/consents_controller.rb
  app/controllers/gillick_assessments_controller.rb
  app/controllers/patient_sessions_controller.rb
  app/controllers/patients_controller.rb
  app/controllers/programmes_controller.rb
  app/controllers/sessions/consent_controller.rb
  app/controllers/sessions/outcome_controller.rb
  app/controllers/sessions/record_controller.rb
  app/controllers/sessions/register_controller.rb
  app/controllers/sessions/triage_controller.rb
  app/controllers/sessions_controller.rb
  app/controllers/triages_controller.rb
  app/controllers/vaccination_records_controller.rb
  app/controllers/vaccinations_controller.rb
  app/forms/vaccinate_form.rb
  app/jobs/school_session_reminders_job.rb
  app/lib/consent_grouper.rb
  app/models/draft_consent.rb
  app/models/draft_vaccination_record.rb
  app/models/patient.rb
  app/models/patient/consent_status.rb
  app/models/patient/triage_status.rb
  app/models/patient/vaccination_status.rb
  app/models/patient_session.rb
  app/models/patient_session/registration_status.rb
  app/models/patient_session/session_status.rb
  app/models/school_move.rb
  app/models/session_notification.rb
  app/views/draft_consents/who.html.erb
  app/views/gillick_assessments/edit.html.erb
  app/views/sessions/show.html.erb
  spec/components/app_outcome_banner_component_spec.rb
  spec/components/app_session_actions_component_spec.rb
  spec/components/app_session_details_summary_component_spec.rb
  spec/forms/search_form_spec.rb
  spec/models/patient_session_spec.rb
Labels: ⌛️ performance

#3294 Allow build and deployment with single workflow
  .github/workflows/build-and-push-image.yml
  .github/workflows/continuous-deployment.yml
  .github/workflows/deploy-mavis.yml
  terraform/resources/github_actions_policy.json
Labels: 🛠️ refactor

#3304 Ensure conflicting consent has correct session status
  app/models/patient_session/session_status.rb
  spec/models/patient_session/session_status_spec.rb
Labels: 🐞 bug

#3306 Add training onboarding configuration for Leicestershire
  config/onboarding/leicestershire-training.yaml
Labels: 🗄️ operations

#3307 Add required permission for training deployment
  terraform/resources/github_actions_policy.json
Labels: 🐞 bug

#3310 Reduce preloading in school consent jobs
  app/jobs/school_consent_reminders_job.rb
  app/jobs/school_consent_requests_job.rb
Labels: ⌛️ performance

#3311 Fix Terraform linting issues
  terraform/app/env/copilotmigration.tfvars
  terraform/app/env/poc.tfvars
  terraform/app/env/preview.tfvars
  terraform/app/env/production.tfvars
  terraform/app/env/qa.tfvars
  terraform/app/env/test.tfvars
  terraform/app/env/training.tfvars
  terraform/app/modules/dns/main.tf
  terraform/app/modules/dns/variables.tf
  terraform/app/monitoring.tf
  terraform/app/variables.tf
  terraform/bootstrap/main.tf
Labels: 🛠️ refactor

#3291 Refactor Terraform feature enable variables
  terraform/app/env/copilotmigration.tfvars
  terraform/app/env/preview.tfvars
  terraform/app/env/production.tfvars
  terraform/app/env/qa.tfvars
  terraform/app/env/test.tfvars
  terraform/app/env/training.tfvars
  terraform/app/variables.tf
Labels: 🛠️ refactor

#3303 Set PDS job priority when importing records
  app/models/concerns/csv_importable.rb
Labels: 🐞 bug

#3290 Rename `disable_pds` variable
  app/jobs/bulk_update_patients_from_pds_job.rb
  app/models/concerns/csv_importable.rb
  config/settings.yml
  config/settings/development.yml
  terraform/app/env/copilotmigration.tfvars
  terraform/app/env/preview.tfvars
  terraform/app/env/training.tfvars
  terraform/app/variables.tf
Labels: 🛠️ refactor

#3301 Add `PatientSession#includes_programmes`
  app/controllers/consent_forms_controller.rb
  app/controllers/patients_controller.rb
  app/controllers/sessions/consent_controller.rb
  app/controllers/sessions/outcome_controller.rb
  app/controllers/sessions/register_controller.rb
  app/controllers/sessions/triage_controller.rb
  app/jobs/school_session_reminders_job.rb
  app/jobs/send_clinic_initial_invitations_job.rb
  app/models/patient_session.rb
Labels: 🛠️ refactor

#3331 Add leicestershire production yaml
  config/onboarding/leicestershire-production.yaml
Labels: 🗄️ operations

#3285 Design tweaks
  app/assets/stylesheets/_button.scss
  app/assets/stylesheets/_filters.scss
  app/components/app_patient_session_table_component.rb
  app/components/app_search_component.rb
Labels: 🧑‍🎨 design tweak

#3346 Ignore exceptions related to team-only API keys
  config/initializers/sentry.rb
Labels: 🗄️ operations

#3345 Ignore health check transactions
  config/initializers/sentry.rb
Labels: 🗄️ operations

#3317 Refactor CSV parsing in preparation for future enhancements
  app/models/cohort_import.rb
  app/models/cohort_import_row.rb
  app/models/concerns/csv_importable.rb
  app/models/immunisation_import.rb
  app/models/immunisation_import_row.rb
  app/models/patient_import.rb
  app/models/patient_import_row.rb
  config/locales/en.yml
  spec/features/import_child_records_spec.rb
  spec/features/import_class_lists_spec.rb
  spec/fixtures/class_import/invalid_headers.csv
  spec/fixtures/cohort_import/invalid_headers.csv
  spec/fixtures/immunisation_import/missing_headers.csv
  spec/models/class_import_row_spec.rb
  spec/models/class_import_spec.rb
  spec/models/cohort_import_row_spec.rb
  spec/models/cohort_import_spec.rb
  spec/models/immunisation_import_row_spec.rb
  spec/models/immunisation_import_spec.rb
Labels: 🛠️ refactor

#3333 Remove Copilot deploy workflow
  .github/workflows/_deploy-template.yml
  .github/workflows/continuous-deployment.yml
  .github/workflows/deploy-mavis.yml
  .github/workflows/deploy.yml
Labels: 🛠️ refactor

#3314 Download school moves
  app/controllers/school_moves/exports_controller.rb
  app/lib/reports/csv_school_moves.rb
  app/lib/reports/export_formatters.rb
  app/models/school_move_export.rb
  app/views/school_moves/exports/confirm.html.erb
  app/views/school_moves/exports/dates.html.erb
  app/views/school_moves/index.html.erb
  config/routes.rb
  spec/features/download_school_moves_spec.rb
  spec/lib/reports/csv_school_moves_spec.rb
  spec/models/school_move_export_spec.rb
Labels: ✨ feature

#3321 Create ecs service module
  terraform/app/modules/ecs_service/main.tf
  terraform/app/modules/ecs_service/outputs.tf
  terraform/app/modules/ecs_service/variables.tf
Labels: 🛠️ refactor

#3329 Make gap between PDS jobs configurable
  app/jobs/bulk_update_patients_from_pds_job.rb
  app/models/concerns/csv_importable.rb
  config/settings.yml
Labels: 🗄️ operations

#3349 Set `MAVIS__PDS__WAIT_BETWEEN_JOBS` environment variable
  terraform/app/ssm_parameters.tf
  terraform/app/variables.tf
Labels: 🗄️ operations

#3322 Create modularized ecs services
  Dockerfile
  bin/docker-entrypoint
  bin/docker-start
  config/application.rb
  config/environments/development.rb
  config/puma.rb
  terraform/app/autoscaling.tf
  terraform/app/codedeploy.tf
  terraform/app/ecs.tf
  terraform/app/iam_policy_documents.tf
  terraform/app/modules/ecs_service/outputs.tf
  terraform/app/outputs.tf
  terraform/app/rds.tf
  terraform/app/variables.tf
Labels: ✨ feature

#3312 Support batches without expiration dates
  app/components/app_vaccination_record_summary_component.rb
  app/controllers/batches_controller.rb
  app/forms/batch_form.rb
  app/models/batch.rb
  app/models/dps_export_row.rb
  app/models/immunisation_import_row.rb
  app/models/vaccine.rb
  app/views/batches/edit.html.erb
  app/views/batches/new.html.erb
  app/views/draft_vaccination_records/batch.html.erb
  app/views/sessions/record/batch.html.erb
  app/views/vaccines/index.html.erb
  config/locales/en.yml
  db/migrate/20250402093102_change_batch_expiry_not_null.rb
  db/schema.rb
  spec/factories/batches.rb
  spec/factories/vaccination_records.rb
  spec/features/doubles_vaccination_administered_spec.rb
  spec/features/edit_vaccination_record_spec.rb
  spec/features/hpv_vaccination_administered_spec.rb
  spec/features/hpv_vaccination_clinic_spec.rb
  spec/features/hpv_vaccination_offline_spec.rb
  spec/features/menacwy_vaccination_administered_spec.rb
  spec/features/td_ipv_vaccination_administered_spec.rb
  spec/features/vaccination_todays_batch_spec.rb
  spec/forms/batch_form_spec.rb
  spec/lib/reports/offline_session_exporter_spec.rb
  spec/models/batch_spec.rb
  spec/models/immunisation_import_row_spec.rb
Labels: ✨ feature

#3318 Add `CSVParser` and `CSVParser::Field`
  app/lib/csv_parser.rb
  app/lib/reports/offline_session_exporter.rb
  app/models/cohort_import_row.rb
  app/models/concerns/csv_importable.rb
  app/models/immunisation_import_row.rb
  app/models/patient_import_row.rb
  spec/lib/csv_parser_spec.rb
  spec/models/class_import_row_spec.rb
  spec/models/cohort_import_row_spec.rb
  spec/models/cohort_import_spec.rb
  spec/models/immunisation_import_row_spec.rb
  spec/support/shared_examples/a_csv_importable_model.rb
Labels: 🛠️ refactor

#3327 Add support for uploading SystmOne vaccination records
  app/lib/vaccination_description_string_parser.rb
  app/models/immunisation_import_row.rb
  spec/fixtures/immunisation_import/systm_one.csv
  spec/lib/vaccination_description_string_parser_spec.rb
  spec/models/immunisation_import_row_spec.rb
  spec/models/immunisation_import_spec.rb
Labels: ✨ feature

#3323 Update deployment pipeline to work with modularized services
  .github/workflows/continuous-deployment.yml
  .github/workflows/deploy-application.yml
  .github/workflows/deploy-mavis.yml
  terraform/app/codedeploy.tf
  terraform/scripts/check_task_definition.sh
  terraform/scripts/validate_plan.sh
Labels: 🗄️ operations

#3353 Correct Leicestershire ODS code
  config/onboarding/leicestershire-production.yaml
  config/onboarding/leicestershire-training.yaml
Labels: 🐞 bug

#3358 Update workflow to access right element
  .github/workflows/deploy-application.yml
Labels: github_actions

#3356 Add feature flag for SystmOne imports
  app/models/immunisation_import_row.rb
  app/views/immunisation_imports/new.html.erb
  spec/models/immunisation_import_row_spec.rb
  spec/models/immunisation_import_spec.rb
Labels: 🗄️ operations

#3363 Ensure errors messages don't reference SystmOne
  app/models/immunisation_import_row.rb
  spec/models/immunisation_import_row_spec.rb
Labels: 🐞 bug

#3364 Update number of background tasks
  terraform/app/autoscaling.tf
  terraform/app/ecs.tf
  terraform/app/env/copilotmigration.tfvars
  terraform/app/env/poc.tfvars
  terraform/app/env/preview.tfvars
  terraform/app/env/production.tfvars
  terraform/app/env/qa.tfvars
  terraform/app/env/test.tfvars
  terraform/app/env/training.tfvars
  terraform/app/iam_policy_documents.tf
  terraform/app/variables.tf
Labels: ⌛️ performance

#3367 Specify preloading rules explicitly
  app/models/patient_session.rb
  spec/features/manage_attendance_spec.rb
Labels: 🐞 bug

#3374 Ensure year group integer value is validated
  app/models/patient_import_row.rb
  spec/models/class_import_row_spec.rb
  spec/models/cohort_import_row_spec.rb
Labels: bug

#3373 Revert "must be blank" content
  app/models/immunisation_import_row.rb
  app/models/patient_import_row.rb
  spec/models/immunisation_import_row_spec.rb
Labels: bug

#3375 Allow fractional wait time between PDS jobs
  app/jobs/bulk_update_patients_from_pds_job.rb
  app/models/concerns/csv_importable.rb
  config/settings.yml
Labels: operations

#3376 Make GOOD_JOB_MAX_THREADS configurable
  terraform/app/iam_policy_documents.tf
  terraform/app/ssm_parameters.tf
  terraform/app/variables.tf
Labels: performance

#3378 Make max ACU capacity for rds a variable amount
  terraform/app/env/production.tfvars
  terraform/app/rds.tf
  terraform/app/variables.tf
Labels: performance

#3379 Make `MAVIS__PDS__ENQUEUE_BULK_UPDATES` configurable
  terraform/app/env/copilotmigration.tfvars
  terraform/app/env/preview.tfvars
  terraform/app/env/qa.tfvars
  terraform/app/env/training.tfvars
  terraform/app/iam_policy_documents.tf
  terraform/app/ssm_parameters.tf
  terraform/app/variables.tf
Labels: operations

#3389 Fix bug where searching with no results would raise an error
  app/jobs/send_clinic_initial_invitations_job.rb
  app/models/patient_session.rb
  spec/features/patient_search_spec.rb
Labels: bug

#3392 Add linting to script and ci
  .github/workflows/lint.yml
  bin/lint
Labels: github_actions

#3388 Add Essex schools to Hertfordshire onboarding
  config/onboarding/hertfordshire-production.yaml
Labels: operations

#3399 Add Essex schools to Hertfordshire training
  config/onboarding/hertfordshire-training-with-sessions.yaml
  config/onboarding/hertfordshire-training.yaml
Labels: operations

#3249 Update design of patient session table
  app/components/app_patient_session_table_component.rb
  app/helpers/sessions_helper.rb
  spec/components/app_patient_session_table_component_spec.rb
  spec/helpers/sessions_helper_spec.rb
Labels: design tweak

#3250 Update session activity log entry
  app/components/app_activity_log_component.rb
  spec/components/app_activity_log_component_spec.rb
  spec/features/manage_children_spec.rb
Labels: design tweak

#3390 Remove BATCH_EXPIRY_DATE from SystmOne fixture
  spec/fixtures/immunisation_import/systm_one.csv
Labels: refactor

#3387 Avoid sending consent reminders to new patients
  app/jobs/school_consent_reminders_job.rb
  app/models/consent_notification.rb
  spec/jobs/school_consent_reminders_job_spec.rb
Labels: bug

#3334 Remove obsolete Copilot-related code
  .dockerignore
  .tool-versions
  copilot/.workspace
  copilot/environments/accessibility/manifest.yml
  copilot/environments/addons/addons.parameters.yml
  copilot/environments/addons/db.yml
  copilot/environments/copilotmigration/manifest.yml
  copilot/environments/overrides/README.md
  copilot/environments/overrides/cfn.patches.yml
  copilot/environments/pentest/manifest.yml
  copilot/environments/preview/manifest.yml
  copilot/environments/production/manifest.yml
  copilot/environments/qa/manifest.yml
  copilot/environments/test/manifest.yml
  copilot/environments/training/manifest.yml
  copilot/webapp/manifest.yml
  docs/aws-copilot.md
Labels: refactor

#3380 Refactor use of ssm parameters
  terraform/app/env/copilotmigration.tfvars
  terraform/app/env/poc.tfvars
  terraform/app/env/preview.tfvars
  terraform/app/env/qa.tfvars
  terraform/app/env/training.tfvars
  terraform/app/iam_policy_documents.tf
  terraform/app/ssm_parameters.tf
  terraform/app/variables.tf
  terraform/scripts/bootstrap.sh
Labels: infrastructure

#3384 Maintain a list of supported feature flags
  app/lib/feature_flag_factory.rb
  bin/docker-entrypoint
  config/feature_flags.yml
  db/seeds.rb
  lib/tasks/feature_flags.rake
  spec/lib/feature_flag_factory_spec.rb
Labels: refactor

#3395 Include TFLint into the CI pipeline
  .github/workflows/lint.yml
  bin/lint
  terraform/.tflint.hcl
  terraform/app/modules/dns/main.tf
  terraform/app/modules/dns/outputs.tf
  terraform/app/modules/ecs_service/main.tf
  terraform/app/modules/vpc_endpoint/main.tf
  terraform/bootstrap/main.tf
  terraform/bootstrap/outputs.tf
  terraform/hooks/lint.sh
Labels: operations

#3386 Improve feature flag interface
  app/lib/feature_flag_factory.rb
  config/feature_flags.yml
  config/initializers/flipper.rb
Labels: design tweak

#3324 Use only today's prescreening data for VaccinateForm initialisation
  app/components/app_patient_page_component.rb
  app/forms/vaccinate_form.rb
  app/models/pre_screening.rb
  app/models/session_date.rb
  db/migrate/20250403155909_add_session_date_id_to_pre_screenings.rb
  db/schema.rb
  spec/components/app_patient_page_component_spec.rb
  spec/factories/pre_screenings.rb
  spec/features/doubles_vaccination_administered_spec.rb
  spec/models/pre_screening_spec.rb
Labels: bug

#3410 Replace non-breaking space characters
  app/lib/csv_parser.rb
  spec/lib/csv_parser_spec.rb
Labels: operations

#3411 Don't require VACCINATED column
  app/models/immunisation_import_row.rb
  spec/models/immunisation_import_row_spec.rb
Labels: operations

#3252 Validate individual pre-screening questions
  app/components/app_patient_page_component.html.erb
  app/components/app_patient_page_component.rb
  app/components/app_vaccinate_form_component.html.erb
  app/components/app_vaccinate_form_component.rb
  app/controllers/vaccinations_controller.rb
  app/forms/vaccinate_form.rb
  app/models/pre_screening.rb
  config/locales/en.yml
  spec/components/app_vaccinate_form_component_spec.rb
  spec/features/hpv_vaccination_pre_screening_spec.rb
  spec/models/pre_screening_spec.rb
Labels: design tweak

#3419 Ensure pipeline jobs exit with failure
  .github/workflows/deploy-application.yml
  .github/workflows/deploy-infrastructure.yml
  .github/workflows/destroy-infrastructure.yml
Labels: infrastructure

#3265 Timeline records UI
  app/assets/stylesheets/_timeline.scss
  app/assets/stylesheets/application.scss
  app/components/app_timeline_filter_component.html.erb
  app/components/app_timeline_filter_component.rb
  app/components/app_timeline_table_component.html.erb
  app/components/app_timeline_table_component.rb
  app/controllers/inspect/timeline/patients_controller.rb
  app/views/inspect/timeline/patients/show.html.erb
  config/routes.rb
  lib/timeline_records.rb
  spec/features/timeline_records_spec.rb
  spec/lib/timeline_records_spec.rb
Labels: operations

#3417 Don't link to vaccination records
  app/components/app_patient_table_component.html.erb
  app/components/app_patient_table_component.rb
  app/components/app_vaccination_record_table_component.html.erb
  app/components/app_vaccination_record_table_component.rb
  app/views/imports/show.html.erb
  app/views/vaccination_records/index.html.erb
  spec/components/app_vaccination_record_table_component_spec.rb
Labels: design tweak

#3394 Track school open/closed status
  app/models/location.rb
  app/models/onboarding.rb
  db/migrate/20250414092500_add_status_to_locations.rb
  db/schema.rb
  lib/tasks/schools.rake
  spec/factories/locations.rb
  spec/fixtures/files/onboarding/invalid.yaml
  spec/models/location_spec.rb
  spec/models/onboarding_spec.rb
Labels: operations

#3381 Refactor how PDS update jobs are queued
  app/jobs/enqueue_update_patients_from_pds_job.rb
  app/lib/update_patients_from_pds.rb
  app/models/concerns/csv_importable.rb
  spec/lib/update_patients_from_pds_spec.rb
Labels: refactor

#3393 Overwrite db/data/dfe-schools.zip
  lib/tasks/schools.rake
Labels: operations

#3423 Rename poc environments
  .github/workflows/deploy-application.yml
  .github/workflows/deploy-infrastructure.yml
  .github/workflows/deploy.yml
  .github/workflows/destroy-infrastructure.yml
  terraform/app/env/copilotmigration.tfvars
  terraform/app/env/poc.tfvars
  terraform/app/env/sandbox-alpha-backend.hcl
  terraform/app/env/sandbox-alpha.tfvars
  terraform/app/env/sandbox-beta-backend.hcl
  terraform/app/env/sandbox-beta.tfvars
  terraform/app/variables.tf
  terraform/scripts/bootstrap.sh
Labels: infrastructure

#3357 Don't send clinic invitations incorrectly
  app/jobs/concerns/send_clinic_invitations_concern.rb
  spec/jobs/send_clinic_initial_invitations_job_spec.rb
Labels: bug

#3443 Add required permissions for ECS autoscaling
  terraform/resources/github_actions_policy.json
Labels: infrastructure

#3407 Prepare restriction of AWS permissions for github workflows
  .github/workflows/build-and-push-image.yml
  .github/workflows/deploy-application.yml
  .github/workflows/deploy-infrastructure.yml
  .github/workflows/deploy.yml
  README.md
Labels: infrastructure

#3412 Use hk to run linters
  .github/workflows/lint.yml
  .rubocop.yml
  .rufo
  .tool-versions
  README.md
  bin/lint
  docs/branching.md
  docs/releasing.md
  hk.pkl
Labels: refactor

#3448 Small validation improvements to SystmOne import
  app/models/immunisation_import_row.rb
  spec/fixtures/immunisation_import/systm_one.csv
  spec/models/immunisation_import_row_spec.rb
  spec/models/immunisation_import_spec.rb
Labels: data consistency

#3446 Upgrade DB version for QA and Test
  terraform/app/env/qa.tfvars
  terraform/app/env/test.tfvars
  terraform/app/rds.tf
  terraform/app/variables.tf
Labels: infrastructure

#3462 Allow programme vaccination types without dose sequence
  app/models/immunisation_import_row.rb
  spec/fixtures/immunisation_import/systm_one.csv
  spec/models/immunisation_import_spec.rb
Labels: bug

#3466 Fix school consent reminders cron job
  config/environments/production.rb
Labels: bug

#3468 Include moves out in school moves export
  app/lib/reports/school_moves_exporter.rb
  app/models/school_move_export.rb
  app/models/school_move_log_entry.rb
  app/views/school_moves/exports/confirm.html.erb
  db/migrate/20250429140846_remove_move_to_school_from_school_move_log_entries.rb
  db/schema.rb
  spec/factories/school_move_log_entries.rb
  spec/features/download_school_moves_spec.rb
  spec/lib/reports/school_moves_exporter_spec.rb
  spec/models/school_move_export_spec.rb
  spec/models/school_move_log_entry_spec.rb
Labels: bug

#3470 Ensure cron jobs reference valid classes
  config/cron_jobs.rb
  config/environments/production.rb
  config/environments/staging.rb
  spec/lib/cron_jobs_spec.rb
Labels: refactor

#3292 Add NHS number format validation to imports
  app/models/immunisation_import_row.rb
  app/models/patient.rb
  app/models/patient_import_row.rb
  app/validators/nhs_number_validator.rb
  spec/models/class_import_row_spec.rb
  spec/models/cohort_import_row_spec.rb
  spec/models/immunisation_import_row_spec.rb
  spec/validators/nhs_number_validator_spec.rb
Labels: bug

#3465 Remove brakeman from pre-commit and fail on changed files
  .tool-versions
  hk.pkl
Labels: github_actions

#3295 Validate NHS number check digit
  app/validators/nhs_number_validator.rb
  spec/components/app_child_summary_component_spec.rb
  spec/components/app_patient_table_component_spec.rb
  spec/features/e2e_journey_spec.rb
  spec/features/import_child_records_spec.rb
  spec/features/import_child_records_with_duplicates_spec.rb
  spec/features/import_class_lists_spec.rb
  spec/features/import_class_lists_with_duplicates_spec.rb
  spec/features/manage_children_spec.rb
  spec/fixtures/class_import/duplicates.csv
  spec/fixtures/class_import/invalid_fields.csv
  spec/fixtures/class_import/valid.csv
  spec/fixtures/class_import/valid_extra_fields.csv
  spec/fixtures/cohort_import/duplicate_nhs_numbers.csv
  spec/fixtures/cohort_import/invalid_fields.csv
  spec/fixtures/cohort_import/valid.csv
  spec/fixtures/cohort_import/valid_1000_rows.csv
  spec/fixtures/cohort_import/valid_extra_fields.csv
  spec/fixtures/cohort_import/valid_iso_8859_1_encoding.csv
  spec/fixtures/cohort_import/valid_with_changes.csv
  spec/fixtures/immunisation_import/valid_flu.csv
  spec/fixtures/immunisation_import/valid_hpv.csv
  spec/models/class_import_spec.rb
  spec/models/cohort_import_row_spec.rb
  spec/models/cohort_import_spec.rb
  spec/models/immunisation_import_row_spec.rb
  spec/validators/nhs_number_validator_spec.rb
Labels: operations

#3210 Show a more meaningful error to users from organisations that aren't set up in Mavis
  app/controllers/concerns/authentication_concern.rb
  app/controllers/users/omniauth_callbacks_controller.rb
  app/views/users/errors/organisation_not_found.html.erb
  lib/omni_auth_strategies_openid_connect_patch.rb
  spec/features/user_cis2_authentication_with_empty_role_spec.rb
  spec/features/user_cis2_authentication_with_wrong_organisation_spec.rb
  spec/features/user_cis2_authentication_with_wrong_role_spec.rb
  spec/features/user_cis2_authentication_with_wrong_workgroup_spec.rb
  spec/support/cis2_auth_helper.rb
Labels: design tweak

#3300 Improve patient search result ordering
  app/controllers/patients_controller.rb
  spec/forms/search_form_spec.rb
  spec/models/patient_spec.rb
Labels: operations

#3475 Fix issues in linting workflow
  .github/workflows/lint.yml
  db/migrate/20250429140846_remove_move_to_school_from_school_move_log_entries.rb
  hk.pkl
  spec/lib/reports/school_moves_exporter_spec.rb
Labels: github_actions, refactor

#3409 Accumulate gender on import
  app/models/patient_import_row.rb
  spec/models/class_import_row_spec.rb
  spec/models/cohort_import_row_spec.rb
Labels: feature

#3398 Choose vaccine when choosing a batch
  app/components/app_vaccinate_form_component.html.erb
  app/components/app_vaccinate_form_component.rb
  app/controllers/draft_vaccination_records_controller.rb
  app/forms/vaccinate_form.rb
  app/models/draft_vaccination_record.rb
  app/models/programme.rb
  app/models/vaccine.rb
  app/views/draft_vaccination_records/batch.html.erb
  app/views/draft_vaccination_records/confirm.html.erb
  app/views/draft_vaccination_records/vaccine.html.erb
  config/locales/en.yml
  config/vaccines.yml
  spec/features/edit_vaccination_record_spec.rb
  spec/features/hpv_vaccination_administered_spec.rb
  spec/features/menacwy_vaccination_administered_spec.rb
  spec/features/td_ipv_vaccination_administered_spec.rb
  spec/models/draft_vaccination_record_spec.rb
  spec/models/programme_spec.rb
  spec/models/vaccine_spec.rb
Labels: feature

#3469 Update PostgreSQL to 16.8
  terraform/app/rds.tf
Labels: infrastructure
