Repository nhsuk/manage-vaccinations-in-schools, pull requests merged in 2025-02, with the labels that each got.

#2921 Handle school move log entries when merging patients
  app/lib/patient_merger.rb
  app/models/school_move_log_entry.rb
  db/migrate/20250201201237_add_school_move_log_entries_foreign_keys.rb
  db/schema.rb
  spec/factories/school_move_log_entries.rb
  spec/lib/govuk_notify_personalisation_spec.rb
  spec/lib/patient_merger_spec.rb
  spec/models/school_move_log_entry_spec.rb
Labels: 🐞 bug

#2922 Increase wait time between PDS jobs
  app/jobs/bulk_update_patients_from_pds_job.rb
  app/models/concerns/csv_importable.rb
Labels: 🐞 bug

#2923 Increase wait time per executions
  app/jobs/concerns/nhs_api_concurrency_concern.rb
Labels: 🗄️ operations

#2924 Improvements to NHS job concurency configuration
  app/jobs/bulk_update_patients_from_pds_job.rb
  app/jobs/concerns/nhs_api_concurrency_concern.rb
  app/models/concerns/csv_importable.rb
Labels: 🐞 bug

#2917 Add ability to edit vaccination record notes
  app/components/app_vaccination_record_summary_component.rb
  app/controllers/draft_vaccination_records_controller.rb
  app/controllers/vaccinations_controller.rb
  app/models/draft_vaccination_record.rb
  app/views/draft_vaccination_records/confirm.html.erb
  app/views/draft_vaccination_records/notes.html.erb
  spec/components/app_vaccination_record_summary_component_spec.rb
  spec/features/edit_vaccination_record_spec.rb
Labels: ✨ feature

#2934 Ensure patient merging works with audited and strict loading
  app/controllers/patients/edit_controller.rb
  app/lib/patient_merger.rb
  spec/lib/patient_merger_spec.rb
Labels: 🐞 bug

#2936 Increase interval between PDS jobs
  app/jobs/bulk_update_patients_from_pds_job.rb
  app/models/concerns/csv_importable.rb
  config/environments/production.rb
Labels: 🗄️ operations

#2941 Remove max threads override for test environment
  copilot/webapp/manifest.yml
Labels: ⌛️ performance

#2783 Replace cohorts with organisations directly
  app/components/app_patient_cohort_table_component.html.erb
  app/components/app_patient_cohort_table_component.rb
  app/controllers/cohorts_controller.rb
  app/controllers/consents_controller.rb
  app/controllers/dev_controller.rb
  app/controllers/import_issues_controller.rb
  app/controllers/patient_sessions_controller.rb
  app/controllers/patients_controller.rb
  app/controllers/programmes_controller.rb
  app/controllers/triages_controller.rb
  app/controllers/vaccination_records_controller.rb
  app/controllers/vaccinations_controller.rb
  app/lib/reports/offline_session_exporter.rb
  app/lib/reports/programme_vaccinations_exporter.rb
  app/models/cohort.rb
  app/models/concerns/year_group_concern.rb
  app/models/organisation.rb
  app/models/patient.rb
  app/models/patient_import_row.rb
  app/models/programme.rb
  app/models/school_move.rb
  app/policies/patient_policy.rb
  app/policies/school_move_policy.rb
  app/views/cohorts/index.html.erb
  app/views/cohorts/show.html.erb
  app/views/programmes/index.html.erb
  db/migrate/20241219115056_add_organisation_to_patients.rb
  db/schema.rb
  db/seeds.rb
  lib/core_ext/integer/year_group.rb
  spec/components/app_patient_cohort_table_component_spec.rb
  spec/components/app_patient_table_component_spec.rb
  spec/factories/cohorts.rb
  spec/factories/patients.rb
  spec/features/dev_reset_organisation_spec.rb
  spec/features/manage_children_spec.rb
  spec/features/patient_search_spec.rb
  spec/models/class_import_row_spec.rb
  spec/models/class_import_spec.rb
  spec/models/cohort_import_row_spec.rb
  spec/models/cohort_import_spec.rb
  spec/models/concerns/pending_changes_concern_spec.rb
  spec/models/immunisation_import_row_spec.rb
  spec/models/patient_spec.rb
  spec/models/school_move_spec.rb
  spec/policies/patient_policy_spec.rb
Labels: 📐 data_consistency, 🛠️ refactor

#2850 Remove mailers
  Gemfile
  Gemfile.lock
  app/jobs/notify_delivery_job.rb
  app/mailers/application_mailer.rb
  app/mailers/consent_mailer.rb
  app/mailers/session_mailer.rb
  app/mailers/triage_mailer.rb
  app/mailers/vaccination_mailer.rb
  config/application.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/staging.rb
  config/environments/test.rb
  config/settings/test.yml
  spec/jobs/email_delivery_job_spec.rb
  spec/jobs/sms_delivery_job_spec.rb
  spec/mailers/application_mailer_spec.rb
  spec/mailers/consent_mailer_spec.rb
  spec/mailers/session_mailer_spec.rb
  spec/mailers/triage_mailer_spec.rb
  spec/mailers/vaccination_mailer_spec.rb
Labels: 🛠️ refactor

#2899 Stop using recipient column
  app/components/app_activity_log_component.rb
  app/jobs/email_delivery_job.rb
  app/jobs/sms_delivery_job.rb
  app/models/notify_log_entry.rb
  db/migrate/20250128100040_make_notify_log_entry_recipient_null.rb
  db/schema.rb
  lib/tasks/notify_log_entries.rake
  spec/factories/notify_log_entries.rb
  spec/jobs/email_delivery_job_spec.rb
  spec/jobs/sms_delivery_job_spec.rb
  spec/models/notify_log_entry_spec.rb
Labels: 📐 data_consistency, 🛠️ refactor

#2912 Remove patient invalidating when editing NHS number
  app/controllers/patients/edit_controller.rb
  spec/features/manage_children_spec.rb
Labels: 🐞 bug

#2913 Set CSV report date format to ISO8601
  app/lib/reports/programme_vaccinations_exporter.rb
  spec/lib/reports/programme_vaccinations_exporter_spec.rb
Labels: ✨ feature

#2918 Add GILLICK_NOTIFY_PARENTS column to report
  app/lib/reports/programme_vaccinations_exporter.rb
  spec/lib/reports/programme_vaccinations_exporter_spec.rb
Labels: ✨ feature

#2919 Remove duplicate preloading
  app/controllers/vaccination_records_controller.rb
Labels: 🛠️ refactor

#2947 Fix CSV line number in import errors
  app/models/concerns/csv_importable.rb
  spec/features/import_child_records_spec.rb
  spec/features/import_vaccination_records_spec.rb
  spec/models/cohort_import_spec.rb
  spec/models/immunisation_import_spec.rb
Labels: 🐞 bug

#2946 Document alternative date format for vaccination record upload
  app/components/app_import_format_details_component.rb
Labels: 🐞 bug

#2939 Filter triage and consents by programme
  app/components/app_activity_log_component.rb
  app/components/app_consent_component.rb
  app/components/app_outcome_banner_component.rb
  app/components/app_patient_page_component.html.erb
  app/components/app_patient_page_component.rb
  app/components/app_session_patient_table_component.rb
  app/components/app_simple_status_banner_component.rb
  app/components/app_triage_form_component.rb
  app/components/app_triage_notes_component.rb
  app/controllers/concerns/vaccination_mailer_concern.rb
  app/controllers/consents_controller.rb
  app/controllers/draft_consents_controller.rb
  app/controllers/gillick_assessments_controller.rb
  app/controllers/patient_sessions_controller.rb
  app/controllers/programmes_controller.rb
  app/controllers/register_attendances_controller.rb
  app/controllers/session_attendances_controller.rb
  app/controllers/triages_controller.rb
  app/controllers/vaccination_records_controller.rb
  app/jobs/clinic_session_invitations_job.rb
  app/jobs/school_session_reminders_job.rb
  app/jobs/vaccination_confirmations_job.rb
  app/lib/reports/careplus_exporter.rb
  app/lib/reports/offline_session_exporter.rb
  app/lib/reports/programme_vaccinations_exporter.rb
  app/models/concerns/patient_session_status_concern.rb
  app/models/draft_consent.rb
  app/models/draft_vaccination_record.rb
  app/models/patient.rb
  app/models/patient_session.rb
  app/models/session_notification.rb
  app/views/consents/index.html.erb
  spec/components/app_activity_log_component_spec.rb
  spec/components/app_consent_component_spec.rb
  spec/components/app_outcome_banner_component_spec.rb
  spec/components/app_simple_status_banner_component_spec.rb
  spec/components/app_triage_notes_component_spec.rb
  spec/controllers/concerns/triage_mailer_concern_spec.rb
  spec/controllers/concerns/vaccination_mailer_concern_spec.rb
  spec/features/triage_spec.rb
  spec/features/verbal_consent_given_when_previously_refused_spec.rb
  spec/models/patient_session_spec.rb
  spec/models/session_notification_spec.rb
Labels: 🛠️ refactor

#2948 Require VACCINE_GIVEN when importing immunisations
  app/components/app_import_format_details_component.rb
  app/models/immunisation_import_row.rb
  spec/features/hpv_vaccination_offline_spec.rb
  spec/fixtures/immunisation_import/valid_flu.csv
Labels: 🗄️ operations

#2942 Handle vaccination records outside the organisation
  app/controllers/vaccinations_controller.rb
  app/forms/vaccinate_form.rb
  app/models/draft_vaccination_record.rb
  app/models/immunisation_import_row.rb
  app/models/vaccination_record.rb
  app/policies/vaccination_record_policy.rb
  config/locales/en.yml
  db/migrate/20250207091449_add_organisation_to_vaccination_records.rb
  db/schema.rb
  spec/factories/vaccination_records.rb
  spec/features/import_vaccination_records_spec.rb
  spec/models/immunisation_import_row_spec.rb
  spec/models/vaccination_record_spec.rb
Labels: ✨ feature

#2961 Add Td/IPV and MenACWY programmes
  app/models/programme.rb
  app/models/vaccine.rb
  config/locales/en.yml
  spec/factories/programmes.rb
  spec/models/class_import_spec.rb
Labels: 📐 data_consistency

#2958 Import cohorts and immunisations across multiple programmes
  app/components/app_import_format_details_component.rb
  app/components/app_imports_table_component.html.erb
  app/components/app_imports_table_component.rb
  app/components/app_programme_navigation_component.rb
  app/controllers/class_imports_controller.rb
  app/controllers/cohort_imports_controller.rb
  app/controllers/immunisation_imports_controller.rb
  app/controllers/import_issues_controller.rb
  app/controllers/imports_controller.rb
  app/models/cohort_import.rb
  app/models/cohort_import_row.rb
  app/models/immunisation_import.rb
  app/models/immunisation_import_row.rb
  app/models/organisation.rb
  app/models/programme.rb
  app/views/cohort_imports/new.html.erb
  app/views/cohorts/index.html.erb
  app/views/immunisation_imports/new.html.erb
  app/views/import_issues/index.html.erb
  app/views/import_issues/show.html.erb
  app/views/imports/index.html.erb
  app/views/imports/new.html.erb
  app/views/imports/show.html.erb
  app/views/programmes/patients.html.erb
  app/views/vaccination_records/index.html.erb
  config/routes.rb
  db/migrate/20250210091908_remove_programme_from_immunisation_imports.rb
  db/migrate/20250210092331_remove_programme_from_cohort_imports.rb
  db/schema.rb
  db/seeds.rb
  spec/components/app_import_format_details_component_spec.rb
  spec/components/app_imports_table_component_spec.rb
  spec/factories/cohort_imports.rb
  spec/factories/immunisation_imports.rb
  spec/features/e2e_journey_spec.rb
  spec/features/import_child_records_slow_spec.rb
  spec/features/import_child_records_spec.rb
  spec/features/import_vaccination_records_spec.rb
  spec/models/cohort_import_row_spec.rb
  spec/models/cohort_import_spec.rb
  spec/models/immunisation_import_row_spec.rb
  spec/models/immunisation_import_spec.rb
Labels: 📐 data_consistency, 🛠️ refactor

#2964 Add Td/IPV and MenACWY vaccines
  config/vaccines.yml
  spec/factories/programmes.rb
  spec/factories/vaccines.rb
Labels: 📐 data_consistency

#2969 Don't move patients to clinic if consent is refused
  app/controllers/sessions_controller.rb
  app/models/session.rb
  app/views/sessions/close.html.erb
  spec/models/session_spec.rb
Labels: 🐞 bug

#2967 Search globally for patients when merging
  app/controllers/patients/edit_controller.rb
  app/lib/patient_merger.rb
  spec/lib/patient_merger_spec.rb
Labels: 🐞 bug

#2965 Filter vaccination records by programme
  app/components/app_activity_log_component.rb
  app/components/app_outcome_banner_component.rb
  app/components/app_patient_page_component.html.erb
  app/components/app_simple_status_banner_component.rb
  app/controllers/patient_sessions_controller.rb
  app/controllers/patients_controller.rb
  app/controllers/session_attendances_controller.rb
  app/jobs/clinic_session_invitations_job.rb
  app/lib/reports/careplus_exporter.rb
  app/lib/reports/offline_session_exporter.rb
  app/models/concerns/patient_session_status_concern.rb
  app/models/immunisation_import.rb
  app/models/organisation.rb
  app/models/patient.rb
  app/models/patient_session.rb
  app/models/session.rb
  app/policies/session_attendance_policy.rb
  spec/components/app_outcome_banner_component_spec.rb
  spec/components/app_simple_status_banner_component_spec.rb
  spec/models/patient_session_spec.rb
Labels: 🐞 bug, ✨ feature

#2971 Avoid double ORGANISATION_CODE errors
  app/models/immunisation_import_row.rb
  spec/models/immunisation_import_row_spec.rb
Labels: 🛠️ refactor

#2966 Sort patients by surname
  app/models/concerns/full_name_concern.rb
  app/models/patient_session.rb
  spec/models/patient_spec.rb
Labels: 🗄️ operations

#2972 Add feature flag for GILLICK_NOTIFY_PARENTS
  app/lib/reports/programme_vaccinations_exporter.rb
  spec/lib/reports/programme_vaccinations_exporter_spec.rb
Labels: 🗄️ operations

#2975 Add patient to sessions when importing vaccinations
  app/models/immunisation_import.rb
  app/models/immunisation_import_row.rb
  spec/models/immunisation_import_spec.rb
Labels: 🐞 bug

#2976 Add Hertfordshire onboarding configuration
  config/onboarding/hertfordshire-production.yaml
Labels: 🗄️ operations

#2973 Update environment banner for Heroku review apps
  app/components/app_hosting_environment_component.rb
Labels: 🗄️ operations

#2968 Restrict editing vaccination records
  app/controllers/draft_vaccination_records_controller.rb
  app/policies/vaccination_record_policy.rb
  spec/policies/vaccination_record_policy_spec.rb
Labels: 🗄️ operations

#2960 Update imports to match latest designs
  app/components/app_imports_navigation_component.rb
  app/components/app_imports_table_component.html.erb
  app/components/app_imports_table_component.rb
  app/components/app_programme_navigation_component.rb
  app/controllers/class_imports_controller.rb
  app/controllers/dashboard_controller.rb
  app/controllers/draft_class_imports_controller.rb
  app/controllers/imports/issues_controller.rb
  app/controllers/imports/notices_controller.rb
  app/controllers/imports_controller.rb
  app/models/draft_class_import.rb
  app/views/class_imports/new.html.erb
  app/views/cohorts/index.html.erb
  app/views/dashboard/index.html.erb
  app/views/draft_class_imports/session.html.erb
  app/views/imports/index.html.erb
  app/views/imports/issues/index.html.erb
  app/views/imports/issues/show.html.erb
  app/views/imports/new.html.erb
  app/views/imports/notices/index.html.erb
  app/views/imports/show.html.erb
  app/views/layouts/_header.html.erb
  app/views/programmes/patients.html.erb
  app/views/programmes/sessions.html.erb
  app/views/programmes/show.html.erb
  app/views/sessions/show.html.erb
  app/views/vaccination_records/index.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/components/app_imports_table_component_spec.rb
  spec/features/import_child_records_spec.rb
  spec/features/import_child_records_with_duplicates_spec.rb
  spec/features/import_class_lists_move_spec.rb
  spec/features/import_class_lists_spec.rb
  spec/features/import_class_lists_with_duplicates_spec.rb
  spec/features/import_vaccination_records_with_duplicates_spec.rb
  spec/features/manage_children_spec.rb
Labels: ✨ feature

#2784 Remove `Cohort` model
  app/models/cohort.rb
  app/models/concerns/year_group_concern.rb
  app/models/patient.rb
  app/models/patient_import_row.rb
  config/locales/en.yml
  db/migrate/20241219162929_drop_cohorts.rb
  db/schema.rb
  spec/factories/cohorts.rb
  spec/factories/patients.rb
  spec/models/class_import_spec.rb
  spec/models/cohort_import_spec.rb
  spec/models/cohort_spec.rb
  spec/models/patient_spec.rb
Labels: 📐 data_consistency, 🛠️ refactor

#2957 Add year group selection when importing class lists
  app/controllers/class_imports_controller.rb
  app/controllers/draft_class_imports_controller.rb
  app/models/class_import.rb
  app/models/class_import_row.rb
  app/models/draft_class_import.rb
  app/views/draft_class_imports/year_groups.html.erb
  app/views/imports/show.html.erb
  config/locales/en.yml
  db/migrate/20250211092238_add_year_groups_to_class_imports.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/class_imports.rb
  spec/features/import_class_lists_move_spec.rb
  spec/features/import_class_lists_spec.rb
  spec/features/import_class_lists_with_duplicates_spec.rb
  spec/models/class_import_row_spec.rb
  spec/models/class_import_spec.rb
Labels: ✨ feature

#2900 Replace recipient_deterministic with recipient
  app/jobs/email_delivery_job.rb
  app/jobs/sms_delivery_job.rb
  app/models/notify_log_entry.rb
  db/migrate/20250128111046_remove_recipient_from_notify_log_entries.rb
  db/migrate/20250128111223_add_recipient_to_notify_log_entries.rb
  db/schema.rb
  lib/tasks/notify_log_entries.rake
  spec/factories/notify_log_entries.rb
  spec/jobs/email_delivery_job_spec.rb
  spec/jobs/sms_delivery_job_spec.rb
  spec/models/notify_log_entry_spec.rb
Labels: 📐 data_consistency, 🛠️ refactor

#2974 Mavis-2020 Add build workflow
  .github/workflows/build.yml
  terraform/scripts/shell-access.sh
Labels: github_actions

#2978 Pass programme to components
  app/components/app_activity_log_component.rb
  app/components/app_consent_component.html.erb
  app/components/app_consent_component.rb
  app/components/app_consent_status_component.rb
  app/components/app_outcome_banner_component.rb
  app/components/app_patient_page_component.html.erb
  app/components/app_patient_page_component.rb
  app/components/app_simple_status_banner_component.rb
  app/components/app_triage_form_component.rb
  app/components/app_vaccinate_form_component.rb
  app/controllers/consents_controller.rb
  app/controllers/patient_sessions_controller.rb
  app/controllers/triages_controller.rb
  app/controllers/vaccinations_controller.rb
  app/views/patient_sessions/log.html.erb
  app/views/patient_sessions/show.html.erb
  app/views/triages/new.html.erb
  spec/components/app_consent_component_spec.rb
  spec/components/app_consent_status_component_spec.rb
  spec/components/app_outcome_banner_component_spec.rb
  spec/components/app_patient_page_component_spec.rb
  spec/components/app_simple_status_banner_component_spec.rb
  spec/components/app_triage_form_component_spec.rb
  spec/components/app_vaccinate_form_component_spec.rb
Labels: 🛠️ refactor

#2981 Filter programme stats by programme
  app/controllers/programmes_controller.rb
  app/views/programmes/index.html.erb
Labels: 🐞 bug

#2982 Show paper consent form links for each programme
  app/components/app_session_summary_component.rb
  app/controllers/programmes_controller.rb
  app/controllers/sessions_controller.rb
  app/policies/programme_policy.rb
  app/policies/session_policy.rb
  app/views/sessions/show.html.erb
  config/brakeman.ignore
  config/routes.rb
  db/seeds.rb
  public/consent_forms/hpv.pdf
  public/consent_forms/menacwy.pdf
  public/consent_forms/td_ipv.pdf
  spec/features/paper_consent_download_spec.rb
Labels: ✨ feature

#2983 Use programme to generate patient session status
  app/components/app_consent_component.html.erb
  app/components/app_consent_component.rb
  app/components/app_consent_status_component.rb
  app/components/app_outcome_banner_component.rb
  app/components/app_patient_page_component.html.erb
  app/components/app_programme_session_table_component.rb
  app/components/app_session_patient_table_component.rb
  app/components/app_simple_status_banner_component.rb
  app/components/app_vaccinate_form_component.rb
  app/controllers/concerns/patient_tabs_concern.rb
  app/controllers/concerns/triage_mailer_concern.rb
  app/controllers/consents_controller.rb
  app/controllers/register_attendances_controller.rb
  app/controllers/session_attendances_controller.rb
  app/controllers/sessions_controller.rb
  app/controllers/triages_controller.rb
  app/controllers/vaccinations_controller.rb
  app/jobs/clinic_session_invitations_job.rb
  app/jobs/school_session_reminders_job.rb
  app/lib/reports/export_formatters.rb
  app/lib/reports/offline_session_exporter.rb
  app/lib/reports/programme_vaccinations_exporter.rb
  app/models/concerns/patient_session_status_concern.rb
  app/models/immunisation_import.rb
  app/models/patient.rb
  app/models/patient_session_stats.rb
  app/models/school_move.rb
  app/models/session.rb
  app/views/consent_forms/show.html.erb
  app/views/consents/index.html.erb
  app/views/programmes/sessions.html.erb
  app/views/register_attendances/index.html.erb
  app/views/triages/index.html.erb
  app/views/vaccinations/index.html.erb
  spec/components/app_programme_session_table_component_spec.rb
  spec/components/app_session_patient_table_component_spec.rb
  spec/controllers/concerns/patient_sorting_concern_spec.rb
  spec/controllers/concerns/patient_tabs_concern_spec.rb
  spec/models/concerns/patient_session_status_concern_spec.rb
  spec/models/immunisation_import_spec.rb
  spec/models/patient_session_spec.rb
  spec/models/patient_session_stats_spec.rb
Labels: 🛠️ refactor

#2984 Add programme selection to patient session pages
  app/components/app_activity_log_component.rb
  app/components/app_consent_component.html.erb
  app/components/app_patient_page_component.html.erb
  app/components/app_session_patient_table_component.rb
  app/components/app_simple_status_banner_component.html.erb
  app/components/app_simple_status_banner_component.rb
  app/components/app_vaccinate_form_component.rb
  app/controllers/consent_forms_controller.rb
  app/controllers/consents_controller.rb
  app/controllers/draft_consents_controller.rb
  app/controllers/draft_vaccination_records_controller.rb
  app/controllers/gillick_assessments_controller.rb
  app/controllers/patient_sessions_controller.rb
  app/controllers/session_attendances_controller.rb
  app/controllers/triages_controller.rb
  app/controllers/vaccinations_controller.rb
  app/models/consent_form.rb
  app/views/consents/index.html.erb
  app/views/consents/invalidate.html.erb
  app/views/consents/show.html.erb
  app/views/consents/withdraw.html.erb
  app/views/gillick_assessments/edit.html.erb
  app/views/patient_sessions/_secondary_navigation.html.erb
  app/views/patient_sessions/log.html.erb
  app/views/patient_sessions/show.html.erb
  app/views/session_attendances/edit.html.erb
  app/views/triages/new.html.erb
  config/routes.rb
  spec/components/app_patient_page_component_spec.rb
  spec/components/app_session_patient_table_component_spec.rb
  spec/components/app_simple_status_banner_component_spec.rb
  spec/features/self_consent_spec.rb
Labels: ✨ feature

#2994 Update consent links to show per programme
  app/components/app_session_summary_component.rb
  spec/components/app_session_summary_component_spec.rb
Labels: ✨ feature

#2996 Add ability to assign programmes to sessions
  app/components/app_programme_tags_component.rb
  app/components/app_session_summary_component.rb
  app/components/app_session_table_component.html.erb
  app/controllers/sessions/edit_controller.rb
  app/models/session.rb
  app/views/sessions/edit.html.erb
  app/views/sessions/edit/programmes.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/features/manage_school_sessions_spec.rb
  spec/models/session_spec.rb
Labels: ✨ feature

#3000 Invalidate self-consents on a schedule
  app/jobs/invalidate_self_consents_job.rb
  app/models/session.rb
  config/environments/production.rb
  spec/jobs/invalidate_self_consents_job_spec.rb
Labels: 🛠️ refactor

#3002 Add minimum doubles session page design
  app/components/app_programme_selection_form_component.html.erb
  app/components/app_programme_selection_form_component.rb
  app/components/app_session_patient_table_component.rb
  app/controllers/concerns/patient_sorting_concern.rb
  app/controllers/consents_controller.rb
  app/controllers/register_attendances_controller.rb
  app/controllers/session_attendances_controller.rb
  app/controllers/sessions_controller.rb
  app/controllers/triages_controller.rb
  app/controllers/vaccinations_controller.rb
  app/views/consent_forms/show.html.erb
  app/views/consents/index.html.erb
  app/views/patient_sessions/show.html.erb
  app/views/register_attendances/index.html.erb
  app/views/sessions/show.html.erb
  app/views/triages/index.html.erb
  app/views/vaccinations/index.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/controllers/concerns/patient_sorting_concern_spec.rb
Labels: ✨ feature

#3005 Increase Td/IPV maximum dose sequence
  app/models/vaccine.rb
  spec/models/vaccine_spec.rb
Labels: 📐 data_consistency

#3006 Validate date of vaccination is after date of birth
  app/models/immunisation_import_row.rb
  config/locales/en.yml
  spec/models/immunisation_import_row_spec.rb
Labels: 🗄️ operations

#3008 Invite patients to clinics
  app/components/app_programme_session_table_component.html.erb
  app/controllers/sessions/invite_to_clinic_controller.rb
  app/controllers/sessions_controller.rb
  app/jobs/clinic_session_invitations_job.rb
  app/jobs/concerns/send_clinic_invitations_concern.rb
  app/jobs/send_clinic_initial_invitations_job.rb
  app/jobs/send_clinic_subsequent_invitations_job.rb
  app/lib/govuk_notify_personalisation.rb
  app/models/session.rb
  app/views/sessions/invite_to_clinic/edit.html.erb
  app/views/sessions/show.html.erb
  config/routes.rb
  db/seeds.rb
  spec/features/manage_clinic_sessions_spec.rb
  spec/features/manage_school_sessions_spec.rb
  spec/jobs/send_clinic_initial_invitations_job_spec.rb
Labels: ✨ feature

#3011 Add programme to activity log entries
  app/components/app_activity_log_component.rb
  app/components/app_log_event_component.rb
  spec/components/app_activity_log_component_spec.rb
Labels: ✨ feature

#3016 Add MenACWY and Td/IPV health questions
  lib/tasks/vaccines.rake
  spec/factories/health_questions.rb
  spec/factories/vaccines.rb
Labels: ✨ feature

#3018 Order programmes by name
  app/models/organisation.rb
  app/models/programme.rb
  app/models/session.rb
  app/models/session_programme.rb
  db/migrate/20250221080758_create_session_programmes.rb
  db/schema.rb
  spec/models/session_spec.rb
Labels: ✨ feature

#3021 Simplify seeds generation
  app/models/location.rb
  config/settings.yml
  config/settings/development.yml
  config/settings/test.yml
  db/seeds.rb
  spec/models/location_spec.rb
Labels: 🛠️ refactor

#3019 Send session notifications for all programmes
  app/models/session_notification.rb
  spec/models/session_notification_spec.rb
Labels: 🛠️ refactor

#3023 Associate consent forms with multiple programmes
  app/controllers/dev_controller.rb
  app/controllers/parent_interface/consent_forms/base_controller.rb
  app/controllers/parent_interface/consent_forms_controller.rb
  app/lib/govuk_notify_personalisation.rb
  app/models/consent.rb
  app/models/consent_form.rb
  app/models/consent_form_programme.rb
  app/models/vaccine.rb
  app/views/consent_forms/show.html.erb
  app/views/parent_interface/consent_forms/_confirmation_agreed.html.erb
  app/views/parent_interface/consent_forms/_confirmation_injection.html.erb
  app/views/parent_interface/consent_forms/_confirmation_needs_triage.html.erb
  app/views/parent_interface/consent_forms/_confirmation_refused.html.erb
  app/views/parent_interface/consent_forms/confirm.html.erb
  app/views/parent_interface/consent_forms/edit/consent.html.erb
  app/views/parent_interface/consent_forms/edit/name.html.erb
  app/views/parent_interface/consent_forms/start.html.erb
  db/migrate/20250221105126_create_consent_form_programmes.rb
  db/schema.rb
  db/seeds.rb
  spec/components/app_activity_log_component_spec.rb
  spec/components/app_session_patient_table_component_spec.rb
  spec/components/previews/app_session_patient_table_component_preview.rb
  spec/controllers/concerns/consent_form_mailer_concern_spec.rb
  spec/factories/consent_forms.rb
  spec/features/dev_reset_organisation_spec.rb
  spec/features/parental_consent_manual_matching_spec.rb
  spec/jobs/email_delivery_job_spec.rb
  spec/jobs/sms_delivery_job_spec.rb
  spec/models/consent_form_spec.rb
  spec/models/consent_spec.rb
  spec/models/patient_session_stats_spec.rb
Labels: ✨ feature

#3025 Show consent form link for doubles
  app/components/app_session_summary_component.rb
  app/controllers/parent_interface/consent_forms/base_controller.rb
  app/controllers/parent_interface/consent_forms_controller.rb
  app/jobs/email_delivery_job.rb
  app/jobs/sms_delivery_job.rb
  app/lib/govuk_notify_personalisation.rb
  app/lib/programme_grouper.rb
  app/models/consent_notification.rb
  app/views/parent_interface/consent_forms/edit/name.html.erb
  app/views/parent_interface/consent_forms/start.html.erb
  config/routes.rb
  spec/features/parental_consent_doubles_spec.rb
  spec/jobs/email_delivery_job_spec.rb
  spec/jobs/sms_delivery_job_spec.rb
  spec/lib/govuk_notify_personalisation_spec.rb
  spec/lib/programme_grouper_spec.rb
  spec/models/consent_notification_spec.rb
Labels: ✨ feature

#3029 Customise consent email templates by group
  app/components/app_consent_component.rb
  app/components/app_session_summary_component.rb
  app/controllers/consents_controller.rb
  app/controllers/programmes_controller.rb
  app/jobs/school_consent_reminders_job.rb
  app/jobs/school_consent_requests_job.rb
  app/lib/programme_grouper.rb
  app/models/consent_notification.rb
  app/models/consent_notification_programme.rb
  app/models/programme.rb
  config/initializers/govuk_notify.rb
  db/migrate/20250221155425_create_consent_notification_programmes.rb
  db/schema.rb
  db/seeds.rb
  spec/components/app_activity_log_component_spec.rb
  spec/components/app_consent_component_spec.rb
  spec/components/app_consent_status_component_spec.rb
  spec/components/app_outcome_banner_component_spec.rb
  spec/components/app_patient_page_component_spec.rb
  spec/components/app_session_patient_table_component_spec.rb
  spec/components/app_simple_status_banner_component_spec.rb
  spec/components/app_triage_form_component_spec.rb
  spec/components/app_triage_notes_component_spec.rb
  spec/components/app_vaccinate_form_component_spec.rb
  spec/controllers/concerns/patient_sorting_concern_spec.rb
  spec/controllers/concerns/patient_tabs_concern_spec.rb
  spec/factories/consent_notifications.rb
  spec/factories/organisations.rb
  spec/factories/patient_sessions.rb
  spec/factories/patients.rb
  spec/features/delete_vaccination_record_spec.rb
  spec/features/download_vaccination_reports_spec.rb
  spec/features/edit_vaccination_record_spec.rb
  spec/features/manage_attendance_spec.rb
  spec/features/manage_batches_spec.rb
  spec/features/scheduled_consent_requests_spec.rb
  spec/features/triage_delay_vaccination_spec.rb
  spec/features/triage_spec.rb
  spec/features/triage_then_parental_consent_refused_spec.rb
  spec/features/verbal_consent_given_when_previously_refused_spec.rb
  spec/jobs/patient_nhs_number_lookup_job_spec.rb
  spec/jobs/school_consent_reminders_job_spec.rb
  spec/jobs/school_consent_requests_job_spec.rb
  spec/jobs/school_session_reminders_job_spec.rb
  spec/lib/patient_merger_spec.rb
  spec/lib/programme_grouper_spec.rb
  spec/lib/reports/careplus_exporter_spec.rb
  spec/lib/reports/programme_vaccinations_exporter_spec.rb
  spec/models/consent_notification_spec.rb
  spec/models/draft_consent_spec.rb
  spec/models/patient_session_spec.rb
  spec/models/patient_session_stats_spec.rb
  spec/policies/patient_session_policy_spec.rb
Labels: ✨ feature

#3026 Associate consent notifications with multiple programmes
  app/components/app_consent_component.rb
  app/controllers/consents_controller.rb
  app/controllers/programmes_controller.rb
  app/jobs/school_consent_reminders_job.rb
  app/jobs/school_consent_requests_job.rb
  app/models/consent_notification.rb
  app/models/consent_notification_programme.rb
  app/models/programme.rb
  db/migrate/20250221155425_create_consent_notification_programmes.rb
  db/schema.rb
  spec/factories/consent_notifications.rb
  spec/factories/patients.rb
  spec/jobs/school_consent_reminders_job_spec.rb
  spec/jobs/school_consent_requests_job_spec.rb
  spec/lib/patient_merger_spec.rb
  spec/models/consent_notification_spec.rb
Labels: 📐 data_consistency

#3031 Paginate session patients
  app/controllers/consents_controller.rb
  app/controllers/triages_controller.rb
  app/controllers/vaccinations_controller.rb
  app/views/consents/index.html.erb
  app/views/triages/index.html.erb
  app/views/vaccinations/index.html.erb
Labels: ✨ feature

#3028 Add historical MenACWY vaccines
  config/vaccines.yml
  spec/factories/programmes.rb
Labels: 📐 data_consistency

#3032 Add vaccination criteria for doubles
  app/lib/programme_grouper.rb
  app/lib/vaccinated_criteria.rb
  app/models/concerns/age_concern.rb
  app/models/concerns/patient_session_status_concern.rb
  app/models/programme.rb
  spec/lib/vaccinated_criteria_spec.rb
Labels: ✨ feature

#3033 Fetch programmes from patient session
  app/components/app_consent_component.rb
  app/components/app_session_patient_table_component.rb
  app/controllers/consent_forms_controller.rb
  app/controllers/consents_controller.rb
  app/controllers/dev_controller.rb
  app/controllers/gillick_assessments_controller.rb
  app/controllers/patient_sessions_controller.rb
  app/controllers/patients_controller.rb
  app/controllers/session_attendances_controller.rb
  app/controllers/triages_controller.rb
  app/controllers/vaccinations_controller.rb
  app/jobs/school_session_reminders_job.rb
  app/lib/reports/careplus_exporter.rb
  app/lib/reports/offline_session_exporter.rb
  app/models/patient.rb
  app/models/patient_session.rb
  app/models/patient_session_stats.rb
  app/views/patient_sessions/_secondary_navigation.html.erb
  app/views/session_attendances/edit.html.erb
  spec/lib/reports/careplus_exporter_spec.rb
  spec/lib/reports/offline_session_exporter_spec.rb
Labels: 🛠️ refactor

#3034 Ensure consent requests are only sent to eligible patients
  app/jobs/concerns/send_clinic_invitations_concern.rb
  app/jobs/school_consent_reminders_job.rb
  app/jobs/school_consent_requests_job.rb
  app/jobs/send_clinic_initial_invitations_job.rb
  app/models/session_notification.rb
  spec/jobs/clinic_session_invitations_job_spec.rb
  spec/jobs/school_consent_requests_job_spec.rb
  spec/jobs/send_clinic_initial_invitations_job_spec.rb
  spec/jobs/send_clinic_subsequent_invitations_job_spec.rb
  spec/models/session_notification_spec.rb
Labels: 🐞 bug

#3036 Allow triage without consent
  app/models/concerns/patient_session_status_concern.rb
  app/models/consent_form.rb
  spec/features/triage_remove_from_cohort_spec.rb
  spec/fixtures/files/menacwy/class_list.csv
Labels: ✨ feature

#3037 Update PDF paper consent forms for doubles
  public/consent_forms/menacwy.pdf
  public/consent_forms/td_ipv.pdf
Labels: ✨ feature

#3038 Pluralise GOV.UK Notify vaccination personalisation
  app/lib/govuk_notify_personalisation.rb
  spec/lib/govuk_notify_personalisation_spec.rb
Labels: ✨ feature

#3040 Rework how triage works for incomplete vaccination history
  app/components/app_session_patient_table_component.rb
  app/components/app_simple_status_banner_component.html.erb
  app/components/app_simple_status_banner_component.rb
  app/controllers/concerns/patient_tabs_concern.rb
  app/helpers/triage_helper.rb
  app/models/concerns/patient_session_status_concern.rb
  app/models/patient_session_stats.rb
  config/locales/patient_session_statuses.en.yml
  db/seeds.rb
  spec/factories/patient_sessions.rb
  spec/factories/patients.rb
  spec/features/triage_partially_vaccinated_spec.rb
  spec/models/concerns/patient_session_status_concern_spec.rb
Labels: ✨ feature

#3041 Update health questions for Td/IPV and MenACWY
  lib/tasks/vaccines.rake
  spec/factories/vaccines.rb
Labels: ✨ feature

#3042 Show programme separate to vaccine
  app/components/app_vaccination_record_summary_component.rb
  spec/components/app_vaccination_record_summary_component_spec.rb
Labels: 🗄️ operations

#3045 Add PROGRAMME column when importing vaccination records
  app/components/app_import_format_details_component.rb
  app/lib/reports/offline_session_exporter.rb
  app/models/immunisation_import_row.rb
  app/models/programme.rb
  config/locales/en.yml
  spec/fixtures/files/td_ipv/vaccination_records.csv
  spec/fixtures/immunisation_import/empty.csv
  spec/fixtures/immunisation_import/invalid_rows.csv
  spec/fixtures/immunisation_import/valid_flu.csv
  spec/fixtures/immunisation_import/valid_hpv.csv
  spec/fixtures/immunisation_import/valid_hpv_with_changes.csv
  spec/lib/reports/offline_session_exporter_spec.rb
  spec/models/immunisation_import_row_spec.rb
Labels: ✨ feature

#3047 Allow dose_sequence to be optional
  app/components/app_vaccination_record_summary_component.rb
  app/controllers/draft_vaccination_records_controller.rb
  app/models/draft_vaccination_record.rb
  app/models/immunisation_import_row.rb
  app/models/vaccination_record.rb
  db/migrate/20250224200603_make_vaccination_record_dose_sequence_null.rb
  db/schema.rb
  spec/factories/vaccination_records.rb
  spec/models/vaccination_record_spec.rb
Labels: 📐 data_consistency

#3046 Add SESSION_ID column when importing vaccination records
  app/lib/reports/offline_session_exporter.rb
  app/models/immunisation_import_row.rb
  spec/features/import_vaccination_records_with_duplicates_spec.rb
  spec/lib/reports/offline_session_exporter_spec.rb
  spec/models/immunisation_import_row_spec.rb
  spec/models/immunisation_import_spec.rb
Labels: ✨ feature

#3048 Add custom dose sequence values per programme
  app/components/app_import_format_details_component.rb
  app/models/immunisation_import_row.rb
  app/models/programme.rb
  spec/models/immunisation_import_row_spec.rb
  spec/models/programme_spec.rb
Labels: ✨ feature

#3049 Make CARE_SETTING optional for all programmes
  app/components/app_import_format_details_component.rb
  app/models/immunisation_import_row.rb
Labels: 📐 data_consistency

#3024 Allow parents to consent to just one vaccine
  app/controllers/parent_interface/consent_forms/edit_controller.rb
  app/models/consent_form.rb
  app/views/parent_interface/consent_forms/edit/consent.html.erb
  db/migrate/20250224195511_add_chosen_vaccine_to_consent_form.rb
  db/schema.rb
  spec/factories/consent_forms.rb
  spec/features/parental_consent_doubles_spec.rb
  spec/models/consent_form_spec.rb
Labels: ✨ feature

#3050 Allow vaccine and batch to be optional
  app/components/app_import_format_details_component.rb
  app/models/immunisation_import.rb
  app/models/immunisation_import_row.rb
  spec/fixtures/immunisation_import/valid_flu.csv
  spec/models/immunisation_import_row_spec.rb
Labels: ✨ feature

#3053 Add Td/IPV and MenACWY email templates
  config/initializers/govuk_notify.rb
Labels: ✨ feature

#3051 Allow delivery site to be optional
  app/models/immunisation_import_row.rb
  app/models/vaccination_record.rb
  spec/features/import_vaccination_records_spec.rb
  spec/fixtures/immunisation_import/valid_hpv.csv
  spec/models/immunisation_import_row_spec.rb
Labels: ✨ feature

#3060 Update check answers page for doubles
  app/views/parent_interface/consent_forms/confirm.html.erb
  config/locales/en.yml
Labels: ✨ feature

#3059 Use location_name when there's no session
  app/components/app_vaccination_record_summary_component.rb
Labels: 🐞 bug

#3063 Allow SCHOOL_URN to be optional
  app/components/app_import_format_details_component.rb
  app/models/immunisation_import_row.rb
  spec/fixtures/immunisation_import/valid_hpv.csv
Labels: 📐 data_consistency

#3062 Allow performed_ods_code to be optional
  app/components/app_import_format_details_component.rb
  app/models/immunisation_import_row.rb
  app/models/vaccination_record.rb
  db/migrate/20250224221219_make_vaccination_record_performed_ods_code_null.rb
  db/schema.rb
  spec/factories/vaccination_records.rb
  spec/fixtures/immunisation_import/valid_hpv.csv
  spec/models/immunisation_import_row_spec.rb
  spec/models/vaccination_record_spec.rb
Labels: 📐 data_consistency

#3065 Add "Record as already vaccinated" functionality
  app/components/app_vaccination_record_summary_component.rb
  app/controllers/patient_sessions_controller.rb
  app/jobs/school_consent_reminders_job.rb
  app/jobs/school_consent_requests_job.rb
  app/models/concerns/patient_session_status_concern.rb
  app/models/draft_vaccination_record.rb
  app/models/patient_session.rb
  app/views/draft_vaccination_records/confirm.html.erb
  app/views/patient_sessions/show.html.erb
  config/routes.rb
  spec/features/td_ipv_already_had_spec.rb
Labels: ✨ feature

#3064 Ask for reason when parent consents to one vaccine
  app/models/consent_form.rb
  spec/features/parental_consent_doubles_spec.rb
Labels: ✨ feature

#3068 Get the programmes from the consent form
  app/views/parent_interface/consent_forms/edit/consent.html.erb
Labels: 🐞 bug

#3067 Add missing doubles translation strings
  config/locales/en.yml
Labels: 🐞 bug

#3066 Handle doubles health questions
  app/models/consent_form.rb
  lib/tasks/vaccines.rake
  spec/factories/health_questions.rb
  spec/factories/vaccines.rb
  spec/features/parental_consent_doubles_spec.rb
  spec/features/parental_consent_flu_spec.rb
  spec/models/consent_form_spec.rb
Labels: ✨ feature

#3069 Validate vaccine for programme
  app/models/immunisation_import_row.rb
Labels: 📐 data_consistency

#3070 Create consent responses per programme
  app/models/consent.rb
  app/models/consent_form.rb
  spec/models/consent_spec.rb
Labels: ✨ feature

#3073 Update content when sending reminders
  app/views/sessions/invite_to_clinic/edit.html.erb
Labels: 🗄️ operations

#3074 Show patients if we have a vaccination record
  app/controllers/cohorts_controller.rb
  app/policies/patient_policy.rb
  app/policies/vaccination_record_policy.rb
  spec/policies/patient_policy_spec.rb
Labels: ✨ feature

#3079 Avoid duplicate TIME_OF_VACCINATION errors
  app/models/immunisation_import_row.rb
Labels: 🐞 bug

#3078 Show notify log entry programmes in activity log
  app/components/app_activity_log_component.rb
  app/components/app_log_event_component.rb
  app/jobs/email_delivery_job.rb
  app/jobs/sms_delivery_job.rb
  app/lib/govuk_notify_personalisation.rb
  app/models/notify_log_entry.rb
  db/migrate/20250225161342_add_programme_i_ds_to_notify_log_entries.rb
  db/schema.rb
  spec/components/app_activity_log_component_spec.rb
  spec/factories/notify_log_entries.rb
  spec/features/delete_vaccination_record_spec.rb
  spec/features/parental_consent_send_request_spec.rb
  spec/jobs/email_delivery_job_spec.rb
  spec/jobs/sms_delivery_job_spec.rb
  spec/lib/govuk_notify_personalisation_spec.rb
  spec/models/notify_log_entry_spec.rb
Labels: ✨ feature

#3075 Send consent confirmation emails per programme
  app/controllers/concerns/consent_form_mailer_concern.rb
  app/models/consent.rb
  app/models/consent_form.rb
  spec/controllers/concerns/consent_form_mailer_concern_spec.rb
Labels: ✨ feature

#3076 Update content when refusing consent
  app/views/parent_interface/consent_forms/edit/reason.html.erb
  spec/features/parental_consent_doubles_spec.rb
  spec/features/parental_consent_refused_spec.rb
  spec/features/triage_then_parental_consent_refused_spec.rb
Labels: ✨ feature

#3081 Add MenACWY and Td/IPV to Coventry
  config/onboarding/coventry-production.yaml
Labels: 🗄️ operations

#3083 Add feature flag for vaccinating doubles
  app/models/concerns/patient_session_status_concern.rb
  spec/factories/programmes.rb
  spec/features/menacwy_vaccination_administered_spec.rb
  spec/features/td_ipv_vaccination_administered_spec.rb
Labels: 🗄️ operations

#3080 Update parental consent confirmation pages
  app/assets/stylesheets/application.scss
  app/components/app_consent_confirmation_component.rb
  app/views/parent_interface/consent_forms/_confirmation_agreed.html.erb
  app/views/parent_interface/consent_forms/_confirmation_injection.html.erb
  app/views/parent_interface/consent_forms/_confirmation_needs_triage.html.erb
  app/views/parent_interface/consent_forms/_confirmation_refused.html.erb
  app/views/parent_interface/consent_forms/record.html.erb
  config/initializers/govuk_components.rb
  config/locales/en.yml
  spec/components/app_consent_confirmation_component_spec.rb
  spec/features/parental_consent_change_answers_spec.rb
  spec/features/parental_consent_clinic_spec.rb
  spec/features/parental_consent_create_patient_spec.rb
  spec/features/parental_consent_inexact_auto_match_spec.rb
  spec/features/parental_consent_refused_spec.rb
  spec/features/parental_consent_school_session_completed_spec.rb
  spec/features/parental_consent_spec.rb
  spec/features/triage_then_parental_consent_refused_spec.rb
Labels: ✨ feature

#3089 Improve offline recording detection
  app/models/immunisation_import_row.rb
Labels: 📐 data_consistency

#3090 Remove data migration
  db/migrate/20250211092238_add_year_groups_to_class_imports.rb
  lib/tasks/class_imports.rake
Labels: 🛠️ refactor

#3092 Mention both vaccines when doubles refused
  app/components/app_consent_confirmation_component.rb
  spec/components/app_consent_confirmation_component_spec.rb
Labels: 🐞 bug

#3091 Only show future dates on consent confimrmation
  app/components/app_consent_confirmation_component.rb
  spec/components/app_consent_confirmation_component_spec.rb
Labels: 🐞 bug

#3088 Add pagination to register attendances page
  app/controllers/register_attendances_controller.rb
  app/views/register_attendances/index.html.erb
Labels: ✨ feature

#3094 Fix vaccinated criteria for MenACWY
  app/lib/vaccinated_criteria.rb
  spec/lib/vaccinated_criteria_spec.rb
Labels: 🐞 bug

#3098 Ensure validation against SESSION_ID works
  app/models/immunisation_import_row.rb
  config/locales/en.yml
  spec/models/immunisation_import_row_spec.rb
Labels: 🐞 bug

#3107 Reset chosen_vaccine if changing response
  app/models/consent_form.rb
  spec/models/consent_form_spec.rb
Labels: 🐞 bug

#3106 Update content for date of vaccination inclusion error
  config/locales/en.yml
  spec/models/immunisation_import_row_spec.rb
Labels: 🧑‍🎨 design tweak

#3104 Include historical records in offline reporting
  app/lib/reports/offline_session_exporter.rb
  spec/lib/reports/offline_session_exporter_spec.rb
Labels: 🐞 bug

#3103 Make sure school name is stored on vaccination record
  app/models/immunisation_import_row.rb
  spec/features/import_vaccination_records_with_duplicates_spec.rb
  spec/models/immunisation_import_row_spec.rb
Labels: 🐞 bug

#3102 Update design of secondary navigation component
  app/assets/stylesheets/_secondary-navigation.scss
  app/components/app_secondary_navigation_component.html.erb
  spec/components/app_secondary_navigation_component_spec.rb
Labels: 🧑‍🎨 design tweak

#3111 Fix spelling of programme
  config/locales/en.yml
  spec/forms/session_programmes_form_spec.rb
Labels: 🧑‍🎨 design tweak

#3113 Add patient_sessions:add_to_clinic
  lib/tasks/patient_sessions.rake
Labels: 🗄️ operations

#3112 Add organisations:add_programme
  docs/rake-tasks.md
  lib/tasks/organisations.rake
Labels: 🗄️ operations

#3115 Get location name from school if available
  app/models/immunisation_import_row.rb
  spec/features/import_vaccination_records_with_duplicates_spec.rb
  spec/models/immunisation_import_row_spec.rb
Labels: 🐞 bug
