Repository nhsuk/manage-vaccinations-in-schools, pull requests merged in 2025-08, with the labels that each got.

#4148 Hide navigation bar in parent consent journey
  app/controllers/parent_interface/consent_forms/base_controller.rb
Labels: design tweak

#4149 Use `patient_id` when staging vaccination record changes
  app/models/immunisation_import_row.rb
  spec/features/hpv_vaccination_offline_spec.rb
Labels: bug

#4136 Show import issues count on header item
  app/components/app_count_component.rb
  app/components/app_header_navigation_item_component.rb
  app/components/app_imports_navigation_component.rb
  app/helpers/imports_helper.rb
  app/policies/vaccination_record_policy.rb
  app/views/layouts/_header.html.erb
  spec/features/import_child_records_spec.rb
  spec/features/import_child_records_with_duplicates_spec.rb
  spec/features/import_vaccination_records_with_duplicates_spec.rb
  spec/features/manage_children_spec.rb
Labels: design tweak

#4144 Simplify logic for next immunisations API action
  app/lib/nhs/immunisations_api.rb
Labels: refactor

#4094 Record already had vaccinations from consent response
  app/jobs/patients_refused_consent_already_vaccinated_job.rb
  app/models/vaccination_record.rb
  config/cron_jobs.rb
  spec/jobs/patients_refused_consent_already_vaccinated_job_spec.rb
  spec/models/vaccination_record_spec.rb
Labels: operations

#4162 Fix "an team" typos
  app/lib/mavis_cli/clinics/add_to_team.rb
  app/lib/mavis_cli/schools/add_to_team.rb
  app/lib/mavis_cli/teams/add_programme.rb
  app/models/immunisation_import_row.rb
  docs/disaster-recovery.md
  docs/ops-tasks.md
  docs/rake-tasks.md
  lib/tasks/onboard.rake
  lib/tasks/subteams.rake
  lib/tasks/teams.rake
  spec/lib/reports/school_moves_exporter_spec.rb
  spec/models/location_spec.rb
Labels: bug

#4161 Put imms API sync status behind feature flag
  app/components/app_vaccination_record_summary_component.rb
Labels: design tweak

#4171 Continue to fix session cohort stats
  app/components/app_programme_session_table_component.rb
  app/components/app_session_actions_component.rb
  app/components/app_session_details_summary_component.rb
  spec/components/app_programme_session_table_component_spec.rb
  spec/components/app_session_actions_component_spec.rb
  spec/components/app_session_details_summary_component_spec.rb
Labels: bug

#4172 fix: use AcademicYear.current rather than Date.current
  app/components/app_activity_log_component.rb
  spec/components/app_activity_log_component_spec.rb
Labels: bug

#4179 Rename unprocessable_entity
  app/controllers/api/testing/onboard_controller.rb
  app/controllers/application_controller.rb
  app/controllers/batches_controller.rb
  app/controllers/class_imports_controller.rb
  app/controllers/cohort_imports_controller.rb
  app/controllers/consent_forms_controller.rb
  app/controllers/draft_vaccination_records_controller.rb
  app/controllers/errors_controller.rb
  app/controllers/immunisation_imports_controller.rb
  app/controllers/imports/issues_controller.rb
  app/controllers/offline_passwords_controller.rb
  app/controllers/parent_interface/consent_forms/edit_controller.rb
  app/controllers/parent_relationships_controller.rb
  app/controllers/patient_sessions/activities_controller.rb
  app/controllers/patient_sessions/consents_controller.rb
  app/controllers/patient_sessions/gillick_assessments_controller.rb
  app/controllers/patient_sessions/session_attendances_controller.rb
  app/controllers/patient_sessions/triages_controller.rb
  app/controllers/patient_sessions/vaccinations_controller.rb
  app/controllers/patients/edit_controller.rb
  app/controllers/school_moves_controller.rb
  app/controllers/session_dates_controller.rb
  app/controllers/sessions/edit_controller.rb
  app/controllers/sessions/record_controller.rb
  app/controllers/users/teams_controller.rb
  config/initializers/devise.rb
  spec/requests/api/testing/onboard_spec.rb
  spec/requests/patient_sessions/activity_spec.rb
Labels: refactor

#4120 Archive patients
  app/components/app_activity_log_component.rb
  app/components/app_child_summary_component.rb
  app/components/app_patient_card_component.rb
  app/components/app_patient_cohort_table_component.html.erb
  app/components/app_patient_cohort_table_component.rb
  app/components/app_patient_search_form_component.rb
  app/controllers/concerns/patient_search_form_concern.rb
  app/controllers/patients/archive_controller.rb
  app/controllers/patients/base_controller.rb
  app/controllers/patients/edit_controller.rb
  app/controllers/patients_controller.rb
  app/controllers/programmes/base_controller.rb
  app/forms/concerns/patient_merge_form_concern.rb
  app/forms/patient_archive_form.rb
  app/forms/patient_merge_form.rb
  app/forms/patient_search_form.rb
  app/lib/patient_merger.rb
  app/models/archive_reason.rb
  app/models/consent_notification.rb
  app/models/location.rb
  app/models/patient.rb
  app/models/patient_session.rb
  app/models/school_move.rb
  app/models/session_notification.rb
  app/models/team.rb
  app/policies/patient_policy.rb
  app/views/patient_sessions/activities/show.html.erb
  app/views/patients/archive/new.html.erb
  app/views/patients/edit/nhs_number_merge.html.erb
  app/views/patients/log.html.erb
  app/views/patients/show.html.erb
  app/views/programmes/index.html.erb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20250730052926_create_archive_reason.rb
  db/schema.rb
  lib/tasks/archive_deceased_patients.rake
  lib/tasks/archive_moved_out_of_cohort_patients.rake
  spec/components/app_activity_log_component_spec.rb
  spec/components/app_child_summary_component_spec.rb
  spec/components/app_patient_cohort_table_component_spec.rb
  spec/factories/archive_reasons.rb
  spec/features/archive_children_spec.rb
  spec/features/manage_children_spec.rb
  spec/features/patient_search_spec.rb
  spec/forms/patient_archive_form_spec.rb
  spec/forms/patient_merge_form_spec.rb
  spec/forms/patient_search_form_spec.rb
  spec/lib/patient_merger_spec.rb
  spec/models/archive_reason_spec.rb
  spec/models/patient_spec.rb
  spec/models/school_move_spec.rb
  spec/models/team_spec.rb
  spec/policies/patient_policy_spec.rb
Labels: feature

#4184 Fix incorrect reference to organisations
  lib/tasks/archive_moved_out_of_cohort_patients.rake
Labels: bug

#4185 Fix patient show page layout
  app/views/patients/show.html.erb
Labels: bug

#4182 Don't add deceased patients to sessions
  app/models/patient_import_row.rb
  spec/models/class_import_row_spec.rb
  spec/models/cohort_import_row_spec.rb
Labels: feature

#4165 Show `notify_parents_on_vaccination` on confirmation
  app/components/app_consent_summary_component.rb
  app/views/draft_consents/confirm.html.erb
  spec/components/app_consent_summary_component_spec.rb
  spec/features/self_consent_spec.rb
  spec/features/verbal_consent_given_spec.rb
  spec/features/verbal_consent_refused_personal_choice_spec.rb
Labels: design tweak

#4175 Hide school and year group for some patients
  app/components/app_child_summary_component.rb
  app/components/app_patient_card_component.rb
  app/controllers/draft_imports_controller.rb
  app/controllers/programmes/overview_controller.rb
  app/controllers/programmes/patients_controller.rb
  app/lib/mavis_cli/schools/add_programme_year_group.rb
  app/lib/mavis_cli/schools/remove_programme_year_group.rb
  app/lib/programme_year_groups.rb
  app/lib/status_updater.rb
  app/models/concerns/has_programme_year_groups.rb
  app/models/location.rb
  app/models/location_programme_year_group.rb
  app/models/patient.rb
  app/models/patient_session.rb
  app/models/session.rb
  app/models/team.rb
  app/models/user.rb
  app/policies/location/programme_year_group_policy.rb
  app/views/consent_forms/patient.html.erb
  app/views/patients/edit.html.erb
  app/views/patients/edit/nhs_number_merge.html.erb
  app/views/patients/show.html.erb
  app/views/programmes/patients/index.html.erb
  app/views/vaccination_records/show.html.erb
  spec/components/app_child_summary_component_spec.rb
  spec/components/app_patient_card_component_spec.rb
  spec/factories/location_programme_year_groups.rb
  spec/features/cli_schools_add_programme_year_groups_spec.rb
  spec/features/cli_schools_remove_programme_year_groups_spec.rb
  spec/features/cli_teams_add_programme_spec.rb
  spec/lib/programme_year_groups_spec.rb
  spec/models/location_programme_year_group_spec.rb
  spec/models/location_spec.rb
  spec/models/onboarding_spec.rb
  spec/models/patient_spec.rb
Labels: design tweak

#4193 Small changes to archive design
  app/controllers/patients/archive_controller.rb
  app/forms/patient_search_form.rb
  app/views/patients/_header.html.erb
  app/views/patients/log.html.erb
  app/views/patients/show.html.erb
  spec/features/archive_children_spec.rb
  spec/forms/patient_search_form_spec.rb
Labels: design tweak

#4195 Log requests to immunisations API
  app/jobs/sync_vaccination_record_to_nhs_job.rb
  app/lib/nhs/immunisations_api.rb
Labels: operations

#4194 Handle discarded vaccination records on merge
  app/lib/patient_merger.rb
  spec/lib/patient_merger_spec.rb
Labels: bug

#4196 Show year group according to pending academic year
  app/models/patient.rb
  spec/models/patient_spec.rb
Labels: bug

#4197 Ensure patients are unarchived
  app/models/patient_import.rb
  app/models/patient_import_row.rb
  spec/models/class_import_row_spec.rb
  spec/models/cohort_import_row_spec.rb
Labels: bug

#4202 Update cohort import filename
  app/lib/mavis_cli/generate/cohort_imports.rb
  lib/generate/cohort_imports.rb
  spec/features/cli_generate_cohort_imports_spec.rb
Labels: refactor

#4095 Add workgroup to teams
  app/controllers/api/testing/teams_controller.rb
  app/lib/mavis_cli/clinics/add_to_team.rb
  app/lib/mavis_cli/generate/consents.rb
  app/lib/mavis_cli/generate/vaccination_records.rb
  app/lib/mavis_cli/schools/add_to_team.rb
  app/lib/mavis_cli/teams/add_programme.rb
  app/lib/mavis_cli/teams/create_sessions.rb
  app/models/onboarding.rb
  app/models/team.rb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20250728184911_add_workgroup_to_teams.rb
  db/schema.rb
  db/seeds.rb
  lib/generate/cohort_imports.rb
  lib/tasks/subteams.rake
  lib/tasks/teams.rake
  lib/tasks/users.rake
  spec/controllers/api/testing/teams_controller_spec.rb
  spec/factories/teams.rb
  spec/features/cli_clinics_add_to_team_spec.rb
  spec/features/cli_generate_consents_spec.rb
  spec/features/cli_generate_vaccination_records_spec.rb
  spec/features/cli_schools_add_to_team_spec.rb
  spec/features/cli_teams_add_programme_spec.rb
  spec/features/cli_teams_create_sessions_spec.rb
  spec/fixtures/files/onboarding/valid.yaml
  spec/lib/generate/cohort_imports_spec.rb
  spec/models/onboarding_spec.rb
  spec/models/team_spec.rb
  spec/requests/api/testing/onboard_spec.rb
Labels: operations

#4178 Show expired flu consents in activity log
  app/components/app_activity_log_component.rb
  spec/components/app_activity_log_component_spec.rb
Labels: design tweak

#4186 Don't add school patients to community clinic
  app/controllers/patients_controller.rb
  app/controllers/sessions/invite_to_clinic_controller.rb
  app/jobs/enqueue_clinic_session_invitations_job.rb
  app/jobs/send_clinic_initial_invitations_job.rb
  app/jobs/send_clinic_subsequent_invitations_job.rb
  app/lib/clinic_patient_sessions_factory.rb
  app/lib/location_sessions_factory.rb
  app/models/consent_form.rb
  app/models/patient.rb
  app/models/school_move.rb
  app/models/team.rb
  app/views/patients/show.html.erb
  config/routes.rb
  spec/controllers/api/testing/teams_controller_spec.rb
  spec/features/access_log_spec.rb
  spec/features/archive_children_spec.rb
  spec/features/delete_vaccination_record_spec.rb
  spec/features/edit_parent_spec.rb
  spec/features/edit_vaccination_record_spec.rb
  spec/features/manage_children_spec.rb
  spec/features/manage_school_sessions_spec.rb
  spec/features/parent_relationships_spec.rb
  spec/features/parental_consent_manual_matching_spec.rb
  spec/jobs/enqueue_clinic_session_invitations_job_spec.rb
  spec/jobs/send_clinic_initial_invitations_job_spec.rb
  spec/lib/location_sessions_factory_spec.rb
  spec/models/cohort_import_spec.rb
  spec/models/school_move_spec.rb
Labels: feature

#4219 Ensure register attendance buttons show correctly
  app/policies/session_attendance_policy.rb
  spec/policies/session_attendance_policy_spec.rb
Labels: bug

#4220 Add mavis teams list command
  Gemfile
  Gemfile.lock
  app/lib/mavis_cli.rb
  app/lib/mavis_cli/teams/list.rb
  spec/features/cli_list_teams_spec.rb
Labels: operations

#4209 Show notice in session if any patients are missing NHS number
  app/components/app_patient_summary_component.rb
  app/components/app_session_actions_component.rb
  app/components/app_session_needs_review_warning_component.rb
  app/views/sessions/consent/show.html.erb
  app/views/sessions/patients/show.html.erb
  app/views/sessions/record/show.html.erb
  app/views/sessions/register/show.html.erb
  app/views/sessions/triage/show.html.erb
  config/locales/en.yml
  spec/components/app_patient_summary_component_spec.rb
  spec/components/app_session_actions_component_spec.rb
  spec/components/app_session_needs_review_warning_component_spec.rb
  spec/features/filter_state_persistence_spec.rb
Labels: imms fhir api

#4228 Revert "Turn off preparation period in QA"
  terraform/app/env/qa.tfvars
Labels: operations

#4224 Enable preparation period from 18th August
  terraform/app/env/production.tfvars
Labels: infrastructure

#4192 Choose team when signing in
  app/controllers/application_controller.rb
  app/controllers/concerns/authentication_concern.rb
  app/controllers/users/errors_controller.rb
  app/controllers/users/omniauth_callbacks_controller.rb
  app/controllers/users/teams_controller.rb
  app/forms/select_team_form.rb
  app/models/cis2_info.rb
  app/models/user.rb
  app/views/users/errors/organisation_not_found.html.erb
  app/views/users/errors/role_not_found.html.erb
  app/views/users/errors/team_not_found.html.erb
  app/views/users/errors/workgroup_not_found.html.erb
  app/views/users/teams/new.html.erb
  config/routes.rb
  spec/factories/users.rb
  spec/features/e2e_journey_spec.rb
  spec/features/manage_clinic_sessions_spec.rb
  spec/features/manage_school_sessions_spec.rb
  spec/features/parental_consent_spec.rb
  spec/features/triage_spec.rb
  spec/features/user_cis2_authentication_from_redirect_spec.rb
  spec/features/user_cis2_authentication_from_start_page_spec.rb
  spec/features/user_cis2_authentication_select_team_spec.rb
  spec/features/user_cis2_authentication_with_empty_role_spec.rb
  spec/features/user_cis2_authentication_with_wrong_organisation_spec.rb
  spec/features/user_cis2_authentication_with_wrong_role_spec.rb
  spec/features/user_cis2_authentication_with_wrong_workgroup_spec.rb
  spec/forms/select_team_form_spec.rb
  spec/models/user_spec.rb
  spec/requests/patient_sessions/activity_spec.rb
  spec/support/cis2_auth_helper.rb
  tests/accessibility.spec.ts
Labels: feature

#4247 Hide patients vaccinated by the same organisation but different team
  app/policies/patient_policy.rb
  app/policies/vaccination_record_policy.rb
  spec/policies/patient_policy_spec.rb
  spec/policies/vaccination_record_policy_spec.rb
Labels: bug

#4248 Ensure aged out patients are added to community clinic
  app/jobs/patients_aged_out_of_school_job.rb
  spec/jobs/patients_aged_out_of_school_job_spec.rb
Labels: bug

#4250 Default session form academic year to pending
  app/forms/session_search_form.rb
  spec/features/td_ipv_already_had_spec.rb
  spec/features/triage_delay_vaccination_spec.rb
  spec/forms/session_search_form_spec.rb
Labels: design tweak

#4258 Handle unknown session keys
  app/models/concerns/request_session_persistable.rb
  spec/models/concerns/request_session_persistable_spec.rb
Labels: bug

#4257 Allow signing in without a team workgroup
  app/controllers/concerns/authentication_concern.rb
  app/controllers/users/omniauth_callbacks_controller.rb
  app/forms/select_team_form.rb
  app/models/cis2_info.rb
  app/views/users/errors/workgroup_not_found.html.erb
  spec/factories/users.rb
  spec/features/user_cis2_authentication_from_redirect_spec.rb
  spec/features/user_cis2_authentication_from_start_page_spec.rb
  spec/features/user_cis2_authentication_with_empty_role_spec.rb
  spec/features/user_cis2_authentication_with_wrong_organisation_spec.rb
  spec/features/user_cis2_authentication_with_wrong_role_spec.rb
  spec/features/user_cis2_authentication_with_wrong_workgroup_spec.rb
  spec/support/cis2_auth_helper.rb
Labels: operations

#4263 Spoof user agent when downloading GIAS data
  app/lib/mavis_cli/gias/download.rb
Labels: bug

#4262 Ensure triage and consent tags use the correct status colour
  app/helpers/consents_helper.rb
  app/helpers/triages_helper.rb
Labels: design tweak

#4276 Allow writing to db/data
  Dockerfile
Labels: infrastructure

#4277 Add script to prepare Coventry for flu
  app/lib/team_migration/base.rb
  app/lib/team_migration/coventry.csv
  app/lib/team_migration/coventry.rb
  lib/tasks/migrate_team.rake
  spec/lib/team_migration/coventry_spec.rb
Labels: operations

#4281 Handle closing Coventry school
  app/lib/team_migration/base.rb
  app/lib/team_migration/coventry.csv
  app/lib/team_migration/coventry.rb
  spec/lib/team_migration/coventry_spec.rb
Labels: operations

#4283 Move logging line in to correct place
  app/lib/team_migration/base.rb
Labels: refactor

#4284 Fix typo in Leicestershire schools CSV
  app/lib/team_migration/leicestershire.csv
Labels: bug

#4289 Disable PDS update during import completely
  app/models/concerns/csv_importable.rb
  spec/features/import_child_pds_lookup_extravaganza_spec.rb
Labels: operations, refactor

#4292 Small improvements to vaccination programmes table
  app/components/app_patient_programmes_table_component.rb
  config/locales/en.yml
Labels: refactor

#3809 Complete implementation of valkey with a connected sidekiq service
  bin/docker-start
  terraform/account/resources/iam_policy_DeployMavisResources.json
  terraform/app/ecs.tf
  terraform/app/env/preview.tfvars
  terraform/app/env/sandbox-alpha.tfvars
  terraform/app/env/sandbox-beta.tfvars
  terraform/app/env/test.tfvars
  terraform/app/env/training.tfvars
  terraform/app/outputs.tf
  terraform/app/valkey.tf
  terraform/app/variables.tf
  terraform/documentation/valkey-sidekiq-setup.md
Labels: performance, infrastructure

#4296 Increase PDS rate limit to 50 req/s
  config/initializers/sidekiq.rb
  config/settings.yml
  config/settings/development.yml
  config/settings/staging.yml
  config/settings/test.yml
  terraform/app/env/preview.tfvars
  terraform/app/env/production.tfvars
  terraform/app/env/test.tfvars
  terraform/app/variables.tf
Labels: operations

#4291 Simplify PDS update during import
  app/jobs/process_patient_changesets_job.rb
  app/models/concerns/csv_importable.rb
  app/models/patient_changeset.rb
  spec/features/import_child_pds_lookup_extravaganza_spec.rb
  spec/fixtures/cohort_import/pds_extravaganza.csv
  spec/support/pds_helper.rb
Labels: operations, refactor

#4319 Remove typo in monitoring deploy
  .github/workflows/deploy-monitoring.yml
  terraform/account/resources/iam_policy_DeployMonitoringResources.json
  terraform/monitoring/tf_grafana.sh
Labels: bug, infrastructure

#4321 Handle `nil` vaccination record location
  app/lib/reports/systm_one_exporter.rb
  spec/factories/vaccination_records.rb
  spec/lib/reports/systm_one_exporter_spec.rb
Labels: bug

#4297 One location multiple sites
  app/components/app_session_summary_component.rb
  app/controllers/sessions_controller.rb
  app/lib/mavis_cli.rb
  app/lib/mavis_cli/gias/import.rb
  app/lib/mavis_cli/schools/add_programme_year_group.rb
  app/lib/mavis_cli/schools/add_to_team.rb
  app/lib/mavis_cli/schools/create.rb
  app/lib/mavis_cli/schools/move_patients.rb
  app/lib/mavis_cli/schools/remove_programme_year_group.rb
  app/lib/reports/export_formatters.rb
  app/lib/reports/school_moves_exporter.rb
  app/lib/reports/systm_one_exporter.rb
  app/models/cohort_import_row.rb
  app/models/immunisation_import_row.rb
  app/models/location.rb
  app/models/onboarding.rb
  app/views/parent_interface/consent_forms/edit/school.html.erb
  db/migrate/20250814170010_add_site_to_locations.rb
  db/migrate/20250816113617_add_systm_one_code_to_locations.rb
  db/schema.rb
  docs/ops-tasks.md
  script/generate_model_office_data.rb
  spec/factories/locations.rb
  spec/features/cli_gias_import_spec.rb
  spec/features/cli_schools_create_spec.rb
  spec/fixtures/immunisation_import/systm_one.csv
  spec/lib/reports/school_moves_exporter_spec.rb
  spec/lib/reports/systm_one_exporter_spec.rb
  spec/models/cohort_import_row_spec.rb
  spec/models/cohort_import_spec.rb
  spec/models/immunisation_import_spec.rb
  spec/models/location_spec.rb
Labels: feature

#4359 Add delegation columns to sessions
  app/models/class_imports_patient.rb
  app/models/cohort_imports_patient.rb
  app/models/session.rb
  db/migrate/20250820145646_add_delegation_to_sessions.rb
  db/schema.rb
  spec/factories/patient_changesets.rb
  spec/factories/sessions.rb
  spec/models/session_spec.rb
Labels: refactor

#4361 Rename CIS2Info#can_prescribe_pgd? to can_supply_using_pgd?
  app/controllers/concerns/authentication_concern.rb
  app/models/cis2_info.rb
  app/models/user.rb
  app/policies/gillick_assessment_policy.rb
  app/policies/triage_policy.rb
  app/policies/vaccination_record_policy.rb
  spec/models/user_spec.rb
Labels: refactor

#4364 Use global ODS code sequence in tests
  spec/factories/organisations.rb
  spec/factories/teams.rb
Labels: refactor

#4279 Add parent details to consent summary
  app/assets/stylesheets/components/_summary-list.scss
  app/helpers/parents_helper.rb
  app/views/consent_forms/search.html.erb
Labels: design tweak

#4378 Track which users should be shown in list of suppliers
  app/controllers/users/omniauth_callbacks_controller.rb
  app/controllers/users/sessions_controller.rb
  app/models/user.rb
  config/initializers/inflections.rb
  db/migrate/20250822094829_add_show_in_suppliers_to_users.rb
  db/schema.rb
  spec/factories/users.rb
  spec/features/user_cis2_authentication_from_redirect_spec.rb
  spec/features/user_cis2_authentication_spec.rb
  spec/features/user_cis2_authentication_with_wrong_organisation_spec.rb
  spec/models/patient_changeset_spec.rb
  spec/models/user_spec.rb
Labels: operations

#4324 Add new vaccine icons
  app/assets/stylesheets/components/_index.scss
  app/assets/stylesheets/components/_vaccine-method.scss
  app/components/app_patient_session_record_component.rb
  app/components/app_patient_session_search_result_card_component.rb
Labels: design tweak

#4383 Skip wildcard searches for names ≤ 3 characters
  app/jobs/process_patient_changesets_job.rb
  app/models/pds_search_result.rb
  spec/jobs/process_patient_changesets_job_spec.rb
Labels: bug

#4391 Fix tests that fail during preparation period
  spec/features/parental_consent_school_session_completed_spec.rb
  spec/features/triage_then_parental_consent_refused_spec.rb
  spec/jobs/send_clinic_subsequent_invitations_job_spec.rb
Labels: bug

#4385 Finish processing patient changeset on error
  app/jobs/process_patient_changesets_job.rb
Labels: bug

#4392 Remove redundant PDS fuzzy search with history
  app/jobs/process_patient_changesets_job.rb
  app/models/pds_search_result.rb
  spec/features/import_child_pds_lookup_extravaganza_spec.rb
  spec/jobs/process_patient_changesets_job_spec.rb
Labels: bug

#4368 Deduplicate parents and relationships before incrementing import counts
  app/jobs/commit_patient_changesets_job.rb
  app/models/patient_import.rb
Labels: bug

#4394 Ensure patients with PDS search results can be merged
  app/lib/patient_merger.rb
  spec/factories/pds_search_results.rb
  spec/lib/patient_merger_spec.rb
Labels: bug

#3972 Check flipper before running CLI imms API sync command
  app/lib/mavis_cli/vaccination_records/sync.rb
  spec/features/cli_vaccination_records_sync_spec.rb
Labels: imms fhir api

#4398 Add foundational delegation methods
  app/models/programme.rb
  app/models/session.rb
  db/seeds.rb
  spec/models/programme_spec.rb
  spec/models/session_spec.rb
  spec/support/cis2_auth_helper.rb
Labels: refactor

#4373 Validate child names on import
  app/lib/apostrophe_normaliser.rb
  app/models/patient_import_row.rb
  spec/fixtures/cohort_import/invalid_fields.csv
  spec/models/cohort_import_row_spec.rb
  spec/models/cohort_import_spec.rb
Labels: bug

#4401 Persist all PDS search results for patient changesets
  app/jobs/process_patient_changesets_job.rb
Labels: bug

#4408 Fix `session_attendance` association
  app/lib/status_updater.rb
  app/models/patient_session/registration_status.rb
  app/models/session_attendance.rb
  spec/models/patient_session/registration_status_spec.rb
Labels: bug

#4363 Add `is_prescriber?`
  app/controllers/concerns/authentication_concern.rb
  app/models/cis2_info.rb
  app/models/user.rb
  spec/factories/users.rb
  spec/models/user_spec.rb
Labels: operations

#4415 Make `VaccinationRecord.protocol` optional from imports and API
  app/models/immunisation_import_row.rb
  app/models/vaccination_record.rb
  spec/models/vaccination_record_spec.rb
Labels: data consistency

#4422 deduplicate patients without NHS numbers
  app/jobs/commit_patient_changesets_job.rb
  spec/features/import_child_pds_lookup_extravaganza_spec.rb
  spec/fixtures/cohort_import/pds_extravaganza.csv
Labels: bug

#4420 Vaccine method icon incorrectly shown on consent and triage screens
  app/components/app_patient_session_search_result_card_component.rb
  spec/components/app_patient_session_search_result_card_component_spec.rb
Labels: design tweak

#4431 On-demand DB snapshot for data replication environment
  .github/workflows/data-replication-pipeline.yml
  terraform/account/deployment_permissions.tf
  terraform/account/resources/iam_policy_DatabaseSnapshotPolicy.json
Labels: github_actions

#4434 Disable Sentry in sandbox environments
  config/initializers/sentry.rb
  terraform/app/variables.tf
Labels: infrastructure

#4442 Always run imports in the background
  app/controllers/class_imports_controller.rb
  app/controllers/cohort_imports_controller.rb
  app/controllers/immunisation_imports_controller.rb
  app/jobs/process_patient_changesets_job.rb
  app/models/concerns/csv_importable.rb
  spec/features/e2e_journey_spec.rb
  spec/features/hpv_vaccination_offline_spec.rb
  spec/features/import_child_pds_lookup_extravaganza_spec.rb
  spec/features/import_child_records_preparation_spec.rb
  spec/features/import_child_records_spec.rb
  spec/features/import_child_records_with_duplicates_spec.rb
  spec/features/import_child_records_with_twins_spec.rb
  spec/features/import_class_lists_move_spec.rb
  spec/features/import_class_lists_spec.rb
  spec/features/import_class_lists_with_duplicates_spec.rb
  spec/features/import_vaccination_records_spec.rb
  spec/features/import_vaccination_records_with_duplicates_spec.rb
  spec/features/triage_partially_vaccinated_spec.rb
  spec/jobs/process_patient_changesets_job_spec.rb
Labels: operations, refactor

#4443 Refactor waiting for imports to finish
  spec/features/e2e_journey_spec.rb
  spec/features/hpv_vaccination_offline_spec.rb
  spec/features/import_child_pds_lookup_extravaganza_spec.rb
  spec/features/import_child_records_preparation_spec.rb
  spec/features/import_child_records_slow_spec.rb
  spec/features/import_child_records_spec.rb
  spec/features/import_child_records_with_duplicates_spec.rb
  spec/features/import_child_records_with_twins_spec.rb
  spec/features/import_class_lists_move_spec.rb
  spec/features/import_class_lists_spec.rb
  spec/features/import_class_lists_with_duplicates_spec.rb
  spec/features/import_vaccination_records_spec.rb
  spec/features/import_vaccination_records_with_duplicates_spec.rb
  spec/features/triage_partially_vaccinated_spec.rb
  spec/fixtures/cohort_import/valid_1000_rows.csv
  spec/spec_helper.rb
  spec/support/imports_helper.rb
Labels: refactor

#4351 Set `location_id` on vaccination records in clinic
  app/controllers/draft_vaccination_records_controller.rb
  app/controllers/patient_sessions/programmes_controller.rb
  app/helpers/address_helper.rb
  app/models/draft_vaccination_record.rb
  app/views/draft_vaccination_records/location.html.erb
  spec/helpers/address_helper_spec.rb
Labels: data consistency

#4367 Replace pre-screening patient session foreign key
  app/components/app_patient_session_record_component.rb
  app/components/app_vaccinate_form_component.rb
  app/controllers/api/testing/teams_controller.rb
  app/controllers/patient_sessions/base_controller.rb
  app/controllers/patient_sessions/session_attendances_controller.rb
  app/controllers/patient_sessions/vaccinations_controller.rb
  app/forms/vaccinate_form.rb
  app/lib/patient_merger.rb
  app/models/patient.rb
  app/models/patient_session.rb
  app/models/pre_screening.rb
  app/models/session.rb
  app/models/session_date.rb
  db/migrate/20250821124416_remove_patient_session_from_pre_screenings.rb
  db/schema.rb
  spec/components/app_activity_log_component_spec.rb
  spec/components/app_vaccinate_form_component_spec.rb
  spec/controllers/api/testing/teams_controller_spec.rb
  spec/factories/pre_screenings.rb
  spec/lib/patient_merger_spec.rb
  spec/models/pre_screening_spec.rb
  spec/models/session_date_spec.rb
Labels: refactor
