Repository nhsuk/manage-vaccinations-in-schools, pull requests merged in 2025-09, with the labels that each got.

#4446 Grafana access for DataReplication SSO group
  terraform/monitoring/aws/variables.tf
Labels: infrastructure

#4453 Fix tests outside of preparation period
  app/views/sessions/manage_consent_reminders/show.html.erb
  db/seeds.rb
  spec/components/app_patient_session_table_component_spec.rb
  spec/features/cli_gias_check_import_spec.rb
  spec/features/cli_stats_organisations_spec.rb
  spec/features/hpv_vaccination_offline_spec.rb
  spec/forms/triage_form_spec.rb
  spec/lib/reports/careplus_exporter_spec.rb
  spec/lib/reports/systm_one_exporter_spec.rb
  spec/lib/stats/consents_by_school_spec.rb
  spec/lib/status_generator/consent_spec.rb
  spec/lib/status_generator/registration_spec.rb
  spec/lib/vaccination_notification_criteria_spec.rb
  spec/models/draft_vaccination_record_spec.rb
  spec/models/immunisation_import_row_spec.rb
  spec/models/immunisation_import_spec.rb
  spec/models/patient/consent_status_spec.rb
  spec/models/patient_session/registration_status_spec.rb
  spec/models/pre_screening_spec.rb
  spec/models/session_date_spec.rb
  spec/policies/session_attendance_policy_spec.rb
Labels: refactor

#4454 Ensure seeds don't create session dates outside range
  db/seeds.rb
Labels: refactor

#4461 Ensure components are initiated when a page uses Turbo
  app/assets/javascripts/application.js
  app/views/layouts/application.html.erb
Labels: bug

#4473 Refactor JWT-generation methods out of ReportingAPI controller and into the model
  app/controllers/api/reporting/one_time_tokens_controller.rb
  app/controllers/concerns/reporting_api/token_authentication_concern.rb
  app/models/reporting_api/one_time_token.rb
  spec/controllers/api/reporting/one_time_tokens_controller_spec.rb
  spec/controllers/api/reporting/totals_controller_spec.rb
  spec/controllers/concerns/reporting_api/token_authentication_concern_spec.rb
  spec/models/reporting_api/one_time_token_spec.rb
Labels: refactor

#4470 Update content shown in triage section
  app/components/app_patient_session_triage_component.html.erb
  spec/features/triage_spec.rb
Labels: design tweak

#4492 Ensure `patient_id` is not null
  app/models/vaccination_record.rb
  db/migrate/20250903153120_make_vaccination_record_patient_id_not_null.rb
  db/schema.rb
  spec/factories/vaccination_records.rb
  spec/models/vaccination_record_spec.rb
Labels: data consistency

#4493 Verify that HCA's can't see triaged injected patients when national protocol is off
  spec/factories/patients.rb
  spec/features/flu_vaccination_hca_national_protocol_spec.rb
  spec/features/flu_vaccination_hca_pgd_supply_spec.rb
Labels: refactor

#4503 Small fixes for delegation
  app/forms/triage_form.rb
  spec/features/triage_spec.rb
  spec/features/verbal_consent_given_triage_psd_spec.rb
Labels: bug

#4505 Use dig for safe nested array navigation
  app/views/vaccines/index.html.erb
Labels: bug

#4510 Hide PSD tags on session activity page
  app/components/app_activity_log_component.rb
  app/views/patient_sessions/_header.html.erb
  spec/features/flu_vaccination_hca_psd_spec.rb
Labels: design tweak

#4516 Ensure invalidated PSDs aren't in offline export
  app/lib/reports/offline_session_exporter.rb
  spec/factories/patient_specific_directions.rb
  spec/lib/reports/offline_session_exporter_spec.rb
Labels: bug

#4478 Return user nav info in reporting token
  app/controllers/api/reporting/one_time_tokens_controller.rb
  app/controllers/users/logout_controller.rb
  app/views/logout/show.html.erb
  config/routes.rb
  spec/controllers/api/reporting/one_time_tokens_controller_spec.rb
Labels: feature

#4502 Use Sidekiq for comms and add rate limits
  app/jobs/concerns/notify_throttling_concern.rb
  app/jobs/email_delivery_job.rb
  app/jobs/notify_delivery_job.rb
  app/jobs/sms_delivery_job.rb
  app/jobs/status_updater_job.rb
  config/initializers/sentry.rb
  config/initializers/sidekiq.rb
  config/settings.yml
  config/sidekiq.yml
  spec/jobs/email_delivery_job_spec.rb
  spec/jobs/sms_delivery_job_spec.rb
Labels: operations

#4518 Reduce GOV.UK Notify rate limit
  config/settings.yml
Labels: operations

#4517 Hide button to send reminders if not open
  app/controllers/sessions/manage_consent_reminders_controller.rb
  app/views/sessions/manage_consent_reminders/show.html.erb
  config/locales/en.yml
Labels: bug

#4529 Ensure patients with notes can be merged
  app/lib/patient_merger.rb
  spec/lib/patient_merger_spec.rb
Labels: bug

#4433 Combine consent given status and vaccine method
  app/components/app_activity_log_component.rb
  app/components/app_programme_status_tags_component.rb
  app/controllers/sessions/consent_controller.rb
  app/forms/patient_search_form.rb
  app/models/session.rb
  config/locales/status.en.yml
  spec/components/app_patient_session_search_result_card_component_spec.rb
  spec/components/app_programme_status_tags_component_spec.rb
  spec/forms/patient_search_form_spec.rb
  spec/models/session_spec.rb
Labels: feature

#4532 Improve performance of lookup by ensuring patient results have hash
  app/policies/vaccination_record_policy.rb
Labels: performance

#4475 Ensure reliable NHS number retrieval from search results
  app/jobs/process_patient_changesets_job.rb
  spec/features/import_child_pds_lookup_extravaganza_spec.rb
  spec/jobs/process_patient_changesets_job_spec.rb
  spec/support/pds_helper.rb
Labels: operations

#4476 Remove fuzzy-search from cascading PDS search algorithm
  app/jobs/process_patient_changesets_job.rb
  spec/factories/patient_changesets.rb
  spec/features/import_child_pds_lookup_extravaganza_spec.rb
  spec/jobs/process_patient_changesets_job_spec.rb
Labels: operations

#4452 Show uploaded file name on import screens
  app/components/app_imports_table_component.html.erb
  app/views/imports/show.html.erb
  spec/components/app_imports_table_component_spec.rb
Labels: design tweak

#4543 Ensure programme tags are ordered
  app/components/app_programme_tags_component.rb
  spec/components/app_programme_tags_component_spec.rb
Labels: bug

#4542 Add SystmOne codes for flu
  app/lib/reports/systm_one_exporter.rb
  spec/lib/reports/systm_one_exporter_spec.rb
Labels: operations

#4547 Fix viewing patient when there's no date today
  app/components/app_patient_session_record_component.rb
  spec/factories/sessions.rb
  spec/features/manage_attendance_spec.rb
Labels: bug

#4544 Fix grammar in PSD eligibility message for singular case
  app/views/sessions/patient_specific_directions/show.html.erb
  spec/features/flu_vaccination_hca_psd_spec.rb
Labels: design tweak

#4552 Make flu SystmOne codes based on dose sequence
  app/lib/reports/systm_one_exporter.rb
  spec/lib/reports/systm_one_exporter_spec.rb
Labels: operations

#4562 Fix HCAs unable to record vaccination if PSD exists
  app/components/app_vaccinate_form_component.rb
  spec/features/flu_vaccination_hca_national_protocol_spec.rb
  spec/features/flu_vaccination_hca_pgd_supply_spec.rb
Labels: bug

#4511 PostgreSQL logging
  terraform/app/rds.tf
Labels: infrastructure

#4549 Improve patient lookup speed
  app/policies/patient_policy.rb
Labels: performance

#4575 Fix syntax error in Sidekiq configuration
  config/sidekiq.yml
Labels: bug

#4580 Fix merging patients with session attendances
  app/lib/patient_merger.rb
  spec/lib/patient_merger_spec.rb
Labels: bug

#4583 Optimise migration that replaces `patient_session_id`
  db/migrate/20250822153747_remove_patient_session_from_patient_registration_statuses.rb
Labels: refactor

#4582 Ensure `CommitPatientChangesetsJob` runs in `imports` queue
  app/jobs/commit_patient_changesets_job.rb
  config/sidekiq.yml
Labels: operations

#4584 Check all the relevant feature flags when displaying in the UI
  app/components/app_vaccination_record_summary_component.rb
  spec/components/app_vaccination_record_summary_component_spec.rb
Labels: design tweak

#4577 Run sidekiq locally
  .tool-versions
  Procfile
  Procfile.dev
  README.md
Labels: refactor, infrastructure

#4587 Fix queue for `SyncVaccinationRecordToNHSJob`
  app/jobs/sync_vaccination_record_to_nhs_job.rb
  spec/models/immunisation_import_spec.rb
Labels: bug

#4622 Call `StatusUpdater` after Imms API search
  app/jobs/search_vaccination_records_in_nhs_job.rb
  spec/jobs/search_vaccination_records_in_nhs_job_spec.rb
Labels: bug

#4620 Hide discontinued vaccines from summary table
  app/components/app_vaccinations_summary_table_component.html.erb
  app/components/app_vaccinations_summary_table_component.rb
  app/controllers/sessions/record_controller.rb
  spec/components/app_vaccinations_summary_table_component_spec.rb
  spec/features/tallying_spec.rb
Labels: bug

#4623 Fix flaky PDS import test
  spec/features/import_child_pds_lookup_extravaganza_spec.rb
  spec/features/import_child_records_spec.rb
  spec/support/imports_helper.rb
Labels: refactor

#4621 Use `mail_to` helper
  app/views/errors/internal_server_error.html.erb
  app/views/errors/not_found.html.erb
  app/views/errors/unprocessable_entity.html.erb
  app/views/parent_interface/consent_forms/deadline_passed.html.erb
Labels: refactor

#4640 Ensure `NotifyLogEntry` is deleted in testing
  app/controllers/api/testing/teams_controller.rb
Labels: bug

#4644 Replace IN loop with EXIST
  app/policies/vaccination_record_policy.rb
Labels: performance

#4646 Add `data_migrations:fix_vaccination_records_location`
  lib/tasks/data_migrations.rake
Labels: data consistency

#4647 Introduce a rails cache for web server
  terraform/app/ecs.tf
  terraform/app/valkey.tf
Labels: infrastructure

#4649 Use `EXISTS` instead of `IN`
  app/controllers/sessions_controller.rb
  app/models/patient.rb
  app/models/patient_location.rb
Labels: performance

#4663 Ensure cache invalidation happens
  app/controllers/consent_forms_controller.rb
  app/controllers/imports/issues_controller.rb
  app/forms/import_duplicate_form.rb
  app/forms/school_move_form.rb
  spec/features/import_child_records_with_duplicates_spec.rb
  spec/features/parental_consent_clinic_spec.rb
  spec/features/parental_consent_manual_matching_spec.rb
Labels: bug

#4664 Fix reference to patient session factory
  spec/policies/school_move_policy_spec.rb
Labels: refactor

#4662 Revert caching of navigation bar counts
  Gemfile
  Gemfile.lock
  app/controllers/consent_forms_controller.rb
  app/controllers/imports/issues_controller.rb
  app/controllers/parent_interface/consent_forms_controller.rb
  app/forms/import_duplicate_form.rb
  app/forms/school_move_form.rb
  app/jobs/commit_patient_changesets_job.rb
  app/jobs/consent_form_matching_job.rb
  app/lib/team_cached_counts.rb
  config/environments/production.rb
Labels: bug

#4667 Import test coverage for invite to clinic
  spec/features/manage_school_sessions_spec.rb
Labels: refactor

#4671 Update `AppCardComponent` to allow for more variants and content types
  app/assets/stylesheets/components/_card.scss
  app/components/app_card_component.rb
  app/components/app_card_heading_component.rb
  app/components/app_compare_consent_form_and_patient_component.rb
  app/components/app_consent_card_component.rb
  app/components/app_consent_form_card_component.rb
  app/components/app_health_answers_card_component.rb
  app/components/app_parent_card_component.rb
  app/components/app_patient_card_component.rb
  app/components/app_patient_search_form_component.rb
  app/components/app_patient_search_result_card_component.rb
  app/components/app_patient_session_consent_component.html.erb
  app/components/app_patient_session_outcome_component.rb
  app/components/app_patient_session_search_result_card_component.rb
  app/components/app_patient_session_triage_component.html.erb
  app/components/app_programme_stats_component.html.erb
  app/components/app_session_card_component.rb
  app/components/app_session_search_form_component.rb
  app/views/consent_forms/search.html.erb
  app/views/consent_forms/show.html.erb
  app/views/dashboard/index.html.erb
  app/views/imports/issues/show.html.erb
  app/views/imports/show.html.erb
  app/views/parent_interface/consent_forms/confirm.html.erb
  app/views/patients/index.html.erb
  app/views/programmes/overview/show.html.erb
  app/views/school_moves/show.html.erb
  app/views/sessions/edit/show.html.erb
  app/views/teams/show.html.erb
  app/views/vaccines/index.html.erb
  app/views/vaccines/show.html.erb
  spec/components/app_card_component_spec.rb
  spec/components/app_card_heading_component_spec.rb
  spec/components/app_patient_session_consent_component_spec.rb
  spec/components/app_patient_session_triage_component_spec.rb
Labels: refactor, design tweak

#4597 Deduplicate parents with same email in same file
  app/jobs/commit_patient_changesets_job.rb
  spec/features/import_child_pds_lookup_extravaganza_spec.rb
  spec/fixtures/cohort_import/pds_extravaganza.csv
Labels: bug

#4675 Upgrade to latest Terraform
  .github/workflows/data-replication-pipeline.yml
  .github/workflows/deploy-application.yml
  .github/workflows/deploy-backup-infrastructure.yml
  .github/workflows/deploy-infrastructure.yml
  .github/workflows/deploy-monitoring.yml
  .github/workflows/destroy-infrastructure.yml
  .github/workflows/test.yml
  .tool-versions
  terraform/account/main.tf
  terraform/app/main.tf
  terraform/app/modules/dms/main.tf
  terraform/app/modules/dns/main.tf
  terraform/app/modules/ecs_service/main.tf
  terraform/app/modules/vpc_endpoint/main.tf
  terraform/backup/destination-bootstrap/main.tf
  terraform/backup/destination/main.tf
  terraform/backup/source/main.tf
  terraform/bootstrap/main.tf
  terraform/data_replication/main.tf
  terraform/modules/s3/main.tf
  terraform/monitoring/aws/main.tf
  terraform/monitoring/grafana/main.tf
Labels: infrastructure

#4626 Ensure already vaccinated patients don't receive clinic invitations
  app/models/session_notification.rb
  spec/models/session_notification_spec.rb
Labels: bug

#4618 Prevent Imms API syncs from changing vaccs record `updated_at` field
  app/lib/nhs/immunisations_api.rb
  spec/lib/nhs/immunisations_api_spec.rb
Labels: operations, imms fhir api

#4631 Ensure flu search is done before consents go out
  app/jobs/enqueue_vaccinations_search_in_nhs_job.rb
  config/sidekiq.yml
  spec/jobs/enqueue_vaccinations_search_in_nhs_job_spec.rb
Labels: bug, imms fhir api

#4642 Fix session selection logic
  app/jobs/enqueue_vaccinations_search_in_nhs_job.rb
  spec/jobs/enqueue_vaccinations_search_in_nhs_job_spec.rb
Labels: bug, imms fhir api

#4677 Remove `data_migrations:fix_vaccination_record_locations`
  lib/tasks/data_migrations.rake
Labels: refactor

#4660 Improve performance of team reset endpoint
  app/controllers/api/testing/teams_controller.rb
  app/models/class_imports_parent.rb
  app/models/class_imports_parent_relationship.rb
  app/models/class_imports_patient.rb
  app/models/cohort_imports_parent.rb
  app/models/cohort_imports_parent_relationship.rb
  app/models/cohort_imports_patient.rb
  app/models/consent_form_programme.rb
  db/migrate/20250918075325_add_foreign_key_cascade_to_join_tables.rb
  db/schema.rb
  spec/factories/consent_form_programmes.rb
Labels: performance

#4676 Ensure `LocationProgrammeYearGroups` are created
  app/forms/session_programmes_form.rb
  app/lib/mavis_cli/schools/move_patients.rb
  spec/features/cli_schools_move_patients_spec.rb
  spec/forms/session_programmes_form_spec.rb
Labels: bug, operations

#4682 Don't delete teams in a transaction
  app/controllers/api/testing/teams_controller.rb
Labels: refactor

#4681 Ensure duplicate school moves don't exist
  app/lib/patient_merger.rb
  spec/lib/patient_merger_spec.rb
Labels: bug

#4650 Disallow offline spreadsheets from editing records received from the Imms API
  app/forms/import_duplicate_form.rb
  app/lib/reports/offline_session_exporter.rb
  app/models/concerns/pending_changes_concern.rb
  app/models/immunisation_import_row.rb
  app/views/imports/issues/show.html.erb
  spec/features/vaccination_offline_spec.rb
  spec/forms/import_duplicate_form_spec.rb
  spec/models/immunisation_import_row_spec.rb
Labels: feature, imms fhir api

#4366 Limit cohort imports by team's schools
  app/models/cohort_import_row.rb
  spec/models/cohort_import_row_spec.rb
Labels: bug

#3234 Don't invalidate self-consent if vaccinated
  app/jobs/invalidate_self_consents_job.rb
  spec/jobs/invalidate_self_consents_job_spec.rb
Labels: bug

#4387 Check birth century
  app/models/patient_import_row.rb
  spec/models/class_import_row_spec.rb
  spec/models/cohort_import_row_spec.rb
Labels: bug

#4670 Handle invalid phone errors from GOV.UK Notify
  app/components/app_parent_summary_component.rb
  app/jobs/sms_delivery_job.rb
  app/models/notify_log_entry.rb
  spec/jobs/sms_delivery_job_spec.rb
Labels: operations

#4706 Gracefully handle page overflow errors
  app/controllers/api/reporting/base_controller.rb
  app/controllers/sessions/record_controller.rb
  app/controllers/sessions_controller.rb
  config/initializers/pagy.rb
  spec/features/manage_children_spec.rb
Labels: bug

#4699 Ensure deceased archive reason is created
  app/models/patient.rb
  spec/models/patient_spec.rb
Labels: bug, operations

#4661 Allow users to sort offline sheet by consent time
  app/lib/reports/export_formatters.rb
  spec/lib/reports/programme_vaccinations_exporter_spec.rb
Labels: design tweak

#4723 Fix schedule for enqueueing imms api searches
  config/sidekiq.yml
Labels: bug

#4711 Add IAM policy to deny PII access
  terraform/account/main.tf
Labels: infrastructure

#4725 Render import errors inside AppCardComponent
  app/components/app_import_errors_component.rb
Labels: design tweak

#4707 Ensure patients are visible when PSDs only are enabled
  app/controllers/sessions/record_controller.rb
  spec/features/flu_vaccination_hca_psd_spec.rb
Labels: bug

#4732 Fix pending changes whitespace normalisation
  app/models/concerns/pending_changes_concern.rb
  spec/models/concerns/pending_changes_concern_spec.rb
Labels: bug

#4356 Make superuser permissions based on activities
  app/models/cis2_info.rb
  app/models/user.rb
  app/policies/notices_policy.rb
  app/policies/vaccination_record_policy.rb
  spec/factories/users.rb
  spec/models/user_spec.rb
  spec/support/cis2_auth_helper.rb
Labels: operations

#4432 Separate app and infra deployments
  .github/workflows/build-and-push-image.yml
  .github/workflows/data-replication-pipeline.yml
  .github/workflows/deploy-application.yml
  .github/workflows/deploy-infrastructure.yml
  .github/workflows/deploy.yml
  .github/workflows/refresh-data-replication.yml
  bin/docker-entrypoint
  config/templates/appspec.yaml.tpl
  script/requirements.txt
  script/shell.sh
  terraform/account/deployment_permissions.tf
  terraform/account/resources/iam_policy_DeployECSServiceResources.json
  terraform/account/resources/iam_role_github_trust_policy_development.json.tftpl
  terraform/account/variables.tf
  terraform/app/codedeploy.tf
  terraform/app/db_migration_configuration.tf
  terraform/app/ecs.tf
  terraform/app/env/preview.tfvars
  terraform/app/env/production.tfvars
  terraform/app/env/qa.tfvars
  terraform/app/env/sandbox-alpha.tfvars
  terraform/app/env/sandbox-beta.tfvars
  terraform/app/env/test.tfvars
  terraform/app/env/training.tfvars
  terraform/app/iam.tf
  terraform/app/iam_policy_documents.tf
  terraform/app/modules/ecs_service/main.tf
  terraform/app/modules/ecs_service/outputs.tf
  terraform/app/modules/ecs_service/variables.tf
  terraform/app/outputs.tf
  terraform/app/ssm_parameters.tf
  terraform/app/variables.tf
  terraform/data_replication/ecs.tf
  terraform/data_replication/outputs.tf
  terraform/data_replication/variables.tf
Labels: github_actions, refactor, infrastructure

#4755 Allow submitting consent for an unscheduled session
  app/controllers/parent_interface/consent_forms/base_controller.rb
  app/models/consent_form.rb
  spec/features/parental_consent_school_session_completed_spec.rb
  spec/models/consent_form_spec.rb
Labels: bug

#4740 Skip triage after verbal consent if not required
  app/controllers/draft_consents_controller.rb
  app/models/draft_consent.rb
  spec/features/e2e_journey_spec.rb
  spec/features/self_consent_spec.rb
  spec/features/verbal_consent_change_answers_spec.rb
  spec/features/verbal_consent_given_by_new_parental_contact_spec.rb
  spec/features/verbal_consent_given_spec.rb
  spec/features/verbal_consent_given_triage_psd_spec.rb
  spec/features/verbal_consent_given_when_previously_refused_spec.rb
Labels: operations, feature

#4768 Add crossorigin auth for manifest in non-prod
  app/helpers/application_helper.rb
Labels: performance
