Repository nhsuk/manage-vaccinations-in-schools, pull requests merged in 2025-05, with the labels that each got.

#3482 Add a test to ensure CSV files are converted to UTF-8
  spec/lib/csv_parser_spec.rb
Labels: refactor

#3400 Remove SystmOne import feature flag
  app/models/immunisation_import_row.rb
  app/views/immunisation_imports/new.html.erb
  config/feature_flags.yml
  spec/models/immunisation_import_row_spec.rb
  spec/models/immunisation_import_spec.rb
Labels: refactor

#3483 Add ecs:UpdateCluster permission
  terraform/resources/github_actions_policy.json
Labels: infrastructure

#3439 Remove "Report" action required
  app/components/app_patient_session_search_result_card_component.rb
  app/models/patient_session.rb
  spec/features/doubles_vaccination_administered_spec.rb
  spec/models/patient_session_spec.rb
Labels: design tweak

#3441 Remove pregnancy pre-screening for HPV
  app/forms/vaccinate_form.rb
  spec/features/e2e_journey_spec.rb
  spec/features/hpv_vaccination_administered_spec.rb
  spec/features/hpv_vaccination_already_had_spec.rb
  spec/features/hpv_vaccination_clinic_spec.rb
  spec/features/hpv_vaccination_delayed_spec.rb
  spec/features/hpv_vaccination_pre_screening_spec.rb
  spec/features/vaccination_todays_batch_spec.rb
Labels: design tweak

#3442 Avoid crash when editing response method
  app/views/draft_consents/confirm.html.erb
  spec/features/self_consent_spec.rb
Labels: bug

#3485 Fix header navigation to be compatible with NHS.UK Frontend 9.4.x
  app/assets/stylesheets/_header.scss
  app/assets/stylesheets/_overrides.scss
Labels: bug

#3484 Automatically overwrite incoming address
  app/models/patient_import_row.rb
  spec/models/class_import_row_spec.rb
  spec/models/cohort_import_row_spec.rb
Labels: feature

#3489 Ensure vaccine is set when saving a vaccination record
  app/models/draft_vaccination_record.rb
  spec/models/draft_vaccination_record_spec.rb
Labels: bug

#3490 Improve workflow for adding back into cohort
  app/models/patient_import.rb
  spec/models/cohort_import_spec.rb
Labels: operations

#3486 Add ability to remove parent relationships
  app/components/app_child_summary_component.rb
  app/components/app_parent_card_component.rb
  app/components/app_parent_summary_component.rb
  app/components/app_patient_card_component.rb
  app/components/app_vaccination_record_summary_component.rb
  app/controllers/parent_relationships_controller.rb
  app/models/parent_relationship.rb
  app/models/patient.rb
  app/views/parent_relationships/destroy.html.erb
  app/views/patients/edit.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/components/app_parent_summary_component_spec.rb
  spec/features/manage_children_spec.rb
  spec/features/parent_relationships_spec.rb
Labels: feature

#3492 Ensure "Other" delivery site can be chosen
  app/helpers/vaccinations_helper.rb
  app/models/programme.rb
  app/views/draft_vaccination_records/delivery.html.erb
  spec/features/hpv_vaccination_administered_spec.rb
Labels: bug

#3503 Fix "Check if Rails tests need to run" job
  .github/workflows/test.yml
Labels: github_actions

#3494 Various linting improvements
  hk.pkl
Labels: refactor

#3472 Programme cohorts should be sorted
  app/controllers/cohorts_controller.rb
  spec/features/cohorts_index_spec.rb
Labels: bug, ruby, design tweak

#3444 Add missing length validations
  app/forms/batch_form.rb
  app/models/batch.rb
  app/models/gillick_assessment.rb
  app/models/pre_screening.rb
  config/locales/en.yml
  spec/forms/batch_form_spec.rb
  spec/models/batch_spec.rb
  spec/models/consent_spec.rb
  spec/models/gillick_assessment_spec.rb
  spec/models/pre_screening_spec.rb
Labels: data consistency

#3515 Update README.md
  README.md
Labels: documentation

#3517 Refactor usage of `include_examples`
  spec/lib/reports/careplus_exporter_spec.rb
  spec/lib/reports/programme_vaccinations_exporter_spec.rb
Labels: refactor

#3511 Send vaccination record confirmations earlier
  app/jobs/send_vaccination_confirmations_job.rb
  config/cron_jobs.rb
Labels: operations

#3519 Set preferred DB backup window
  terraform/app/rds.tf
Labels: infrastructure

#3516 Add vaccine code column to CarePlus vaccination reports
  app/lib/reports/careplus_exporter.rb
  spec/lib/reports/careplus_exporter_spec.rb
  spec/lib/reports/programme_vaccinations_exporter_spec.rb
Labels: feature

#3518 Ensure patients who don't need triage are hidden
  app/controllers/sessions/triage_controller.rb
  spec/features/triage_spec.rb
Labels: bug

#3522 Triage from vaccination history requires consent
  app/models/patient/triage_status.rb
  spec/features/triage_partially_vaccinated_spec.rb
  spec/models/patient/triage_status_spec.rb
Labels: bug

#3473 Optimise offline session exporter
  app/lib/reports/offline_session_exporter.rb
Labels: performance

#3527 Fix continuous deployment
  .github/workflows/continuous-deployment.yml
Labels: github_actions

#3365 Log queries in dev reset endpoint
  app/controllers/concerns/dev_concern.rb
  app/controllers/dev/random_consent_form_controller.rb
  app/controllers/dev/reset_controller.rb
  app/controllers/dev/reset_organisation_controller.rb
  app/controllers/dev_controller.rb
  config/routes.rb
  spec/controllers/dev/reset_organisation_controller_spec.rb
  spec/features/dev_reset_organisation_spec.rb
  spec/spec_helper.rb
Labels: feature

#3480 Add phone instructions for organisations and teams
  app/helpers/phone_helper.rb
  app/lib/govuk_notify_personalisation.rb
  app/models/organisation.rb
  app/models/team.rb
  app/views/organisations/show.html.erb
  app/views/parent_interface/consent_forms/cannot_consent_responsibility.html.erb
  db/migrate/20250429081203_add_phone_instructions_to_organisations_and_teams.rb
  db/schema.rb
  spec/factories/organisations.rb
  spec/factories/teams.rb
  spec/fixtures/files/onboarding/valid.yaml
  spec/helpers/phone_helper_spec.rb
  spec/lib/govuk_notify_personalisation_spec.rb
  spec/models/onboarding_spec.rb
  spec/models/organisation_spec.rb
  spec/models/team_spec.rb
Labels: feature

#3530 Fix alignment of filters with results
  app/assets/stylesheets/_grid.scss
Labels: bug, design tweak

#3542 Use reading width for school moves introduction
  app/views/school_moves/index.html.erb
Labels: design tweak

#3543 Set batch name length limit to 100 when importing
  app/models/immunisation_import_row.rb
  spec/models/immunisation_import_row_spec.rb
Labels: bug

#3546 Trim the timestamps being sent to Splunk
  config/initializers/semantic_logger.rb
Labels: bug

#3514 Deadline passed
  app/controllers/parent_interface/consent_forms/base_controller.rb
  app/controllers/parent_interface/consent_forms_controller.rb
  spec/features/parental_consent_closed_spec.rb
Labels: bug

#3547 Allow changing consent response from child to parent
  app/models/draft_consent.rb
  spec/features/self_consent_spec.rb
Labels: bug

#3478 Updates to the data generators
  lib/generate/cohort_imports.rb
  lib/generate/consents.rb
  lib/generate/vaccination_records.rb
  spec/factories/locations.rb
  spec/factories/patients.rb
  spec/lib/generate/cohort_imports_spec.rb
Labels: refactor, performance

#3549 Use inputs.git-sha to checkout out code for build
  .github/workflows/build-and-push-image.yml
  .github/workflows/deploy.yml
Labels: github_actions

#3553 Bugfix: sort cohorts index in all cases
  app/controllers/cohorts_controller.rb
  app/views/cohorts/index.html.erb
  spec/features/cohorts_index_spec.rb
Labels: bug

#3550 Fix team phone formatting for Notify
  app/lib/govuk_notify_personalisation.rb
  spec/lib/govuk_notify_personalisation_spec.rb
Labels: design tweak

#3445 Don't show today's date in session reminder
  app/components/app_programme_session_table_component.html.erb
  app/controllers/sessions/invite_to_clinic_controller.rb
  app/jobs/send_clinic_initial_invitations_job.rb
  app/jobs/send_clinic_subsequent_invitations_job.rb
  app/lib/govuk_notify_personalisation.rb
  app/models/session.rb
  app/views/sessions/invite_to_clinic/edit.html.erb
  spec/lib/govuk_notify_personalisation_spec.rb
Labels: bug

#3510 Remove report_gillick_notify_parents feature flag
  app/lib/reports/programme_vaccinations_exporter.rb
  config/feature_flags.yml
  spec/lib/reports/programme_vaccinations_exporter_spec.rb
Labels: refactor

#3552 Upgrade to NHS.UK Frontend v9.5
  app/assets/stylesheets/_action_list.scss
  app/assets/stylesheets/_add_another.scss
  app/assets/stylesheets/_autocomplete.scss
  app/assets/stylesheets/_button-group.scss
  app/assets/stylesheets/_button.scss
  app/assets/stylesheets/_card.scss
  app/assets/stylesheets/_count.scss
  app/assets/stylesheets/_dev-tools.scss
  app/assets/stylesheets/_environment.scss
  app/assets/stylesheets/_file-upload.scss
  app/assets/stylesheets/_filters.scss
  app/assets/stylesheets/_globals.scss
  app/assets/stylesheets/_grid.scss
  app/assets/stylesheets/_header.scss
  app/assets/stylesheets/_heading-group.scss
  app/assets/stylesheets/_offline.scss
  app/assets/stylesheets/_overrides.scss
  app/assets/stylesheets/_password-input.scss
  app/assets/stylesheets/_search-input.scss
  app/assets/stylesheets/_secondary-navigation.scss
  app/assets/stylesheets/_status.scss
  app/assets/stylesheets/_summary-list.scss
  app/assets/stylesheets/_table.scss
  app/assets/stylesheets/_tabs.scss
  app/assets/stylesheets/_tag.scss
  app/assets/stylesheets/_typography.scss
  app/assets/stylesheets/_utilities.scss
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/helpers/_link.scss
  app/components/app_consent_component.html.erb
  app/components/app_patient_page_component.html.erb
  app/components/app_patient_session_search_result_card_component.rb
  app/components/app_search_component.rb
  app/views/cohorts/index.html.erb
  app/views/consent_forms/search.html.erb
  app/views/imports/index.html.erb
  app/views/imports/issues/index.html.erb
  app/views/imports/notices/index.html.erb
  app/views/pages/start.html.erb
  app/views/patients/show.html.erb
  app/views/programmes/patients.html.erb
  app/views/programmes/show.html.erb
  app/views/school_moves/index.html.erb
  app/views/session_dates/show.html.erb
  app/views/sessions/consent/show.html.erb
  app/views/sessions/outcome/show.html.erb
  app/views/sessions/record/show.html.erb
  app/views/sessions/register/show.html.erb
  app/views/sessions/show.html.erb
  app/views/sessions/triage/show.html.erb
  app/views/vaccination_records/index.html.erb
  app/views/vaccination_records/show.html.erb
  app/views/vaccines/index.html.erb
  yarn.lock
Labels: dependencies, design tweak, css

#3449 Create configuration for data replication
  .github/workflows/data-replication-pipeline.yml
  bin/docker-start
  terraform/app/modules/ecs_service/autoscaling.tf
  terraform/app/modules/ecs_service/main.tf
  terraform/app/modules/ecs_service/variables.tf
  terraform/data_replication/README.md
  terraform/data_replication/ecs.tf
  terraform/data_replication/env/production-backend.hcl
  terraform/data_replication/env/production.tfvars
  terraform/data_replication/env/qa-backend.hcl
  terraform/data_replication/env/qa.tfvars
  terraform/data_replication/env/sandbox-alpha-backend.hcl
  terraform/data_replication/env/sandbox-alpha.tfvars
  terraform/data_replication/env/sandbox-beta-backend.hcl
  terraform/data_replication/env/sandbox-beta.tfvars
  terraform/data_replication/env/test-backend.hcl
  terraform/data_replication/env/test.tfvars
  terraform/data_replication/env/training-backend.hcl
  terraform/data_replication/env/training.tfvars
  terraform/data_replication/iam.tf
  terraform/data_replication/main.tf
  terraform/data_replication/network.tf
  terraform/data_replication/outputs.tf
  terraform/data_replication/rds.tf
  terraform/data_replication/variables.tf
  terraform/resources/github_data_replication_actions_policy.json
Labels: operations, infrastructure

#3556 Ensure non-unicode strings aren't normalised
  lib/core_ext/string/normalise_whitespace.rb
  spec/lib/core_ext/string_normalise_whitespace_spec.rb
  spec/lib/csv_parser_spec.rb
Labels: bug

#3557 Ensure programmes are shown in alphabetical order
  app/controllers/programmes_controller.rb
  spec/features/programmes_index_spec.rb
Labels: design tweak

#3558 Generate consent status from submitted at time
  app/components/app_activity_log_component.rb
  app/lib/consent_grouper.rb
  app/models/consent.rb
  app/models/consent_form.rb
  app/models/draft_consent.rb
  db/migrate/20250515173205_add_submitted_at_to_consents.rb
  db/schema.rb
  spec/components/app_activity_log_component_spec.rb
  spec/factories/consents.rb
  spec/jobs/consent_form_matching_job_spec.rb
  spec/models/consent_form_spec.rb
  spec/models/consent_spec.rb
  spec/models/draft_consent_spec.rb
  spec/models/patient/consent_status_spec.rb
Labels: bug

#3560 Normalise whitespace in NHS number
  app/models/patient.rb
  spec/models/patient_spec.rb
Labels: feature

#3563 Generate consent status from submitted at time
  app/components/app_activity_log_component.rb
  app/lib/consent_grouper.rb
  app/models/consent.rb
  app/models/consent_form.rb
  app/models/draft_consent.rb
  db/migrate/20250515173205_add_submitted_at_to_consents.rb
  db/schema.rb
  spec/components/app_activity_log_component_spec.rb
  spec/factories/consents.rb
  spec/jobs/consent_form_matching_job_spec.rb
  spec/models/consent_form_spec.rb
  spec/models/consent_spec.rb
  spec/models/draft_consent_spec.rb
  spec/models/patient/consent_status_spec.rb
Labels: bug

#3578 Enable autoscaling on all environments
  terraform/app/env/preview.tfvars
  terraform/app/env/production.tfvars
  terraform/app/env/test.tfvars
  terraform/app/env/training.tfvars
Labels: infrastructure

#3579 Create ADR for autoscaling decisions
  adr/00010-autoscaling-for-ecs.md
Labels: documentation

#3584 Fix check for running deployments script
  terraform/scripts/check-for-running-deployments.sh
Labels: bug, github_actions

#3131 Add Terraform backup module
  .github/workflows/deploy-backup-infrastructure.yml
  terraform/app/env/production.tfvars
  terraform/app/rds.tf
  terraform/app/variables.tf
  terraform/backup/README.md
  terraform/backup/aws-backup-policy.json
  terraform/backup/destination-bootstrap/README.md
  terraform/backup/destination-bootstrap/main.tf
  terraform/backup/destination-bootstrap/outputs.tf
  terraform/backup/destination-bootstrap/variables.tf
  terraform/backup/destination/env/development-backend.hcl
  terraform/backup/destination/env/development.tfvars
  terraform/backup/destination/env/production-backend.hcl
  terraform/backup/destination/env/production.tfvars
  terraform/backup/destination/main.tf
  terraform/backup/destination/outputs.tf
  terraform/backup/destination/variables.tf
  terraform/backup/source/env/development-backend.hcl
  terraform/backup/source/env/development.tfvars
  terraform/backup/source/env/production-backend.hcl
  terraform/backup/source/env/production.tfvars
  terraform/backup/source/main.tf
  terraform/backup/source/outputs.tf
  terraform/backup/source/variables.tf
  terraform/modules/s3/README.md
  terraform/modules/s3/main.tf
  terraform/modules/s3/outputs.tf
  terraform/modules/s3/variables.tf
Labels: infrastructure

#3599 Rename `data-qa` to `data-testid`
  app/components/app_import_errors_component.rb
  app/views/parent_interface/consent_forms/edit/confirm_school.html.erb
Labels: refactor

#3601 Add `aria-label` to new batch buttons
  app/views/vaccines/index.html.erb
  tests/accessibility.spec.ts
Labels: design tweak

#3611 Add custom policy for data replication access
  terraform/account/README.md
  terraform/account/env/development-backend.hcl
  terraform/account/env/production-backend.hcl
  terraform/account/main.tf
  terraform/account/outputs.tf
  terraform/account/variables.tf
Labels: operations, infrastructure

#3607 Remove unnecessary update! call in PendingChangesConcern
  app/models/concerns/pending_changes_concern.rb
  spec/models/concerns/pending_changes_concern_spec.rb
  spec/models/patient_spec.rb
Labels: performance

#3604 Policy version sync
  .github/workflows/deploy-infrastructure.yml
  terraform/scripts/update-github-actions-policy.sh
  terraform/scripts/validate-github-actions-policy.sh
Labels: infrastructure

#3608 Fix: prevent incorrect data merging for twins during patient import
  app/models/patient_import_row.rb
  spec/factories/patients.rb
  spec/features/import_child_records_with_duplicates_spec.rb
  spec/fixtures/class_import/valid.csv
  spec/models/class_import_spec.rb
Labels: bug

#3602 Add basic API endpoints to be used in testing
  app/controllers/api/locations_controller.rb
  app/controllers/api/onboard_controller.rb
  app/models/location.rb
  app/models/onboarding.rb
  config/routes.rb
  docs/api.md
  spec/models/location_spec.rb
  spec/requests/api/locations_spec.rb
  spec/requests/api/onboard_spec.rb
Labels: feature

#3625 Update terraform version
  .github/workflows/data-replication-pipeline.yml
  .github/workflows/deploy-application.yml
  .github/workflows/deploy-backup-infrastructure.yml
  .github/workflows/deploy-infrastructure.yml
  .github/workflows/destroy-infrastructure.yml
  .github/workflows/test.yml
  .tool-versions
  terraform/account/main.tf
  terraform/app/main.tf
  terraform/app/modules/dns/main.tf
  terraform/app/modules/ecs_service/main.tf
  terraform/app/modules/vpc_endpoint/main.tf
  terraform/backup/destination-bootstrap/main.tf
  terraform/backup/destination/main.tf
  terraform/backup/source/main.tf
  terraform/bootstrap/main.tf
  terraform/data_replication/main.tf
Labels: infrastructure

#3626 Move `/dev/reset/:ods_code` endpoint
  app/controllers/api/base_controller.rb
  app/controllers/api/locations_controller.rb
  app/controllers/api/onboard_controller.rb
  app/controllers/api/organisations_controller.rb
  app/controllers/dev/reset_organisation_controller.rb
  config/feature_flags.yml
  config/routes.rb
  docs/api.md
  spec/controllers/api/organisations_controller_spec.rb
  spec/requests/api/locations_spec.rb
  spec/requests/api/onboard_spec.rb
Labels: refactor
