Repository nhsuk/manage-vaccinations-in-schools, pull requests merged in 2025-10, with the labels that each got.

#3559 TimelineRecords UI
  app/components/app_timeline_component.rb
  app/components/app_timeline_filter_component.html.erb
  app/components/app_timeline_filter_component.rb
  app/controllers/inspect/timeline/patients_controller.rb
  app/views/inspect/timeline/patients/show.html.erb
  config/routes.rb
  lib/timeline_records.rb
  spec/features/timeline_records_spec.rb
  spec/lib/timeline_records_spec.rb
Labels: operations

#4304 Add CIS2 authentication for ops tooling
  app/components/app_timeline_filter_component.html.erb
  app/components/app_timeline_filter_component.rb
  app/controllers/concerns/authentication_concern.rb
  app/controllers/inspect/dashboard_controller.rb
  app/controllers/inspect/graphs_controller.rb
  app/controllers/inspect/timeline/patients_controller.rb
  app/models/cis2_info.rb
  app/models/user.rb
  app/views/inspect/dashboard/index.html.erb
  app/views/inspect/graphs/show.html.erb
  app/views/inspect/timeline/patients/show.html.erb
  config/routes.rb
  db/seeds.rb
  spec/factories/users.rb
  spec/features/graph_records_spec.rb
  spec/features/timeline_records_spec.rb
  spec/features/user_cis2_authentication_inspect_non_support_spec.rb
  spec/features/user_cis2_authentication_inspect_support_no_pii_spec.rb
  spec/features/user_cis2_authentication_inspect_support_with_pii_spec.rb
  spec/models/user_spec.rb
Labels: operations

#4783 Ops tools
  app/components/app_timeline_component.rb
  app/components/app_timeline_filter_component.html.erb
  app/components/app_timeline_filter_component.rb
  app/controllers/concerns/authentication_concern.rb
  app/controllers/concerns/inspect_authentication_concern.rb
  app/controllers/inspect/dashboard_controller.rb
  app/controllers/inspect/graphs_controller.rb
  app/controllers/inspect/timeline/patients_controller.rb
  app/models/access_log_entry.rb
  app/models/cis2_info.rb
  app/models/user.rb
  app/views/inspect/dashboard/index.html.erb
  app/views/inspect/graphs/show.html.erb
  app/views/inspect/timeline/patients/show.html.erb
  config/feature_flags.yml
  config/routes.rb
  db/migrate/20250926113321_add_request_details_to_access_log_entry.rb
  db/schema.rb
  db/seeds.rb
  lib/graph_records.rb
  lib/timeline_records.rb
  spec/controllers/concerns/inspect_authentication_concern_spec.rb
  spec/factories/access_log_entries.rb
  spec/factories/users.rb
  spec/features/identity_check_spec.rb
  spec/features/inspect_graph_pii_access_logging_spec.rb
  spec/features/inspect_timeline_pii_access_logging_spec.rb
  spec/features/user_cis2_authentication_inspect_non_support_spec.rb
  spec/features/user_cis2_authentication_inspect_support_no_pii_spec.rb
  spec/features/user_cis2_authentication_inspect_support_with_pii_spec.rb
  spec/lib/graph_records_spec.rb
  spec/lib/timeline_records_spec.rb
  spec/models/access_log_entry_spec.rb
  spec/models/user_spec.rb
Labels: operations, feature

#4795 Move `TimelineRecords` and `GraphRecords`
  .rubocop.yml
  app/lib/graph_records.rb
  app/lib/timeline_records.rb
  lib/graph_records.rb
Labels: refactor

#4781 Replace codedeploy with ecs
  .github/workflows/deploy-application.yml
  terraform/app/codedeploy.tf
  terraform/app/ecs.tf
  terraform/app/iam.tf
  terraform/app/iam_policy_documents.tf
  terraform/app/loadbalancer.tf
  terraform/app/modules/ecs_service/main.tf
  terraform/app/modules/ecs_service/variables.tf
  terraform/app/outputs.tf
  terraform/app/variables.tf
Labels: infrastructure

#4796 Fix issue saving session dates
  app/controllers/draft_sessions_controller.rb
  spec/features/manage_school_sessions_spec.rb
Labels: bug

#4804 Add `Delegatable` concern
  app/models/concerns/delegatable.rb
  app/models/draft_session.rb
  app/models/session.rb
Labels: refactor

#4808 App_version was not picking up passed values
  .github/workflows/deploy-application.yml
Labels: bug, infrastructure

#4818 Put "Still to vaccinate" filter under tallying feature flag
  app/components/app_patient_search_form_component.rb
Labels: bug

#4822 Active Load balancer target groups
  terraform/app/env/preview.tfvars
  terraform/app/env/production.tfvars
  terraform/app/env/training.tfvars
Labels: infrastructure

#4809 Allow `GovukNotifyPersonalisation` to handle `session = nil`
  app/controllers/concerns/vaccination_mailer_concern.rb
  app/lib/already_had_notification_sender.rb
  app/lib/govuk_notify_personalisation.rb
  app/lib/notification_parent_selector.rb
  spec/lib/already_had_notification_sender_spec.rb
  spec/lib/govuk_notify_personalisation_spec.rb
  spec/lib/notification_parent_selector_spec.rb
Labels: bug

#4831 Rename `wait_for_jobs_to_finish`
  spec/jobs/pds_cascading_search_job_spec.rb
  spec/support/imports_helper.rb
Labels: refactor
