Repository nhsuk/manage-vaccinations-in-schools, pull requests merged in 2025-06, with the labels that each got.

#3623 Query full subset of year groups
  app/controllers/api/locations_controller.rb
  spec/requests/api/locations_spec.rb
Labels: bug

#3630 Update permissions for preview
  .github/workflows/deploy-infrastructure.yml
Labels: github_actions

#3645 Update terraform version in S3 module
  terraform/modules/s3/main.tf
Labels: infrastructure

#3531 Hide "Contains gelatine" reason when not valid
  app/components/app_consent_refused_table_component.html.erb
  app/components/app_consent_refused_table_component.rb
  app/models/concerns/gelatine_vaccines_concern.rb
  app/models/consent_form.rb
  app/models/programme.rb
  app/views/parent_interface/consent_forms/edit/reason.html.erb
  app/views/programmes/show.html.erb
  spec/components/app_consent_refused_table_component_spec.rb
  spec/models/consent_form_spec.rb
  spec/models/programme_spec.rb
  spec/models/vaccine_spec.rb
Labels: refactor, design tweak

#3548 Deduplicate health answers with followups
  app/lib/health_answers_deduplicator.rb
  app/models/consent_form.rb
  spec/features/parental_consent_change_answers_spec.rb
  spec/features/parental_consent_flu_spec.rb
  spec/lib/health_answers_deduplicator_spec.rb
Labels: feature

#3523 Persist filters, per user, per view, per browser session
  app/components/app_search_component.rb
  app/controllers/concerns/search_form_concern.rb
  app/forms/search_form.rb
  spec/features/filter_state_persistence_spec.rb
  spec/forms/search_form_spec.rb
Labels: feature

#3647 Allow editing parent contact details
  app/controllers/parent_relationships_controller.rb
  app/views/parent_relationships/edit.html.erb
  config/locales/en.yml
  spec/features/edit_parent_spec.rb
Labels: feature

#3650 Add content for parent relationship type validation
  config/locales/en.yml
Labels: bug

#3659 Update certificates for training
  terraform/app/env/training.tfvars
Labels: infrastructure

#3661 Fix version number display in production
  .github/workflows/build-and-push-image.yml
  .github/workflows/deploy-infrastructure.yml
  .github/workflows/deploy.yml
  config/initializers/version.rb
  terraform/app/variables.tf
Labels: bug

#3670 Use NHS secondary button style
  app/components/app_search_component.rb
Labels: design tweak

#3253 Update change link for parents in consent journey
  app/models/draft_consent.rb
  app/views/draft_consents/confirm.html.erb
  app/views/draft_consents/parent_details.html.erb
  spec/features/verbal_consent_change_answers_spec.rb
Labels: bug

#3674 Remove contact injection wizard step
  app/components/app_consent_confirmation_component.rb
  app/controllers/concerns/consent_form_mailer_concern.rb
  app/controllers/parent_interface/consent_forms/edit_controller.rb
  app/models/consent_form.rb
  app/views/parent_interface/consent_forms/confirm.html.erb
  app/views/parent_interface/consent_forms/edit/injection.html.erb
  config/initializers/govuk_notify.rb
  config/locales/en.yml
  db/migrate/20250606070424_remove_contact_injection_from_consent_forms.rb
  db/schema.rb
  spec/controllers/concerns/consent_form_mailer_concern_spec.rb
  spec/factories/consent_forms.rb
  spec/features/parental_consent_change_answers_spec.rb
  spec/models/consent_form_spec.rb
Labels: refactor

#3582 Ensure dates are deserialized with time zone
  app/models/concerns/request_session_persistable.rb
  spec/models/concerns/request_session_persistable_spec.rb
Labels: bug

#3541 Stop requesting triage for already vaccinated patients
  app/controllers/draft_vaccination_records_controller.rb
  app/models/patient/triage_status.rb
  app/models/vaccination_record.rb
  spec/features/td_ipv_already_had_spec.rb
  spec/models/patient/triage_status_spec.rb
Labels: bug

#3359 Simplify patient-organisation relationship
  app/components/app_patient_cohort_table_component.html.erb
  app/components/app_patient_cohort_table_component.rb
  app/controllers/api/organisations_controller.rb
  app/controllers/cohorts_controller.rb
  app/controllers/patients/edit_controller.rb
  app/controllers/patients_controller.rb
  app/lib/patient_merger.rb
  app/lib/reports/school_moves_exporter.rb
  app/models/organisation.rb
  app/models/patient.rb
  app/models/patient_import.rb
  app/models/patient_import_row.rb
  app/models/school_move.rb
  app/policies/patient_policy.rb
  app/views/patients/show.html.erb
  db/migrate/20250408195356_remove_organisation_from_patient.rb
  db/schema.rb
  db/seeds.rb
  spec/components/app_patient_cohort_table_component_spec.rb
  spec/components/app_patient_table_component_spec.rb
  spec/components/app_vaccination_record_table_component_spec.rb
  spec/factories/patients.rb
  spec/features/cohorts_index_spec.rb
  spec/features/edit_parent_spec.rb
  spec/features/import_child_records_with_duplicates_spec.rb
  spec/features/import_class_lists_with_duplicates_spec.rb
  spec/features/manage_children_spec.rb
  spec/features/parent_relationships_spec.rb
  spec/lib/patient_merger_spec.rb
  spec/lib/reports/school_moves_exporter_spec.rb
  spec/models/class_import_spec.rb
  spec/models/cohort_import_spec.rb
  spec/models/immunisation_import_row_spec.rb
  spec/models/patient_spec.rb
  spec/models/school_move_export_spec.rb
  spec/models/school_move_spec.rb
  spec/policies/patient_policy_spec.rb
Labels: refactor

#3622 Add rake task to transfer school data
  lib/tasks/schools.rake
  spec/lib/tasks/schools_rake_spec.rb
Labels: operations

#3679 Allow testing Flu programme
  app/components/app_vaccinate_form_component.html.erb
  app/components/app_vaccinate_form_component.rb
  app/components/app_vaccination_record_summary_component.rb
  app/controllers/draft_vaccination_records_controller.rb
  app/models/programme.rb
  app/models/vaccine.rb
  db/seeds.rb
  spec/components/app_vaccinate_form_component_spec.rb
  spec/factories/programmes.rb
  spec/factories/vaccination_records.rb
  spec/models/programme_spec.rb
  spec/models/vaccine_spec.rb
Labels: refactor

#3678 Add Flu vaccine health questions
  app/models/programme.rb
  lib/tasks/vaccines.rake
Labels: feature

#3677 Ensure duplicate patients aren't shown
  app/policies/patient_policy.rb
  spec/policies/patient_policy_spec.rb
Labels: bug

#3681 Add full dose or half dose step
  app/components/app_vaccination_record_summary_component.rb
  app/controllers/draft_vaccination_records_controller.rb
  app/forms/vaccinate_form.rb
  app/models/draft_vaccination_record.rb
  app/models/vaccine.rb
  app/views/draft_vaccination_records/confirm.html.erb
  app/views/draft_vaccination_records/dose.html.erb
  config/locales/en.yml
  config/locales/helpers.en.yml
  spec/models/draft_vaccination_record_spec.rb
  spec/models/vaccine_spec.rb
Labels: feature

#3691 Validate `DraftVaccinationRecord` `notes` length
  app/models/draft_vaccination_record.rb
  config/locales/en.yml
  spec/models/draft_vaccination_record_spec.rb
Labels: bug

#3687 Add GIAS download command to deployed envs
  Gemfile
  app/lib/mavis_cli.rb
  app/lib/mavis_cli/gias/download.rb
  lib/tasks/schools.rake
Labels: operations

#3711 Save parent relationship when editing consent
  app/controllers/draft_consents_controller.rb
  app/models/consent.rb
  app/models/draft_consent.rb
  spec/features/verbal_consent_change_answers_spec.rb
Labels: bug

#3719 Save parent relationship when editing consent
  app/models/draft_consent.rb
  spec/features/verbal_consent_change_answers_spec.rb
Labels: bug

#3707 Add `UnsupportedProgramme` exception
  app/lib/programme_grouper.rb
  app/lib/unsupported_programme.rb
  lib/tasks/vaccines.rake
Labels: refactor

#3493 Redesign pre-screening questions
  app/components/app_patient_page_component.rb
  app/components/app_vaccinate_form_component.html.erb
  app/controllers/patient_sessions/vaccinations_controller.rb
  app/forms/vaccinate_form.rb
  app/models/pre_screening.rb
  app/models/session_date.rb
  config/locales/en.yml
  config/locales/helpers.en.yml
  db/migrate/20250505193919_remove_from_pre_screenings.rb
  db/schema.rb
  spec/components/app_activity_log_component_spec.rb
  spec/components/app_patient_page_component_spec.rb
  spec/components/app_triage_notes_component_spec.rb
  spec/controllers/api/organisations_controller_spec.rb
  spec/factories/pre_screenings.rb
  spec/features/doubles_vaccination_administered_spec.rb
  spec/features/e2e_journey_spec.rb
  spec/features/hpv_vaccination_administered_spec.rb
  spec/features/hpv_vaccination_already_had_spec.rb
  spec/features/hpv_vaccination_clinic_spec.rb
  spec/features/hpv_vaccination_delayed_spec.rb
  spec/features/hpv_vaccination_pre_screening_spec.rb
  spec/features/menacwy_vaccination_administered_spec.rb
  spec/features/pre_screening_spec.rb
  spec/features/td_ipv_vaccination_administered_spec.rb
  spec/features/vaccination_todays_batch_spec.rb
  spec/lib/patient_merger_spec.rb
  spec/models/pre_screening_spec.rb
Labels: feature

#3722 Start of follow up questions shouldn't trigger triage
  app/helpers/consent_forms_helper.rb
  app/models/consent.rb
  app/models/consent_form.rb
  app/models/health_answer.rb
  spec/models/consent_form_spec.rb
Labels: design tweak

#3701 Remove broken component previews
  spec/components/previews/app_activity_log_component_preview.rb
  spec/components/previews/app_consent_component_preview.rb
  spec/components/previews/app_consent_form_summary_component_preview.rb
  spec/components/previews/app_health_questions_component_preview.rb
  spec/components/previews/app_outcome_banner_component_preview.rb
  spec/components/previews/app_simple_status_banner_component_preview.rb
Labels: refactor

#3690 Small improvements to `hk` configuration
  .gitignore
  .tool-versions
  hk.pkl
  lib/tasks/vaccines.rake
Labels: refactor

#3724 Make `AddResponseToConsentFormProgrammes` reversible
  db/migrate/20250605084740_add_response_to_consent_form_programmes.rb
Labels: data consistency

#3689 Remove unique index constraint from sessions
  app/models/session.rb
  db/migrate/20250609112437_remove_unique_index_from_sessions.rb
  db/schema.rb
  spec/factories/sessions.rb
  spec/models/session_spec.rb
Labels: data consistency

#3673 Store vaccine methods on consent forms
  Gemfile
  Gemfile.lock
  app/controllers/patient_sessions/consents_controller.rb
  app/models/concerns/has_vaccine_methods.rb
  app/models/consent.rb
  app/models/consent_form.rb
  app/models/consent_form_programme.rb
  app/models/draft_consent.rb
  db/migrate/20250606083902_add_vaccine_methods_to_consent_and_consent_forms.rb
  db/schema.rb
  spec/factories/consent_form_programmes.rb
  spec/factories/consent_forms.rb
  spec/factories/consents.rb
  spec/models/consent_spec.rb
Labels: refactor

#3682 Add Flu vaccination method question to online consent
  app/controllers/parent_interface/consent_forms/edit_controller.rb
  app/models/consent_form.rb
  app/models/consent_form_programme.rb
  app/views/parent_interface/consent_forms/confirm.html.erb
  app/views/parent_interface/consent_forms/edit/consent.html.erb
  app/views/parent_interface/consent_forms/edit/injection_alternative.html.erb
  app/views/parent_interface/consent_forms/edit/response_doubles.html.erb
  app/views/parent_interface/consent_forms/edit/response_flu.html.erb
  app/views/parent_interface/consent_forms/edit/response_hpv.html.erb
  app/views/parent_interface/consent_forms/start.html.erb
  app/views/parent_interface/consent_forms/start/_flu.html.erb
  app/views/parent_interface/consent_forms/start/_hpv.html.erb
  app/views/parent_interface/consent_forms/start/_menacwy.html.erb
  app/views/parent_interface/consent_forms/start/_td_ipv.html.erb
  config/locales/en.yml
  lib/tasks/vaccines.rake
  spec/features/parental_consent_change_answers_spec.rb
  spec/features/parental_consent_doubles_spec.rb
  spec/features/parental_consent_flu_spec.rb
  spec/models/consent_form_spec.rb
Labels: feature

#3742 Various updates to Dependabot configuration
  .github/dependabot.yml
Labels: operations, refactor

#3680 Vary vaccination flow depending on consented vaccination method
  app/components/app_vaccinate_form_component.rb
  app/models/patient/consent_status.rb
  db/migrate/20250608172900_add_vaccine_methods_to_consent_statuses.rb
  db/schema.rb
  spec/components/app_vaccinate_form_component_spec.rb
  spec/factories/consents.rb
  spec/factories/patient_consent_statuses.rb
  spec/models/patient/consent_status_spec.rb
Labels: feature

#3717 Various accessibility updates to vaccines page
  app/components/app_card_component.rb
  app/views/vaccines/index.html.erb
  spec/components/app_card_component_spec.rb
Labels: design tweak

#3751 Don't add answers without a response
  app/models/consolidated_health_answers.rb
  spec/models/consolidated_health_answers_spec.rb
Labels: bug

#3656 Add notes to patients
  app/components/app_activity_log_component.rb
  app/components/app_create_note_component.rb
  app/components/app_log_event_component.rb
  app/components/app_patient_session_search_result_card_component.rb
  app/controllers/patient_sessions/activities_controller.rb
  app/controllers/sessions/consent_controller.rb
  app/controllers/sessions/outcome_controller.rb
  app/controllers/sessions/record_controller.rb
  app/controllers/sessions/register_controller.rb
  app/controllers/sessions/triage_controller.rb
  app/models/note.rb
  app/models/patient.rb
  app/models/patient_session.rb
  app/models/session.rb
  app/views/patient_sessions/_header.html.erb
  app/views/patient_sessions/activities/show.html.erb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20250604122111_create_notes.rb
  db/schema.rb
  spec/components/app_activity_log_component_spec.rb
  spec/components/app_create_note_component_spec.rb
  spec/components/app_patient_session_search_result_card_component_spec.rb
  spec/factories/notes.rb
  spec/features/access_log_spec.rb
  spec/features/delete_vaccination_record_spec.rb
  spec/features/e2e_journey_spec.rb
  spec/features/manage_attendance_spec.rb
  spec/features/parental_consent_manual_matching_spec.rb
  spec/features/parental_consent_send_request_spec.rb
  spec/features/parental_consent_spec.rb
  spec/features/self_consent_spec.rb
  spec/models/note_spec.rb
  spec/models/patient_session_spec.rb
  spec/requests/patient_sessions/activity_spec.rb
  spec/spec_helper.rb
  spec/support/cis2_auth_helper.rb
Labels: feature

#3703 Migrate json columns to jsonb type
  app/models/class_import.rb
  db/migrate/20250610154510_change_class_import_serialized_errors_to_jsonb.rb
  db/schema.rb
  spec/factories/class_imports.rb
  spec/models/class_import_spec.rb
Labels: data consistency

#3718 Choose vaccine method when triaging
  app/components/app_patient_session_triage_component.html.erb
  app/components/app_patient_session_triage_component.rb
  app/components/app_triage_form_component.html.erb
  app/components/app_triage_form_component.rb
  app/controllers/draft_consents_controller.rb
  app/controllers/patient_sessions/triages_controller.rb
  app/forms/triage_form.rb
  app/models/draft_consent.rb
  app/models/programme.rb
  app/models/triage.rb
  app/views/draft_consents/triage.html.erb
  app/views/patient_sessions/programmes/show.html.erb
  app/views/patient_sessions/triages/new.html.erb
  config/locales/en.yml
  config/locales/helpers.en.yml
  db/migrate/20250612083140_add_vaccine_method_to_triages.rb
  db/schema.rb
  spec/components/app_patient_session_triage_component_spec.rb
  spec/components/app_triage_form_component_spec.rb
  spec/factories/triage.rb
  spec/forms/triage_form_spec.rb
  spec/models/draft_consent_spec.rb
  spec/models/triage_spec.rb
Labels: feature

#3800 Specify final snapshot name
  terraform/app/rds.tf
  terraform/app/variables.tf
Labels: infrastructure

#3798 Fix data replication deployment
  .github/workflows/data-replication-pipeline.yml
  terraform/account/resources/iam_policy_DeployDataReplicationResources.json
  terraform/account/resources/iam_policy_DeployMavisResources.json
Labels: infrastructure

#3819 Change triage options text
  app/components/app_triage_form_component.rb
  app/forms/triage_form.rb
  config/locales/helpers.en.yml
  spec/components/app_triage_form_component_spec.rb
Labels: feature

#3822 Reduce frequency of secret rotation
  terraform/app/rds.tf
Labels: infrastructure

#3520 Redirect users back to the patient after triage
  app/controllers/patient_sessions/triages_controller.rb
  spec/features/triage_delay_vaccination_spec.rb
  spec/features/triage_spec.rb
  spec/features/triage_then_parental_consent_refused_spec.rb
Labels: feature

#3843 Fix data replication policy
  terraform/account/resources/iam_policy_DeployDataReplicationResources.json
Labels: infrastructure

#3765 Add ability to filter on vaccine method
  app/components/app_search_component.rb
  app/controllers/concerns/search_form_concern.rb
  app/controllers/sessions/record_controller.rb
  app/forms/search_form.rb
  app/models/patient/consent_status.rb
  app/models/patient_session.rb
  app/models/programme.rb
  app/models/session.rb
  app/views/sessions/record/show.html.erb
  spec/forms/search_form_spec.rb
  spec/models/programme_spec.rb
  spec/models/session_spec.rb
Labels: feature

#3760 Update online consent confirmation page for Flu
  app/components/app_consent_confirmation_component.rb
  spec/components/app_consent_confirmation_component_spec.rb
  spec/features/parental_consent_change_answers_spec.rb
Labels: feature
