Repository nhsuk/manage-vaccinations-in-schools, pull requests merged in 2025-07, with the labels that each got.

#3857 Reapply "Reduce frequency of secret rotation"
  terraform/app/rds.tf
Labels: infrastructure

#3867 Fix: year group filters not filtering as expected
  app/models/patient.rb
  spec/features/filtering_by_programme_spec.rb
  spec/forms/search_form_spec.rb
Labels: bug, ruby

#3774 Identity checks
  app/components/app_vaccinate_form_component.html.erb
  app/components/app_vaccination_record_summary_component.rb
  app/controllers/draft_vaccination_records_controller.rb
  app/controllers/patient_sessions/vaccinations_controller.rb
  app/forms/vaccinate_form.rb
  app/helpers/identity_checks_helper.rb
  app/models/draft_vaccination_record.rb
  app/models/identity_check.rb
  app/models/vaccination_record.rb
  app/views/draft_vaccination_records/confirm.html.erb
  app/views/draft_vaccination_records/identity.html.erb
  config/locales/en.yml
  db/migrate/20250618190014_create_identity_checks.rb
  db/schema.rb
  spec/components/app_vaccinate_form_component_spec.rb
  spec/components/app_vaccination_record_summary_component_spec.rb
  spec/factories/identity_checks.rb
  spec/features/community_clinic_vaccination_session_spec.rb
  spec/features/doubles_vaccination_administered_spec.rb
  spec/features/e2e_journey_spec.rb
  spec/features/hpv_vaccination_administered_spec.rb
  spec/features/hpv_vaccination_already_had_spec.rb
  spec/features/hpv_vaccination_clinic_spec.rb
  spec/features/hpv_vaccination_delayed_spec.rb
  spec/features/menacwy_vaccination_administered_spec.rb
  spec/features/pre_screening_spec.rb
  spec/features/td_ipv_vaccination_administered_spec.rb
  spec/features/vaccination_todays_batch_spec.rb
  spec/forms/vaccinate_form_spec.rb
  spec/helpers/identity_checks_helper_spec.rb
  spec/models/identity_check_spec.rb
  spec/models/vaccination_record_spec.rb
Labels: feature

#3786 Hide previous years seasonal vaccinations
  app/components/app_patient_vaccination_table_component.rb
  app/lib/vaccinated_criteria.rb
  app/models/vaccination_record.rb
  spec/components/app_patient_vaccination_table_component_spec.rb
Labels: feature

#3876 Identity check default
  app/components/app_vaccinate_form_component.html.erb
  spec/features/community_clinic_vaccination_session_spec.rb
  spec/features/doubles_vaccination_administered_spec.rb
  spec/features/e2e_journey_spec.rb
  spec/features/flu_vaccination_administered_spec.rb
  spec/features/hpv_vaccination_administered_spec.rb
  spec/features/hpv_vaccination_already_had_spec.rb
  spec/features/hpv_vaccination_clinic_spec.rb
  spec/features/hpv_vaccination_delayed_spec.rb
  spec/features/identity_check_spec.rb
  spec/features/menacwy_vaccination_administered_spec.rb
  spec/features/pre_screening_spec.rb
  spec/features/td_ipv_vaccination_administered_spec.rb
  spec/features/vaccination_todays_batch_spec.rb
Labels: feature, ruby

#3828 Validate DB connection in internal healthcheck
  Dockerfile
  bin/internal_healthcheck
  terraform/app/ecs.tf
  terraform/app/loadbalancer.tf
Labels: infrastructure

#3873 Aws provider version upgrade
  terraform/account/main.tf
  terraform/app/main.tf
  terraform/app/modules/dms/main.tf
  terraform/app/modules/dns/main.tf
  terraform/app/modules/ecs_service/main.tf
  terraform/app/modules/vpc_endpoint/main.tf
  terraform/backup/destination-bootstrap/main.tf
  terraform/backup/destination/main.tf
  terraform/backup/source/main.tf
  terraform/bootstrap/main.tf
  terraform/modules/s3/main.tf
Labels: dependencies, infrastructure

#3785 Add side effects to vaccines
  app/lib/govuk_notify_personalisation.rb
  app/models/concerns/has_side_effects.rb
  app/models/concerns/has_vaccine_methods.rb
  app/models/vaccine.rb
  config/locales/en.yml
  db/migrate/20250619125105_add_side_effects_to_vaccines.rb
  db/schema.rb
  lib/tasks/vaccines.rake
  spec/factories/vaccines.rb
  spec/lib/govuk_notify_personalisation_spec.rb
  spec/models/vaccine_spec.rb
Labels: feature

#3900 Fix flaky search form test
  spec/forms/search_form_spec.rb
Labels: refactor

#3899 Improve Data replication workflow
  .github/workflows/data-replication-pipeline.yml
  terraform/data_replication/rds.tf
Labels: github_actions

#3841 Add job to sync vaccination records upstream to NHS
  app/jobs/sync_vaccination_record_to_nhs_job.rb
  app/lib/mavis_cli.rb
  app/lib/mavis_cli/vaccination_records/sync.rb
  app/lib/nhs/immunisations_api.rb
  app/models/vaccination_record.rb
  config/feature_flags.yml
  db/migrate/20250625212637_add_nhs_immunisations_api_synced_at_to_vaccination_record.rb
  db/migrate/20250630140421_add_nhs_immunisations_api_etag_to_vaccination_record.rb
  db/migrate/20250630144421_add_nhs_immunisations_api_id_to_vaccination_record.rb
  db/schema.rb
  spec/factories/vaccination_records.rb
  spec/features/cli_vaccination_records_sync_spec.rb
  spec/jobs/sync_vaccination_record_to_nhs_job_spec.rb
  spec/lib/nhs/immunisations_api_spec.rb
  spec/models/vaccination_record_spec.rb
Labels: imms-fhir-api

#3896 Send vaccination records to imms api
  app/controllers/draft_vaccination_records_controller.rb
  app/lib/enqueue_sync_vaccination_record_to_nhs.rb
  app/models/immunisation_import.rb
  config/feature_flags.yml
  spec/features/flu_vaccination_administered_spec.rb
  spec/features/hpv_vaccination_administered_spec.rb
  spec/features/menacwy_vaccination_administered_spec.rb
  spec/features/td_ipv_vaccination_administered_spec.rb
  spec/lib/enqueue_sync_vaccination_record_to_nhs_spec.rb
  spec/models/immunisation_import_spec.rb
Labels: imms-fhir-api

#3916 Add `vaccine_is_injection` and `vaccine_is_nasal`
  app/lib/govuk_notify_personalisation.rb
  spec/lib/govuk_notify_personalisation_spec.rb
Labels: feature

#3897 Change activity title to "Added to session ____"
  app/components/app_activity_log_component.rb
  spec/components/app_activity_log_component_spec.rb
  spec/features/manage_children_spec.rb
Labels: design tweak

#3906 Add `has_multiple_dates` personalisation variable
  app/lib/govuk_notify_personalisation.rb
  spec/lib/govuk_notify_personalisation_spec.rb
Labels: feature

#3919 Consolidate vaccination administered texts
  app/controllers/concerns/vaccination_mailer_concern.rb
  config/initializers/govuk_notify.rb
  spec/controllers/concerns/vaccination_mailer_concern_spec.rb
  spec/features/doubles_vaccination_administered_spec.rb
  spec/features/flu_vaccination_administered_spec.rb
  spec/features/hpv_vaccination_administered_spec.rb
  spec/features/hpv_vaccination_clinic_spec.rb
  spec/features/hpv_vaccination_offline_spec.rb
  spec/features/menacwy_vaccination_administered_spec.rb
  spec/features/td_ipv_vaccination_administered_spec.rb
Labels: refactor, design tweak

#3907 Add `can_self_consent` personalisation variable
  app/lib/govuk_notify_personalisation.rb
  spec/lib/govuk_notify_personalisation_spec.rb
Labels: feature

#3921 Remove `programme_name` personalisation variable
  app/lib/govuk_notify_personalisation.rb
  spec/lib/govuk_notify_personalisation_spec.rb
Labels: refactor

#3922 Add `vaccination_and_method` personalisation variable
  app/lib/govuk_notify_personalisation.rb
  spec/lib/govuk_notify_personalisation_spec.rb
Labels: feature

#3924 Add `vaccine` and `vaccine_and_method` personalisation
  app/lib/govuk_notify_personalisation.rb
  spec/lib/govuk_notify_personalisation_spec.rb
Labels: feature

#3918 Make flu vaccination form titles clearer
  app/components/app_patient_session_record_component.rb
  app/components/app_vaccinate_form_component.html.erb
  app/components/app_vaccinate_form_component.rb
  spec/components/app_vaccinate_form_component_spec.rb
  spec/features/flu_vaccination_administered_spec.rb
Labels: feature

#3915 Add flu pre-screening questions
  .github/workflows/lint.yml
  app/components/app_vaccinate_form_component.html.erb
  app/components/app_vaccinate_form_component.rb
  app/forms/vaccinate_form.rb
  spec/features/pre_screening_spec.rb
Labels: feature

#3940 Ensure flu is displayed lowercase in sentences
  app/components/app_consent_confirmation_component.rb
  app/components/app_patient_session_record_component.rb
  app/components/app_patient_session_search_result_card_component.rb
  app/components/app_patient_session_triage_component.html.erb
  app/components/app_session_actions_component.rb
  app/components/app_session_details_summary_component.rb
  app/components/app_vaccinate_form_component.rb
  app/controllers/draft_vaccination_records_controller.rb
  app/models/immunisation_import_row.rb
  app/models/programme.rb
  app/views/draft_vaccination_records/batch.html.erb
  app/views/draft_vaccination_records/date_and_time.html.erb
  app/views/draft_vaccination_records/delivery.html.erb
  app/views/draft_vaccination_records/location.html.erb
  app/views/draft_vaccination_records/outcome.html.erb
  app/views/parent_relationships/destroy.html.erb
  lib/tasks/health_questions.rake
  spec/features/flu_vaccination_administered_spec.rb
  spec/models/programme_spec.rb
Labels: refactor, design tweak

#3941 Refactor methods related to delivery and vaccine methods
  app/components/app_programme_status_tags_component.rb
  app/components/app_triage_form_component.rb
  app/forms/triage_form.rb
  app/helpers/consents_helper.rb
  app/models/draft_vaccination_record.rb
  app/models/programme.rb
  app/models/vaccine.rb
Labels: refactor

#3936 Allow default daily batch per vaccine method
  app/components/app_consent_confirmation_component.rb
  app/components/app_patient_session_record_component.rb
  app/components/app_vaccinate_form_component.rb
  app/controllers/concerns/todays_batch_concern.rb
  app/controllers/patient_sessions/vaccinations_controller.rb
  app/controllers/sessions/record_controller.rb
  app/controllers/vaccines_controller.rb
  app/lib/govuk_notify_personalisation.rb
  app/views/sessions/record/batch.html.erb
  app/views/sessions/record/show.html.erb
  app/views/vaccines/index.html.erb
  app/views/vaccines/show.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/components/app_consent_confirmation_component_spec.rb
  spec/features/parental_consent_change_answers_spec.rb
  spec/features/todays_batch_spec.rb
Labels: bug, feature

#3946 Add `talk_to_your_child_message` personalisation
  app/lib/govuk_notify_personalisation.rb
  spec/lib/govuk_notify_personalisation_spec.rb
Labels: design tweak

#3902 Create CLI tool to generate the FHIR record for a given vaccination record
  app/lib/mavis_cli.rb
  app/lib/mavis_cli/vaccination_records/generate_fhir.rb
  spec/features/cli_vaccination_records_generate_fhir_spec.rb
Labels: imms fhir api

#3901 Add progress bar to the CLI command `mavis generate cohort-imports`
  app/lib/mavis_cli/generate/cohort_imports.rb
  lib/generate/cohort_imports.rb
Labels: operations

#3945 Update vaccination records in the NHS immunisations api
  .prettierignore
  app/jobs/sync_vaccination_record_to_nhs_job.rb
  app/lib/enqueue_sync_vaccination_record_to_nhs.rb
  app/lib/fhir_mapper/vaccination_record.rb
  app/lib/nhs/immunisations_api.rb
  spec/fixtures/fhir/immunisation-create.json
  spec/fixtures/fhir/immunisation-update.json
  spec/jobs/sync_vaccination_record_to_nhs_job_spec.rb
  spec/lib/enqueue_sync_vaccination_record_to_nhs_spec.rb
  spec/lib/fhir_mapper/vaccination_record_spec.rb
  spec/lib/nhs/immunisations_api_spec.rb
Labels: feature, imms fhir api

#3948 Ensure we have names for unused Notify templates
  app/models/notify_log_entry.rb
  config/initializers/govuk_notify.rb
  spec/models/notify_log_entry_spec.rb
Labels: bug

#3955 Filter on patients with approriate vaccine method
  app/controllers/sessions/record_controller.rb
  app/models/patient.rb
  app/models/patient_session.rb
  spec/features/flu_vaccination_administered_spec.rb
  spec/models/patient_session_spec.rb
Labels: bug

#3951 Don't ask full or half dose question by default
  app/controllers/draft_vaccination_records_controller.rb
  app/controllers/patient_sessions/vaccinations_controller.rb
  app/forms/vaccinate_form.rb
  app/models/draft_vaccination_record.rb
  app/models/vaccine.rb
  spec/features/flu_vaccination_administered_spec.rb
  spec/models/vaccine_spec.rb
Labels: bug

#3668 Implement separate email templates for CWPT and other organisations
  app/models/session_notification.rb
  config/initializers/govuk_notify.rb
  spec/models/session_notification_spec.rb
Labels: feature

#3958 Allow recording injection for nasal patients
  app/components/app_vaccinate_form_component.html.erb
  app/components/app_vaccinate_form_component.rb
  app/controllers/patient_sessions/vaccinations_controller.rb
  app/forms/vaccinate_form.rb
  app/models/draft_vaccination_record.rb
  app/models/patient.rb
  app/models/vaccine.rb
  config/locales/en.yml
  spec/features/flu_vaccination_administered_spec.rb
  spec/features/triage_delay_vaccination_spec.rb
  spec/forms/vaccinate_form_spec.rb
Labels: feature

#3960 Show secondary consent vaccine methods
  app/components/app_consent_card_component.rb
  app/components/app_consent_summary_component.rb
  app/helpers/consents_helper.rb
  app/views/patient_sessions/consents/show.html.erb
  spec/components/app_consent_card_component_spec.rb
  spec/components/app_consent_summary_component_spec.rb
  spec/features/self_consent_spec.rb
  spec/features/verbal_consent_given_by_new_parental_contact_spec.rb
  spec/features/verbal_consent_given_spec.rb
  spec/features/verbal_consent_refused_personal_choice_spec.rb
  spec/features/verbal_consent_refused_spec.rb
Labels: design tweak

#3964 Update session reminder text template
  config/initializers/govuk_notify.rb
Labels: design tweak

#3965 Reorder injection alternative question
  app/models/consent_form.rb
  lib/tasks/vaccines.rake
  spec/features/parental_consent_change_answers_spec.rb
  spec/features/parental_consent_flu_spec.rb
Labels: design tweak

#3947 Triage for flu: UI changes
  app/components/app_activity_log_component.rb
  app/components/app_patient_search_result_card_component.rb
  app/components/app_patient_session_search_result_card_component.rb
  app/components/app_patient_session_triage_component.html.erb
  app/components/app_patient_session_triage_component.rb
  app/components/app_triage_form_component.html.erb
  app/components/app_triage_table_component.rb
  app/forms/triage_form.rb
  app/helpers/triages_helper.rb
  config/locales/en.yml
  config/locales/status.en.yml
  spec/components/app_activity_log_component_spec.rb
  spec/features/triage_spec.rb
  spec/features/verbal_consent_given_spec.rb
Labels: feature

#3977 Don't show "Nasal spray (or injection)"
  app/components/app_programme_status_tags_component.rb
  config/locales/en.yml
  spec/components/app_programme_status_tags_component_spec.rb
Labels: design tweak

#3981 Remove the unused MESH integration
  README.md
  app/controllers/vaccination_records_controller.rb
  app/jobs/mesh_dps_export_job.rb
  app/jobs/mesh_track_dps_exports_job.rb
  app/jobs/mesh_validate_mailbox_job.rb
  app/lib/mesh.rb
  app/models/dps_export.rb
  app/models/dps_export_row.rb
  app/models/patient.rb
  app/models/programme.rb
  app/models/vaccination_record.rb
  app/views/vaccination_records/index.html.erb
  config/cron_jobs.rb
  config/environments/production.rb
  config/feature_flags.yml
  config/initializers/inflections.rb
  config/mesh_ca_bundle.pem
  config/routes.rb
  config/settings.yml
  config/settings/development.yml
  config/settings/test.yml
  db/migrate/20250707221458_remove_dps_export_tables.rb
  db/schema.rb
  docs/architecture.adoc
  docs/mesh.md
  lib/tasks/mesh.rake
  spec/factories/dps_exports.rb
  spec/jobs/mesh_dps_export_job_spec.rb
  spec/jobs/mesh_track_dps_exports_job_spec.rb
  spec/jobs/mesh_validate_mailbox_job_spec.rb
  spec/lib/mesh_spec.rb
  spec/models/dps_export_row_spec.rb
  spec/models/dps_export_spec.rb
Labels: refactor, ruby

#3988 Align terraform versions
  terraform/data_replication/main.tf
Labels: infrastructure

#3983 Refactor programme controllers
  app/components/app_patient_vaccination_table_component.html.erb
  app/components/app_programme_navigation_component.rb
  app/components/app_programme_stats_component.html.erb
  app/components/app_vaccination_record_table_component.html.erb
  app/controllers/draft_vaccination_records_controller.rb
  app/controllers/programmes/base_controller.rb
  app/controllers/programmes/cohorts_controller.rb
  app/controllers/programmes/overview_controller.rb
  app/controllers/programmes/patients_controller.rb
  app/controllers/programmes/reports_controller.rb
  app/controllers/programmes/sessions_controller.rb
  app/controllers/programmes/vaccinations_controller.rb
  app/controllers/programmes_controller.rb
  app/controllers/sessions/register_controller.rb
  app/controllers/vaccination_records_controller.rb
  app/controllers/vaccination_reports_controller.rb
  app/views/programmes/cohorts/index.html.erb
  app/views/programmes/cohorts/show.html.erb
  app/views/programmes/index.html.erb
  app/views/programmes/overview/show.html.erb
  app/views/programmes/patients/index.html.erb
  app/views/programmes/sessions/index.html.erb
  app/views/programmes/vaccinations/index.html.erb
  app/views/vaccination_records/destroy.html.erb
  app/views/vaccination_records/show.html.erb
  app/views/vaccination_reports/dates.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/features/download_vaccination_reports_spec.rb
Labels: refactor

#3985 Add after_save hook to sync vaccination
  app/controllers/draft_vaccination_records_controller.rb
  app/models/vaccination_record.rb
  spec/features/hpv_vaccination_offline_spec.rb
  spec/models/concerns/vaccination_record_sync_to_nhs_immunisations_api_concern_spec.rb
  spec/models/vaccination_record_spec.rb
Labels: imms fhir api

#4001 Revert "Pin mise version"
  .github/workflows/lint.yml
Labels: refactor

#4002 Academic year preparation start date
  app/lib/academic_year.rb
  config/settings.yml
  spec/lib/academic_year_spec.rb
  terraform/app/variables.tf
Labels: operations

#4004 Use separate stylesheets for public- and SAIS-facing interfaces
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/components/_index.scss
  app/assets/stylesheets/components/_signed-in.scss
  app/assets/stylesheets/core/settings/_index.scss
  app/assets/stylesheets/public.scss
  app/assets/stylesheets/vendor/govuk-frontend/_public.scss
  app/assets/stylesheets/vendor/govuk-frontend/components/_index.scss
  app/assets/stylesheets/vendor/govuk-frontend/components/password-input/_index.scss
  app/assets/stylesheets/vendor/nhsuk-frontend/core/_index.scss
  app/javascript/controllers/index.js
  app/javascript/controllers/nhsuk_password_input_controller.js
  app/views/layouts/application.html.erb
  app/views/offline_passwords/new.html.erb
  app/views/users/sessions/new.html.erb
  config/initializers/assets.rb
  package.json
Labels: refactor, performance, css

#4006 Add programmes option to `add-to-organisation`
  app/lib/mavis_cli/schools/add_to_organisation.rb
  app/models/location.rb
  docs/api.md
  docs/managing-teams.md
  docs/onboarding.md
  spec/features/cli_schools_add_to_organisation_spec.rb
Labels: operations

#4010 Use aqua-green for registration attending status colour
  app/components/app_register_status_tag_component.rb
  config/locales/status.en.yml
Labels: design tweak

#3970 SystmOne reports for flu
  app/lib/reports/systm_one_exporter.rb
  spec/lib/reports/systm_one_exporter_spec.rb
Labels: operations, feature

#4009 Hide "Get a new consent response" button
  app/components/app_patient_session_consent_component.html.erb
  app/components/app_patient_session_consent_component.rb
  spec/components/app_patient_session_consent_component_spec.rb
Labels: bug

#4018 Ensure `MavisCLI.load_rails` is called
  app/lib/mavis_cli/clinics/add_to_organisation.rb
  app/lib/mavis_cli/clinics/create.rb
  app/lib/mavis_cli/schools/add_programme_year_group.rb
  app/lib/mavis_cli/schools/add_to_organisation.rb
  app/lib/mavis_cli/schools/remove_programme_year_group.rb
Labels: bug

#4026 Enable SystmOne file format for flu
  app/models/vaccination_report.rb
  spec/models/vaccination_report_spec.rb
Labels: operations

#4019 Ensure all changes are staged when recording offline
  app/models/immunisation_import_row.rb
  spec/features/hpv_vaccination_offline_spec.rb
Labels: bug

#4037 Order academic years most recent first
  app/lib/academic_year.rb
  spec/lib/academic_year_spec.rb
Labels: design tweak

#4047 Update flu vaccine products
  config/vaccines.yml
  spec/factories/programmes.rb
  spec/features/todays_batch_spec.rb
  spec/fixtures/immunisation_import/invalid_rows.csv
  spec/fixtures/immunisation_import/valid_flu.csv
  spec/helpers/vaccines_helper_spec.rb
  spec/lib/reports/systm_one_exporter_spec.rb
  spec/models/immunisation_import_row_spec.rb
  spec/models/vaccine_spec.rb
Labels: operations

#4049 Rename feature flag used to enqueue for imms api
  app/models/concerns/vaccination_record_sync_to_nhs_immunisations_api_concern.rb
  config/feature_flags.yml
  spec/features/delete_vaccination_record_spec.rb
  spec/features/edit_vaccination_record_spec.rb
  spec/features/flu_vaccination_administered_spec.rb
  spec/features/hpv_vaccination_administered_spec.rb
  spec/features/hpv_vaccination_offline_spec.rb
  spec/features/manage_children_spec.rb
  spec/features/menacwy_vaccination_administered_spec.rb
  spec/features/td_ipv_vaccination_administered_spec.rb
  spec/lib/patient_merger_spec.rb
  spec/models/concerns/vaccination_record_sync_to_nhs_immunisations_api_concern_spec.rb
  spec/models/immunisation_import_spec.rb
Labels: refactor, imms fhir api

#4050 Add flu procedure codes
  app/lib/fhir_mapper/programme.rb
  app/lib/fhir_mapper/vaccination_record.rb
  app/lib/fhir_mapper/vaccine.rb
  app/lib/reports/programme_vaccinations_exporter.rb
  app/models/programme.rb
  app/models/vaccination_record.rb
  app/models/vaccine.rb
  spec/lib/fhir_mapper/programme_spec.rb
  spec/lib/fhir_mapper/vaccine_spec.rb
  spec/lib/reports/programme_vaccinations_exporter_spec.rb
  spec/models/vaccine_spec.rb
Labels: operations

#4051 Add `AcademicYear#pending`
  app/lib/academic_year.rb
  spec/lib/academic_year_spec.rb
Labels: refactor

#4066 Fix flaky tests
  spec/features/identity_check_spec.rb
  spec/models/organisation_spec.rb
Labels: refactor

#4071 Fix `create_default_programme_year_groups` task
  lib/tasks/create_default_programme_year_groups.rake
Labels: bug

#4069 Increase flu maximum dose sequence
  app/models/programme.rb
  spec/models/programme_spec.rb
Labels: operations

#4034 Ignore delivery site if there's only one
  app/forms/vaccinate_form.rb
  spec/features/flu_vaccination_administered_spec.rb
Labels: bug

#4029 Rename "Community clinics"
  app/lib/generic_clinic_factory.rb
  spec/factories/locations.rb
  spec/features/hpv_vaccination_offline_spec.rb
  spec/features/manage_clinic_sessions_spec.rb
  spec/features/parental_consent_clinic_spec.rb
Labels: design tweak

#3782 Allow sessions to not have registration
  app/components/app_patient_session_record_component.rb
  app/components/app_session_actions_component.rb
  app/controllers/sessions/record_controller.rb
  app/models/session.rb
  app/views/patient_sessions/_header.html.erb
  app/views/sessions/_header.html.erb
  db/migrate/20250717093714_add_requires_registration_field_to_sessions.rb
  db/schema.rb
  spec/components/app_patient_session_record_component_spec.rb
  spec/components/app_session_actions_component_spec.rb
  spec/factories/sessions.rb
  spec/features/hpv_vaccination_administered_spec.rb
  spec/features/manage_attendance_spec.rb
  spec/models/session_spec.rb
Labels: feature

#4072 Remove `create_default_programme_year_groups`
  lib/tasks/create_default_programme_year_groups.rake
Labels: refactor

#4030 Add address to school options in select dropdown
  app/views/draft_class_imports/session.html.erb
Labels: design tweak

#4048 Prevent changing the vaccination record administration date to a different academic year
  app/models/draft_vaccination_record.rb
  config/locales/en.yml
  spec/features/edit_vaccination_record_spec.rb
  spec/models/draft_vaccination_record_spec.rb
Labels: data consistency

#4013 Add administering professional info to SystmOne export
  app/lib/reports/systm_one_exporter.rb
  spec/lib/reports/systm_one_exporter_spec.rb
Labels: feature

#3588 Accept import capitalisation differences during import
  app/models/concerns/pending_changes_concern.rb
  spec/models/class_import_row_spec.rb
  spec/models/class_import_spec.rb
  spec/models/cohort_import_row_spec.rb
  spec/models/cohort_import_spec.rb
  spec/models/immunisation_import_row_spec.rb
Labels: feature

#4079 Ensure duplicate patients aren't shown on cohort pages
  app/controllers/programmes/cohorts_controller.rb
  app/models/organisation.rb
  app/models/programme.rb
  app/views/programmes/cohorts/show.html.erb
  spec/features/cohorts_index_spec.rb
Labels: bug

#4077 Simplify search form query parameters
  app/components/app_patient_search_form_component.rb
  app/components/app_patient_session_search_result_card_component.rb
  app/components/app_session_actions_component.rb
  app/components/app_session_details_summary_component.rb
  app/controllers/concerns/patient_search_form_concern.rb
  app/controllers/sessions/register_controller.rb
Labels: design tweak

#4035 Remove ingress and egress for default security group
  terraform/app/network.tf
Labels: infrastructure, security

#4011 Set ECR lifecycle policy
  terraform/account/main.tf
Labels: infrastructure

#4007 Drop invalid HTTP headers
  terraform/app/loadbalancer.tf
Labels: infrastructure

#3998 Readonly container filesystem
  Dockerfile
  terraform/app/modules/ecs_service/main.tf
Labels: infrastructure

#4068 Show academic year next to year group
  app/components/app_child_summary_component.rb
  app/components/app_patient_search_result_card_component.rb
  app/components/app_patient_session_search_result_card_component.rb
  app/helpers/patients_helper.rb
  app/models/note.rb
  app/models/patient.rb
  app/views/imports/show.html.erb
  app/views/patient_sessions/_header.html.erb
  spec/helpers/cohorts_helper_spec.rb
  spec/helpers/patients_helper_spec.rb
Labels: design tweak

#4086 Add ability to override today's date
  app/lib/academic_year.rb
  config/settings.yml
  spec/lib/academic_year_spec.rb
  terraform/app/env/production.tfvars
  terraform/app/env/qa.tfvars
  terraform/app/env/test.tfvars
  terraform/app/variables.tf
Labels: refactor

#4088 Set `academic_year_today_override` to an empty string
  spec/lib/academic_year_spec.rb
  terraform/app/variables.tf
Labels: bug

#4089 Set `academic_year_today_override` to `nil`
  app/lib/academic_year.rb
  spec/lib/academic_year_spec.rb
  terraform/app/variables.tf
Labels: refactor

#4083 Add patients to multiple school sessions
  app/models/patient.rb
  app/models/school_move.rb
  spec/controllers/api/organisations_controller_spec.rb
  spec/features/import_child_records_spec.rb
  spec/models/cohort_import_spec.rb
  spec/models/school_move_spec.rb
Labels: bug

#4084 Clarify `in_programmes` scope on patients and patient sessions
  app/components/app_programme_stats_component.rb
  app/controllers/programmes/overview_controller.rb
  app/controllers/programmes/patients_controller.rb
  app/forms/patient_search_form.rb
  app/models/note.rb
  app/models/patient.rb
  app/models/patient_session.rb
  app/models/session.rb
  app/views/programmes/index.html.erb
  lib/generate/triages.rb
  lib/generate/vaccination_records.rb
  spec/controllers/api/organisations_controller_spec.rb
  spec/features/import_child_records_spec.rb
  spec/forms/patient_search_form_spec.rb
  spec/models/cohort_import_spec.rb
  spec/models/patient_session_spec.rb
  spec/models/patient_spec.rb
Labels: bug

#4090 Fix data replication workflow
  .github/workflows/data-replication-pipeline.yml
  terraform/data_replication/outputs.tf
Labels: github_actions

#4099 Fix the text in the "Select a default batch" header
  app/views/sessions/record/batch.html.erb
Labels: design tweak

#4107 Fix content of verbal consent labels
  config/locales/en.yml
  spec/features/verbal_consent_given_spec.rb
Labels: design tweak

#4105 Remove academic year default assignment in CreateSession CLI command
  app/lib/mavis_cli/organisations/create_sessions.rb
Labels: bug

#4109 Fix content of verbal consent labels
  config/locales/en.yml
  spec/features/verbal_consent_given_spec.rb
Labels: bug

#4110 Add `theme-color` meta tag, adapt based on hosting environment
  app/components/app_hosting_environment_component.rb
  app/controllers/application_controller.rb
  app/lib/hosting_environment.rb
  app/views/layouts/application.html.erb
  spec/lib/hosting_environment_spec.rb
Labels: design tweak

#3704 Fix long batch name
  app/views/vaccines/index.html.erb
Labels: design tweak

#4114 Update Devise localisation strings
  config/locales/devise.en.yml
Labels: design tweak

#4108 Add URN/postcode to school options drop down
  app/helpers/locations_helper.rb
  app/views/draft_class_imports/session.html.erb
  app/views/parent_interface/consent_forms/edit/school.html.erb
Labels: design tweak

#4106 Move testing endpoints from /api/.. to /api/testing/...
  Gemfile.lock
  app/controllers/api/base_controller.rb
  app/controllers/api/testing/base_controller.rb
  app/controllers/api/testing/locations_controller.rb
  app/controllers/api/testing/onboard_controller.rb
  app/controllers/api/testing/organisations_controller.rb
  config/routes.rb
  spec/controllers/api/testing/organisations_controller_spec.rb
  spec/requests/api/testing/locations_spec.rb
  spec/requests/api/testing/onboard_spec.rb
Labels: refactor

#4020 Move programme cohorts to overview page
  app/components/app_programme_navigation_component.rb
  app/components/app_programme_stats_component.html.erb
  app/controllers/programmes/base_controller.rb
  app/controllers/programmes/cohorts_controller.rb
  app/controllers/programmes/overview_controller.rb
  app/views/programmes/cohorts/index.html.erb
  app/views/programmes/cohorts/show.html.erb
  app/views/programmes/overview/show.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/features/e2e_journey_spec.rb
  spec/features/import_child_records_slow_spec.rb
  spec/features/import_child_records_spec.rb
  spec/features/import_child_records_with_duplicates_spec.rb
  spec/features/import_vaccination_records_spec.rb
  spec/features/programme_cohorts_spec.rb
Labels: feature

#4036 Rename `Team` to `Subteam`
  README.md
  app/controllers/api/testing/locations_controller.rb
  app/controllers/api/testing/organisations_controller.rb
  app/controllers/parent_interface/consent_forms/base_controller.rb
  app/jobs/email_delivery_job.rb
  app/lib/generic_clinic_factory.rb
  app/lib/govuk_notify_personalisation.rb
  app/lib/mavis_cli/clinics/add_to_organisation.rb
  app/lib/mavis_cli/gias/check_import.rb
  app/lib/mavis_cli/schools/add_to_organisation.rb
  app/lib/reports/offline_session_exporter.rb
  app/models/consent_form.rb
  app/models/location.rb
  app/models/onboarding.rb
  app/models/organisation.rb
  app/models/patient_session.rb
  app/models/session.rb
  app/models/subteam.rb
  app/models/vaccination_record.rb
  app/policies/location/programme_year_group_policy.rb
  app/policies/location_policy.rb
  app/views/parent_interface/consent_forms/cannot_consent_responsibility.html.erb
  app/views/parent_interface/consent_forms/deadline_passed.html.erb
  app/views/parent_interface/consent_forms/edit/school.html.erb
  config/onboarding/coventry-training.yaml
  config/onboarding/hertfordshire-training.yaml
  config/onboarding/leicestershire-training.yaml
  config/onboarding/smoke-test.yml
  db/migrate/20250722162319_rename_team_to_subteam.rb
  db/schema.rb
  db/seeds.rb
  docs/managing-teams.md
  lib/tasks/schools.rake
  lib/tasks/subteams.rake
  script/organisation_export.rb
  spec/controllers/api/testing/organisations_controller_spec.rb
  spec/factories/locations.rb
  spec/factories/patients.rb
  spec/factories/sessions.rb
  spec/factories/subteams.rb
  spec/features/cli_clinics_add_to_organisation_spec.rb
  spec/features/cli_generate_vaccination_records_spec.rb
  spec/features/cli_schools_add_to_organisation_spec.rb
  spec/features/parental_consent_closed_spec.rb
  spec/features/parental_consent_school_session_completed_spec.rb
  spec/fixtures/files/onboarding/invalid.yaml
  spec/fixtures/files/onboarding/valid.yaml
  spec/forms/patient_search_form_spec.rb
  spec/lib/govuk_notify_personalisation_spec.rb
  spec/lib/reports/offline_session_exporter_spec.rb
  spec/lib/reports/programme_vaccinations_exporter_spec.rb
  spec/lib/tasks/schools_rake_spec.rb
  spec/models/location_spec.rb
  spec/models/onboarding_spec.rb
  spec/models/subteam_spec.rb
  spec/requests/api/testing/locations_spec.rb
  spec/requests/api/testing/onboard_spec.rb
Labels: operations, refactor

#4117 Remove `Session#today` scope
  app/models/session.rb
Labels: refactor

#4111 Add `ApplicationController#current_organisation`
  app/controllers/application_controller.rb
  app/controllers/batches_controller.rb
  app/controllers/class_imports_controller.rb
  app/controllers/cohort_imports_controller.rb
  app/controllers/immunisation_imports_controller.rb
  app/controllers/imports_controller.rb
  app/controllers/organisations_controller.rb
  app/controllers/patient_sessions/programmes_controller.rb
  app/helpers/school_moves_helper.rb
Labels: refactor

#4097 Remove case sensitivity in validation check of clinic name
  app/models/immunisation_import_row.rb
  spec/models/immunisation_import_row_spec.rb
Labels: operations

#4092 Remove "Vaccines administered" column
  app/controllers/programmes_controller.rb
  app/models/programme.rb
  app/views/programmes/index.html.erb
  spec/lib/fhir_mapper/vaccination_record_spec.rb
Labels: design tweak

#4118 Ensure gelatine is a refusal option
  app/models/consent.rb
  app/models/draft_consent.rb
  app/views/draft_consents/reason.html.erb
  spec/features/verbal_consent_given_spec.rb
  spec/features/verbal_consent_refused_spec.rb
Labels: bug

#4100 Import class lists in to schools
  app/components/app_imports_table_component.html.erb
  app/components/app_imports_table_component.rb
  app/components/app_programme_stats_component.rb
  app/components/app_session_details_summary_component.rb
  app/controllers/api/testing/organisations_controller.rb
  app/controllers/class_imports_controller.rb
  app/controllers/draft_class_imports_controller.rb
  app/controllers/programmes/base_controller.rb
  app/controllers/programmes/overview_controller.rb
  app/controllers/programmes/patients_controller.rb
  app/models/class_import.rb
  app/models/class_import_row.rb
  app/models/draft_class_import.rb
  app/views/class_imports/new.html.erb
  app/views/draft_class_imports/location.html.erb
  app/views/draft_class_imports/session.html.erb
  app/views/draft_class_imports/year_groups.html.erb
  app/views/imports/show.html.erb
  app/views/programmes/overview/show.html.erb
  config/routes.rb
  db/migrate/20250729115701_add_location_to_class_lists.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/class_imports.rb
  spec/features/import_class_lists_spec.rb
  spec/models/class_import_row_spec.rb
  spec/models/class_import_spec.rb
Labels: operations

#4078 Import patients in to pending year group
  app/controllers/sessions/invite_to_clinic_controller.rb
  app/forms/patient_search_form.rb
  app/models/class_import.rb
  app/models/consent_form.rb
  app/models/onboarding.rb
  app/models/organisation.rb
  app/models/patient.rb
  app/models/patient_import_row.rb
  app/models/patient_session.rb
  app/models/school_move.rb
  app/models/session.rb
  db/seeds.rb
  lib/core_ext/integer/year_group.rb
  lib/tasks/performance.rake
  spec/factories/patients.rb
  spec/features/hpv_vaccination_offline_spec.rb
  spec/features/manage_clinic_sessions_spec.rb
  spec/features/manage_school_sessions_spec.rb
  spec/features/programme_cohorts_spec.rb
  spec/lib/reports/offline_session_exporter_spec.rb
  spec/models/class_import_spec.rb
  spec/models/cohort_import_spec.rb
  spec/models/school_move_spec.rb
  spec/models/vaccination_record_spec.rb
Labels: operations

#4123 Display URN for all school options
  app/views/draft_class_imports/location.html.erb
Labels: design tweak

#4126 Fix issue with incorrect patients appearing in programmes
  app/forms/patient_search_form.rb
  app/models/patient_session.rb
  app/views/programmes/index.html.erb
  spec/features/import_child_records_spec.rb
  spec/models/patient_session_spec.rb
  spec/models/patient_spec.rb
Labels: bug

#4129 Improve rendering of session dates
  app/components/app_session_card_component.rb
  spec/components/app_session_card_component_spec.rb
Labels: design tweak

#4131 Improve session ordering
  app/forms/session_search_form.rb
  app/models/location.rb
  app/models/session.rb
  spec/models/session_spec.rb
Labels: design tweak

#4133 Refactor how distinct patients are determined
  app/controllers/programmes/base_controller.rb
  app/controllers/programmes/patients_controller.rb
  spec/features/import_child_records_spec.rb
Labels: bug

#4132 Restrict which year groups are shown
  app/controllers/draft_class_imports_controller.rb
  app/views/class_imports/new.html.erb
  spec/features/import_class_lists_spec.rb
Labels: bug
