Repository nhsuk/manage-vaccinations-in-schools, pull requests merged in 2025-03, with the labels that each got.

#3120 Improve vaccine and programme error messages
  config/locales/en.yml
  spec/models/immunisation_import_row_spec.rb
Labels: 🧑‍🎨 design tweak

#2901 Stop using recipient_deterministic
  app/components/app_activity_log_component.rb
  app/jobs/email_delivery_job.rb
  app/jobs/sms_delivery_job.rb
  app/models/notify_log_entry.rb
  app/models/parent.rb
  db/migrate/20250128111907_make_recipient_from_notify_log_entries_not_nullable.rb
  db/schema.rb
  lib/tasks/notify_log_entries.rake
  spec/factories/notify_log_entries.rb
  spec/jobs/email_delivery_job_spec.rb
  spec/jobs/sms_delivery_job_spec.rb
  spec/models/notify_log_entry_spec.rb
Labels: 📐 data_consistency, 🛠️ refactor

#3101 Select today's batch per programme
  app/controllers/batches_controller.rb
  app/controllers/concerns/todays_batch_concern.rb
  app/controllers/draft_vaccination_records_controller.rb
  app/controllers/vaccinations/batch_controller.rb
  app/controllers/vaccinations_controller.rb
  app/controllers/vaccines_controller.rb
  app/models/batch.rb
  app/views/vaccinations/batch/edit.html.erb
  app/views/vaccinations/index.html.erb
  app/views/vaccines/index.html.erb
  config/routes.rb
  spec/features/vaccination_todays_batch_spec.rb
Labels: ✨ feature

#3108 Fix back link on parental consent confirm page
  app/controllers/parent_interface/consent_forms_controller.rb
  app/views/parent_interface/consent_forms/confirm.html.erb
  spec/features/parental_consent_change_answers_spec.rb
Labels: 🐞 bug

#3121 Improve error message when SESSION_ID doesn't match an actual session
  config/locales/en.yml
  spec/models/immunisation_import_row_spec.rb
Labels: 🧑‍🎨 design tweak

#3117 Update patient table design
  app/assets/stylesheets/_filters.scss
  app/assets/stylesheets/_grid.scss
  app/assets/stylesheets/_patients.scss
  app/assets/stylesheets/_table.scss
  app/assets/stylesheets/application.scss
  app/components/app_card_component.rb
  app/components/app_session_patient_table_component.html.erb
Labels: ✨ feature

#3129 Build new children design
  app/assets/stylesheets/_table.scss
  app/components/app_patient_table_component.html.erb
  app/components/app_patient_table_component.rb
  app/components/app_search_component.rb
  app/components/app_search_input_component.rb
  app/controllers/concerns/search_form_concern.rb
  app/controllers/consent_forms_controller.rb
  app/controllers/immunisation_imports_controller.rb
  app/controllers/patients_controller.rb
  app/forms/search_form.rb
  app/views/consent_forms/search.html.erb
  app/views/imports/show.html.erb
  app/views/patients/index.html.erb
  spec/components/app_patient_table_component_spec.rb
  spec/features/import_child_records_slow_spec.rb
  spec/features/import_child_records_spec.rb
  spec/features/import_class_lists_spec.rb
  spec/features/patient_search_spec.rb
Labels: ✨ feature

#3133 Build new session triage tab
  app/components/app_outcome_banner_component.rb
  app/components/app_patient_page_component.html.erb
  app/components/app_patient_session_search_result_card_component.rb
  app/components/app_search_component.rb
  app/components/app_simple_status_banner_component.rb
  app/components/app_triage_form_component.rb
  app/controllers/concerns/search_form_concern.rb
  app/controllers/consents_controller.rb
  app/controllers/sessions/triage_controller.rb
  app/controllers/triages_controller.rb
  app/forms/search_form.rb
  app/lib/reports/offline_session_exporter.rb
  app/lib/reports/programme_vaccinations_exporter.rb
  app/models/concerns/patient_session_status_concern.rb
  app/models/patient.rb
  app/models/patient_session.rb
  app/models/patient_session/consent.rb
  app/models/patient_session/triage.rb
  app/views/sessions/_secondary_navigation.html.erb
  app/views/sessions/show.html.erb
  app/views/sessions/triage/show.html.erb
  app/views/triages/index.html.erb
  config/locales/patient_session.en.yml
  config/routes.rb
  spec/components/app_outcome_banner_component_spec.rb
  spec/components/app_simple_status_banner_component_spec.rb
  spec/features/hpv_vaccination_administered_spec.rb
  spec/features/hpv_vaccination_already_had_spec.rb
  spec/features/hpv_vaccination_cannot_record_as_admin_spec.rb
  spec/features/hpv_vaccination_clinic_spec.rb
  spec/features/hpv_vaccination_delayed_spec.rb
  spec/features/hpv_vaccination_pre_screening_spec.rb
  spec/features/menacwy_vaccination_administered_spec.rb
  spec/features/parental_consent_create_patient_spec.rb
  spec/features/parental_consent_spec.rb
  spec/features/td_ipv_vaccination_administered_spec.rb
  spec/features/triage_delay_vaccination_spec.rb
  spec/features/triage_partially_vaccinated_spec.rb
  spec/features/triage_spec.rb
  spec/features/triage_then_parental_consent_refused_spec.rb
  spec/forms/search_form_spec.rb
  spec/models/patient_session/triage_spec.rb
  spec/models/patient_session_spec.rb
Labels: ✨ feature

#3140 Reinstate sticky secondary navigation on patient session page
  app/assets/stylesheets/_secondary-navigation.scss
Labels: 🐞 bug

#3139 Update vaccination journey content
  app/components/app_vaccinate_form_component.html.erb
  app/views/draft_vaccination_records/batch.html.erb
  app/views/draft_vaccination_records/date_and_time.html.erb
  app/views/draft_vaccination_records/delivery.html.erb
  app/views/draft_vaccination_records/location.html.erb
  app/views/draft_vaccination_records/outcome.html.erb
  app/views/draft_vaccination_records/vaccine.html.erb
  spec/components/app_patient_page_component_spec.rb
  spec/components/app_vaccinate_form_component_spec.rb
  spec/features/hpv_vaccination_cannot_record_as_admin_spec.rb
  spec/features/invalidate_consent_spec.rb
  spec/features/manage_attendance_spec.rb
  spec/features/triage_delay_vaccination_spec.rb
  spec/features/withdraw_consent_spec.rb
Labels: 🧑‍🎨 design tweak

#3142 Ensure consent period is capitalised
  app/components/app_programme_session_table_component.html.erb
  app/components/app_session_summary_component.rb
  app/components/app_session_table_component.html.erb
  app/helpers/sessions_helper.rb
  spec/helpers/sessions_helper_spec.rb
Labels: 🧑‍🎨 design tweak

#3144 Ensure invalid dates don't raise an error
  app/forms/search_form.rb
  spec/forms/search_form_spec.rb
Labels: 🐞 bug

#3147 Sort patients when fuzzy searching
  app/models/patient.rb
  spec/models/patient_spec.rb
Labels: 🗄️ operations

#3145 Ensure a SchoolMove is always applied to new patients
  app/models/patient_import_row.rb
  spec/fixtures/cohort_import/valid.csv
  spec/models/cohort_import_spec.rb
Labels: 🐞 bug

#3143 Filter session triage and register tabs
  app/components/app_search_component.rb
  app/controllers/sessions/consent_controller.rb
  app/controllers/sessions/register_controller.rb
  app/controllers/sessions/triage_controller.rb
  app/forms/search_form.rb
  app/views/sessions/consent/show.html.erb
  app/views/sessions/register/show.html.erb
  app/views/sessions/triage/show.html.erb
  spec/features/hpv_vaccination_administered_spec.rb
  spec/features/hpv_vaccination_already_had_spec.rb
  spec/features/hpv_vaccination_cannot_record_as_admin_spec.rb
  spec/features/hpv_vaccination_clinic_spec.rb
  spec/features/hpv_vaccination_delayed_spec.rb
  spec/features/hpv_vaccination_pre_screening_spec.rb
  spec/features/menacwy_vaccination_administered_spec.rb
  spec/features/parental_consent_create_patient_spec.rb
  spec/features/parental_consent_spec.rb
  spec/features/td_ipv_vaccination_administered_spec.rb
Labels: 🐞 bug

#3135 Build new session record tab
  app/components/app_patient_session_search_result_card_component.rb
  app/components/app_search_component.rb
  app/controllers/concerns/patient_tabs_concern.rb
  app/controllers/concerns/search_form_concern.rb
  app/controllers/draft_vaccination_records_controller.rb
  app/controllers/sessions/record_controller.rb
  app/controllers/sessions/register_controller.rb
  app/controllers/triages_controller.rb
  app/controllers/vaccinations/batch_controller.rb
  app/controllers/vaccinations_controller.rb
  app/forms/search_form.rb
  app/lib/reports/careplus_exporter.rb
  app/models/concerns/patient_session_status_concern.rb
  app/models/patient_session.rb
  app/models/patient_session/record.rb
  app/views/sessions/_secondary_navigation.html.erb
  app/views/sessions/record/batch.html.erb
  app/views/sessions/record/show.html.erb
  app/views/sessions/show.html.erb
  app/views/vaccinations/batch/edit.html.erb
  app/views/vaccinations/index.html.erb
  config/initializers/tab_paths.rb
  config/locales/en.yml
  config/locales/patient_session.en.yml
  config/routes.rb
  spec/controllers/concerns/patient_tabs_concern_spec.rb
  spec/features/access_log_spec.rb
  spec/features/delete_vaccination_record_spec.rb
  spec/features/e2e_journey_spec.rb
  spec/features/hpv_vaccination_administered_spec.rb
  spec/features/hpv_vaccination_already_had_spec.rb
  spec/features/hpv_vaccination_cannot_record_as_admin_spec.rb
  spec/features/hpv_vaccination_clinic_spec.rb
  spec/features/hpv_vaccination_delayed_spec.rb
  spec/features/hpv_vaccination_offline_spec.rb
  spec/features/hpv_vaccination_pre_screening_spec.rb
  spec/features/menacwy_vaccination_administered_spec.rb
  spec/features/parental_consent_clinic_spec.rb
  spec/features/parental_consent_create_patient_spec.rb
  spec/features/parental_consent_refused_spec.rb
  spec/features/parental_consent_spec.rb
  spec/features/td_ipv_vaccination_administered_spec.rb
  spec/features/triage_delay_vaccination_spec.rb
  spec/features/vaccination_todays_batch_spec.rb
  spec/forms/search_form_spec.rb
  spec/models/patient_session/record_spec.rb
  spec/models/patient_session/triage_spec.rb
  spec/routing/vaccinations_routing_spec.rb
Labels: ✨ feature

#3137 Build new session outcome tab
  app/components/app_outcome_banner_component.rb
  app/components/app_patient_page_component.html.erb
  app/components/app_patient_session_search_result_card_component.rb
  app/components/app_search_component.rb
  app/components/app_simple_status_banner_component.rb
  app/controllers/concerns/search_form_concern.rb
  app/controllers/sessions/outcome_controller.rb
  app/controllers/sessions/register_controller.rb
  app/forms/search_form.rb
  app/lib/reports/offline_session_exporter.rb
  app/models/concerns/patient_session_status_concern.rb
  app/models/patient_session.rb
  app/models/patient_session/outcome.rb
  app/models/patient_session/record.rb
  app/models/patient_session/triage.rb
  app/views/sessions/_secondary_navigation.html.erb
  app/views/sessions/outcome/show.html.erb
  config/locales/patient_session.en.yml
  config/routes.rb
  spec/components/app_outcome_banner_component_spec.rb
  spec/components/app_simple_status_banner_component_spec.rb
  spec/features/delete_vaccination_record_spec.rb
  spec/features/hpv_vaccination_offline_spec.rb
  spec/features/parental_consent_clinic_spec.rb
  spec/features/parental_consent_create_patient_spec.rb
  spec/features/parental_consent_refused_spec.rb
  spec/features/parental_consent_spec.rb
  spec/forms/search_form_spec.rb
  spec/models/patient_session/outcome_spec.rb
  spec/models/patient_session_spec.rb
Labels: ✨ feature

#3138 Simplify patient session routes and fix session links
  app/components/app_consent_component.html.erb
  app/components/app_consent_component.rb
  app/components/app_patient_page_component.html.erb
  app/components/app_patient_page_component.rb
  app/components/app_patient_session_search_result_card_component.rb
  app/components/app_patient_session_table_component.html.erb
  app/components/app_patient_session_table_component.rb
  app/components/app_session_patient_table_component.rb
  app/components/app_vaccinate_form_component.rb
  app/controllers/consent_forms_controller.rb
  app/controllers/consents_controller.rb
  app/controllers/draft_consents_controller.rb
  app/controllers/draft_vaccination_records_controller.rb
  app/controllers/patient_sessions_controller.rb
  app/controllers/patients_controller.rb
  app/controllers/session_attendances_controller.rb
  app/controllers/triages_controller.rb
  app/controllers/vaccinations_controller.rb
  app/models/concerns/patient_session_status_concern.rb
  app/views/patient_sessions/_secondary_navigation.html.erb
  app/views/patient_sessions/log.html.erb
  app/views/patient_sessions/show.html.erb
  app/views/patients/show.html.erb
  app/views/programmes/patients.html.erb
  app/views/session_attendances/edit.html.erb
  app/views/sessions/consent/show.html.erb
  app/views/sessions/outcome/show.html.erb
  app/views/sessions/record/show.html.erb
  app/views/sessions/register/show.html.erb
  app/views/sessions/triage/show.html.erb
  app/views/triages/new.html.erb
  config/routes.rb
  spec/components/app_consent_component_spec.rb
  spec/components/app_patient_page_component_spec.rb
  spec/components/app_patient_session_search_result_card_component_spec.rb
  spec/components/app_patient_session_table_component_spec.rb
  spec/components/app_session_patient_table_component_spec.rb
  spec/components/app_vaccinate_form_component_spec.rb
  spec/features/e2e_journey_spec.rb
  spec/features/hpv_vaccination_offline_spec.rb
  spec/features/parental_consent_spec.rb
Labels: ✨ feature

#3141 Build new session overview tab
  app/components/app_programme_session_table_component.rb
  app/components/app_session_actions_summary_component.rb
  app/components/app_session_details_summary_component.rb
  app/components/app_session_summary_component.rb
  app/controllers/sessions_controller.rb
  app/helpers/application_helper.rb
  app/helpers/sessions_helper.rb
  app/models/patient_session_stats.rb
  app/views/sessions/_header.html.erb
  app/views/sessions/_secondary_navigation.html.erb
  app/views/sessions/consent/show.html.erb
  app/views/sessions/outcome/show.html.erb
  app/views/sessions/record/show.html.erb
  app/views/sessions/register/show.html.erb
  app/views/sessions/show.html.erb
  app/views/sessions/triage/show.html.erb
  spec/components/app_session_actions_summary_component_spec.rb
  spec/components/app_session_details_summary_component_spec.rb
  spec/components/app_session_summary_component_spec.rb
  spec/features/hpv_vaccination_offline_spec.rb
  spec/features/import_class_lists_move_spec.rb
  spec/features/import_class_lists_spec.rb
  spec/features/import_class_lists_with_duplicates_spec.rb
  spec/features/manage_school_sessions_spec.rb
  spec/features/paper_consent_download_spec.rb
  spec/features/td_ipv_already_had_spec.rb
  spec/features/triage_partially_vaccinated_spec.rb
  spec/helpers/sessions_helper_spec.rb
  spec/models/patient_session_stats_spec.rb
Labels: ✨ feature

#3150 Restrict return_to parameter
  app/controllers/patient_sessions_controller.rb
Labels: 🛠️ refactor

#3136 Change the CarePlus exporter to redact patient address_line_1 if patient is restricted
  app/lib/reports/careplus_exporter.rb
  spec/lib/reports/careplus_exporter_spec.rb
  spec/lib/reports/programme_vaccinations_exporter_spec.rb
Labels: 🐞 bug

#3151 Fix could not vaccinate outcome
  app/models/patient_session/outcome.rb
  spec/features/hpv_vaccination_offline_spec.rb
  spec/models/patient_session/outcome_spec.rb
Labels: 🐞 bug

#3152 Stop using PatientSession statuses
  app/components/app_consent_status_component.rb
  app/components/app_outcome_banner_component.rb
  app/components/app_session_actions_summary_component.rb
  app/components/app_simple_status_banner_component.rb
  app/controllers/concerns/triage_mailer_concern.rb
  app/controllers/sessions/register_controller.rb
  app/helpers/triage_helper.rb
  app/helpers/vaccinations_helper.rb
  app/jobs/concerns/send_clinic_invitations_concern.rb
  app/jobs/school_consent_reminders_job.rb
  app/jobs/school_consent_requests_job.rb
  app/jobs/school_session_reminders_job.rb
  app/lib/reports/export_formatters.rb
  app/lib/reports/offline_session_exporter.rb
  app/models/concerns/patient_session_status_concern.rb
  app/models/patient_session.rb
  app/models/patient_session/triage.rb
  config/locales/patient_session_statuses.en.yml
  spec/components/app_simple_status_banner_component_spec.rb
  spec/controllers/concerns/patient_sorting_concern_spec.rb
  spec/factories/patient_sessions.rb
  spec/features/hpv_vaccination_delayed_spec.rb
  spec/models/concerns/patient_session_status_concern_spec.rb
Labels: 🛠️ refactor

#3157 Change label to "All"
  app/components/app_search_component.rb
Labels: 🧑‍🎨 design tweak

#3158 Revert "Change label to "All""
  app/components/app_search_component.rb
Labels: 🧑‍🎨 design tweak

#3156 Update session record and outcome tabs
  app/components/app_patient_session_search_result_card_component.rb
  app/components/app_programme_status_tags_component.rb
  app/components/app_search_component.rb
  app/controllers/patient_sessions_controller.rb
  app/controllers/sessions/outcome_controller.rb
  app/controllers/sessions/record_controller.rb
  app/controllers/sessions/triage_controller.rb
  app/views/sessions/_header.html.erb
  app/views/sessions/outcome/show.html.erb
  app/views/sessions/record/show.html.erb
  config/locales/status.en.yml
  spec/components/app_programme_status_tags_component_spec.rb
  spec/features/e2e_journey_spec.rb
  spec/features/hpv_vaccination_administered_spec.rb
  spec/features/hpv_vaccination_already_had_spec.rb
  spec/features/hpv_vaccination_clinic_spec.rb
  spec/features/hpv_vaccination_delayed_spec.rb
  spec/features/hpv_vaccination_offline_spec.rb
  spec/features/hpv_vaccination_pre_screening_spec.rb
  spec/features/menacwy_vaccination_administered_spec.rb
  spec/features/parental_consent_clinic_spec.rb
  spec/features/parental_consent_create_patient_spec.rb
  spec/features/parental_consent_refused_spec.rb
  spec/features/parental_consent_spec.rb
  spec/features/td_ipv_vaccination_administered_spec.rb
  spec/features/triage_delay_vaccination_spec.rb
Labels: ✨ feature

#3159 Update session overview page to match latest designs
  app/components/app_session_actions_component.rb
  app/components/app_session_actions_summary_component.rb
  app/components/app_session_details_summary_component.rb
  app/controllers/sessions/record_controller.rb
  app/jobs/school_session_reminders_job.rb
  app/models/concerns/patient_session_status_concern.rb
  app/models/patient.rb
  app/models/patient_session.rb
  app/views/sessions/show.html.erb
  spec/components/app_session_actions_component_spec.rb
  spec/components/app_session_actions_summary_component_spec.rb
  spec/components/app_session_details_summary_component_spec.rb
Labels: 🧑‍🎨 design tweak

#3160 Consider already had as vaccinated
  app/components/app_outcome_banner_component.rb
  app/models/patient/programme_outcome.rb
  spec/components/app_outcome_banner_component_spec.rb
  spec/factories/patient_sessions.rb
  spec/features/hpv_vaccination_already_had_spec.rb
  spec/models/patient/programme_outcome_spec.rb
Labels: 🧑‍🎨 design tweak

#3161 Show next activity on register tab
  app/components/app_patient_session_search_result_card_component.rb
  app/models/patient.rb
  app/models/patient/next_activity.rb
  config/locales/activity.en.yml
  spec/components/app_patient_session_search_result_card_component_spec.rb
  spec/models/patient/next_activity_spec.rb
Labels: ✨ feature

#3162 Show action required on record tab
  app/components/app_patient_session_search_result_card_component.rb
  spec/components/app_patient_session_search_result_card_component_spec.rb
Labels: 🧑‍🎨 design tweak

#3164 Update programme children design
  app/components/app_patient_search_result_card_component.rb
  app/components/app_session_patient_table_component.html.erb
  app/components/app_session_patient_table_component.rb
  app/controllers/concerns/patient_sorting_concern.rb
  app/controllers/programmes_controller.rb
  app/forms/search_form.rb
  app/views/consent_forms/search.html.erb
  app/views/programmes/patients.html.erb
  spec/components/app_patient_search_result_card_component_spec.rb
  spec/components/app_session_patient_table_component_spec.rb
  spec/components/previews/app_session_patient_table_component_preview.rb
  spec/controllers/concerns/patient_sorting_concern_spec.rb
  spec/features/patient_sorting_filtering_spec.rb
  spec/forms/search_form_spec.rb
Labels: ✨ feature

#3165 Allow search on partial date of birth
  app/components/app_search_component.rb
  app/controllers/concerns/search_form_concern.rb
  app/forms/search_form.rb
  app/models/patient.rb
  app/models/patient_session.rb
  spec/forms/search_form_spec.rb
Labels: ✨ feature

#3168 Add missing test for could not vaccinate
  spec/features/parental_consent_refused_spec.rb
Labels: 🛠️ refactor

#3170 Update breadcrumbs to match designs
  app/controllers/patient_sessions_controller.rb
  app/views/cohorts/index.html.erb
  app/views/cohorts/show.html.erb
  app/views/imports/issues/show.html.erb
  app/views/imports/show.html.erb
  app/views/patient_sessions/_breadcrumbs.html.erb
  app/views/patient_sessions/log.html.erb
  app/views/patient_sessions/show.html.erb
  app/views/patients/log.html.erb
  app/views/patients/show.html.erb
  app/views/programmes/patients.html.erb
  app/views/programmes/sessions.html.erb
  app/views/programmes/show.html.erb
  app/views/school_moves/show.html.erb
  app/views/sessions/_header.html.erb
  app/views/sessions/consent/show.html.erb
  app/views/sessions/outcome/show.html.erb
  app/views/sessions/record/show.html.erb
  app/views/sessions/register/show.html.erb
  app/views/sessions/show.html.erb
  app/views/sessions/triage/show.html.erb
  app/views/vaccination_records/index.html.erb
  app/views/vaccination_records/show.html.erb
  config/locales/en.yml
  spec/features/e2e_journey_spec.rb
  spec/features/hpv_vaccination_administered_spec.rb
  spec/features/hpv_vaccination_delayed_spec.rb
  spec/features/hpv_vaccination_offline_spec.rb
  spec/features/parental_consent_spec.rb
Labels: 🧑‍🎨 design tweak

#2871 Add SystmOne exporter
  app/lib/reports/systm_one_exporter.rb
  app/models/vaccination_report.rb
  app/views/vaccination_reports/file_format.html.erb
  config/locales/helpers.en.yml
  spec/features/download_vaccination_reports_spec.rb
  spec/lib/reports/systm_one_exporter_spec.rb
  spec/models/vaccination_report_spec.rb
Labels: ✨ feature

#3148 Don't record a dose sequence for Td/IPV
  app/components/app_import_format_details_component.rb
  app/components/app_vaccinate_form_component.rb
  app/components/app_vaccination_record_summary_component.rb
  app/controllers/draft_vaccination_records_controller.rb
  app/forms/vaccinate_form.rb
  app/lib/reports/offline_session_exporter.rb
  app/models/draft_vaccination_record.rb
  spec/features/hpv_vaccination_administered_spec.rb
  spec/features/td_ipv_vaccination_administered_spec.rb
Labels: 🗄️ operations

#3172 Update ordering of consent filters
  app/models/patient/consent_outcome.rb
Labels: 🧑‍🎨 design tweak

#3173 Add AppRegisterStatusTagComponent
  app/components/app_patient_session_search_result_card_component.rb
  app/components/app_register_status_tag_component.rb
  app/views/patient_sessions/show.html.erb
  config/locales/status.en.yml
  spec/features/manage_attendance_spec.rb
Labels: 🧑‍🎨 design tweak

#3167 Build new pre-screening designs
  app/components/app_activity_log_component.rb
  app/components/app_patient_page_component.rb
  app/components/app_vaccinate_form_component.html.erb
  app/controllers/vaccinations_controller.rb
  app/forms/vaccinate_form.rb
  app/models/pre_screening.rb
  app/models/programme.rb
  config/locales/en.yml
  config/locales/pre_screening.en.yml
  db/migrate/20250307161252_add_programme_to_pre_screenings.rb
  db/migrate/20250307163053_add_questions_to_pre_screening.rb
  db/schema.rb
  spec/components/app_activity_log_component_spec.rb
  spec/factories/pre_screenings.rb
  spec/features/doubles_vaccination_administered_spec.rb
  spec/features/e2e_journey_spec.rb
  spec/features/hpv_vaccination_administered_spec.rb
  spec/features/hpv_vaccination_already_had_spec.rb
  spec/features/hpv_vaccination_clinic_spec.rb
  spec/features/hpv_vaccination_delayed_spec.rb
  spec/features/hpv_vaccination_pre_screening_spec.rb
  spec/features/menacwy_vaccination_administered_spec.rb
  spec/features/td_ipv_vaccination_administered_spec.rb
  spec/features/vaccination_todays_batch_spec.rb
  spec/lib/patient_merger_spec.rb
  spec/models/pre_screening_spec.rb
Labels: ✨ feature

#3174 Allow recording already had vaccination for a clinic session
  app/controllers/patient_sessions_controller.rb
  spec/features/td_ipv_already_had_spec.rb
Labels: 🐞 bug

#3176 Update "could not vaccinate" session outcome
  app/models/concerns/patient_session_status_concern.rb
  app/models/patient_session/session_outcome.rb
  spec/features/parental_consent_refused_spec.rb
  spec/models/patient_session/session_outcome_spec.rb
Labels: 🐞 bug

#3175 Update vaccinated criteria for Td/IPV
  app/lib/vaccinated_criteria.rb
  app/models/patient/programme_outcome.rb
  spec/lib/vaccinated_criteria_spec.rb
Labels: 🗄️ operations

#3178 Seed health questions when consent is given
  app/controllers/dev_controller.rb
  app/controllers/parent_interface/consent_forms/edit_controller.rb
  app/models/consent_form.rb
  app/models/health_question.rb
  spec/features/parental_consent_change_answers_spec.rb
  spec/models/consent_form_spec.rb
Labels: 🐞 bug

#3179 Remove SCHOOL_URN from offline export
  app/lib/reports/offline_session_exporter.rb
  app/models/immunisation_import.rb
  spec/lib/reports/offline_session_exporter_spec.rb
Labels: 🐞 bug

#3180 Triage patients when recording vaccination already had
  app/controllers/draft_vaccination_records_controller.rb
  app/controllers/patient_sessions_controller.rb
  app/models/vaccination_record.rb
  spec/features/td_ipv_already_had_spec.rb
Labels: 🐞 bug

#3181 Make fuzzy search work on full name
  app/models/patient.rb
  spec/features/patient_search_spec.rb
  spec/models/patient_spec.rb
Labels: 🗄️ operations

#3182 Improve test coverage for reports
  spec/lib/reports/careplus_exporter_spec.rb
  spec/lib/reports/programme_vaccinations_exporter_spec.rb
Labels: 🛠️ refactor

#3194 Ensure patients are shown in triage list
  app/controllers/sessions/triage_controller.rb
Labels: 🐞 bug

#3195 Updated status colours
  config/locales/patient_session_statuses.en.yml
  config/locales/status.en.yml
  spec/components/app_outcome_banner_component_spec.rb
  spec/components/app_simple_status_banner_component_spec.rb
Labels: 🧑‍🎨 design tweak

#3196 Remove pluralisation on pre-screening questions
  app/components/app_vaccinate_form_component.html.erb
  app/forms/vaccinate_form.rb
  config/locales/helpers.en.yml
  config/locales/pre_screening.en.yml
  spec/features/doubles_vaccination_administered_spec.rb
  spec/features/vaccination_todays_batch_spec.rb
Labels: 🧑‍🎨 design tweak

#3197 Show "No vaccinations given"
  app/components/app_session_details_summary_component.rb
  config/locales/en.yml
  spec/components/app_session_details_summary_component_spec.rb
Labels: 🧑‍🎨 design tweak

#3201 Improve design of multiple default batches
  app/views/sessions/record/show.html.erb
Labels: 🧑‍🎨 design tweak

#3200 Return to patient session page
  app/controllers/draft_vaccination_records_controller.rb
  spec/features/doubles_vaccination_administered_spec.rb
  spec/features/e2e_journey_spec.rb
  spec/features/hpv_vaccination_administered_spec.rb
  spec/features/hpv_vaccination_already_had_spec.rb
  spec/features/hpv_vaccination_clinic_spec.rb
  spec/features/hpv_vaccination_delayed_spec.rb
  spec/features/menacwy_vaccination_administered_spec.rb
  spec/features/td_ipv_vaccination_administered_spec.rb
  spec/features/vaccination_todays_batch_spec.rb
Labels: 🧑‍🎨 design tweak

#3206 Permit search_form parameter
  app/components/app_patient_session_search_result_card_component.rb
Labels: 🛠️ refactor

#3205 Only show attendance buttons if allowed
  app/components/app_patient_session_search_result_card_component.rb
  app/models/patient_session.rb
  app/policies/session_attendance_policy.rb
  spec/components/app_patient_session_search_result_card_component_spec.rb
Labels: 🧑‍🎨 design tweak

#3207 Send vaccination administered per programme
  app/controllers/concerns/vaccination_mailer_concern.rb
  config/initializers/govuk_notify.rb
  spec/controllers/concerns/vaccination_mailer_concern_spec.rb
  spec/features/doubles_vaccination_administered_spec.rb
  spec/features/edit_vaccination_record_spec.rb
  spec/features/hpv_vaccination_administered_spec.rb
  spec/features/hpv_vaccination_already_had_spec.rb
  spec/features/hpv_vaccination_clinic_spec.rb
  spec/features/hpv_vaccination_delayed_spec.rb
  spec/features/hpv_vaccination_offline_spec.rb
  spec/features/menacwy_vaccination_administered_spec.rb
  spec/features/td_ipv_vaccination_administered_spec.rb
Labels: ✨ feature

#3208 Add outstanding programmes banner
  app/components/app_outcome_banner_component.rb
  app/controllers/draft_vaccination_records_controller.rb
  app/models/patient_session.rb
  app/views/patient_sessions/_breadcrumbs.html.erb
  app/views/patient_sessions/_header.html.erb
  app/views/patient_sessions/_secondary_navigation.html.erb
  app/views/patient_sessions/log.html.erb
  app/views/patient_sessions/show.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/features/doubles_vaccination_administered_spec.rb
  spec/features/hpv_vaccination_administered_spec.rb
  spec/features/hpv_vaccination_already_had_spec.rb
  spec/features/hpv_vaccination_clinic_spec.rb
  spec/features/hpv_vaccination_delayed_spec.rb
  spec/features/menacwy_vaccination_administered_spec.rb
  spec/features/td_ipv_already_had_spec.rb
  spec/features/td_ipv_vaccination_administered_spec.rb
  spec/features/vaccination_todays_batch_spec.rb
Labels: ✨ feature

#3212 Remove class_imports:assign_year_groups
  lib/tasks/class_imports.rake
Labels: 🛠️ refactor

#3214 Don't allow dose sequence to be provided
  app/models/immunisation_import_row.rb
  config/locales/en.yml
  spec/models/immunisation_import_row_spec.rb
Labels: 🗄️ operations

#3219 Don't fetch school if no URN is provided
  app/models/immunisation_import_row.rb
  spec/models/immunisation_import_row_spec.rb
Labels: 🐞 bug

#3217 Don't fetch school if no URN is provided
  app/models/immunisation_import_row.rb
  spec/models/immunisation_import_row_spec.rb
Labels: 🐞 bug

#3221 Ensure clinic records are included in school session offline exports
  app/lib/reports/offline_session_exporter.rb
  spec/lib/reports/offline_session_exporter_spec.rb
Labels: 🐞 bug

#3213 Change default TIME_OF_VACCINATION to midnight
  app/models/immunisation_import_row.rb
  spec/features/import_vaccination_records_with_duplicates_spec.rb
  spec/models/immunisation_import_row_spec.rb
Labels: 🐞 bug

#3224 Small improvements to outstanding programmes banner
  app/models/patient_session.rb
  app/views/patient_sessions/_header.html.erb
  spec/features/doubles_vaccination_cannot_record_as_admin_spec.rb
  spec/features/hpv_vaccination_delayed_spec.rb
Labels: 🧑‍🎨 design tweak

#3225 Fix import issue breadcrumb
  app/views/imports/issues/show.html.erb
Labels: 🧑‍🎨 design tweak

#3226 Add ticks to programme tabs
  app/assets/stylesheets/_secondary-navigation.scss
  app/components/app_secondary_navigation_component.html.erb
  app/components/app_secondary_navigation_component.rb
  app/models/patient_session/session_outcome.rb
  app/views/patient_sessions/_header.html.erb
  spec/components/app_secondary_navigation_component_spec.rb
Labels: 🧑‍🎨 design tweak

#3227 Don't try to create a batch if not provided
  app/models/immunisation_import_row.rb
  spec/fixtures/immunisation_import/valid_hpv.csv
  spec/models/immunisation_import_row_spec.rb
  spec/models/immunisation_import_spec.rb
Labels: 🐞 bug

#3229 Rename none outcome statuses
  app/components/app_consent_component.html.erb
  app/components/app_consent_component.rb
  app/components/app_programme_session_table_component.rb
  app/components/app_session_actions_component.rb
  app/controllers/consents_controller.rb
  app/models/patient/consent_outcome.rb
  app/models/patient/next_activity.rb
  app/models/patient/programme_outcome.rb
  app/models/patient_session.rb
  app/models/patient_session/register_outcome.rb
  app/models/patient_session/session_outcome.rb
  config/locales/status.en.yml
  spec/models/patient/consent_outcome_spec.rb
  spec/models/patient/programme_outcome_spec.rb
  spec/models/patient_session/session_outcome_spec.rb
Labels: 🛠️ refactor

#3228 Fix intermittently failing specs
  spec/features/doubles_vaccination_administered_spec.rb
  spec/lib/reports/programme_vaccinations_exporter_spec.rb
Labels: 🛠️ refactor

#3230 Show ticks according to programme outcome
  app/views/patient_sessions/_header.html.erb
Labels: 🧑‍🎨 design tweak

#3231 Filter reports by programme
  app/lib/reports/careplus_exporter.rb
  app/lib/reports/programme_vaccinations_exporter.rb
  app/lib/reports/systm_one_exporter.rb
  app/models/organisation.rb
  spec/lib/reports/careplus_exporter_spec.rb
  spec/lib/reports/programme_vaccinations_exporter_spec.rb
  spec/lib/reports/systm_one_exporter_spec.rb
Labels: 🐞 bug

#3232 Reduce N+1 queries on school move index
  app/controllers/school_moves_controller.rb
Labels: 🛠️ refactor

#3235 Hide "Record as already vaccinated" without permission
  app/views/patient_sessions/_header.html.erb
  spec/features/td_ipv_already_had_spec.rb
Labels: 🐞 bug

#3236 Avoid N+1 issue in vaccination criteria
  app/jobs/vaccination_confirmations_job.rb
  app/lib/vaccinated_criteria.rb
  app/models/vaccination_record.rb
Labels: 🛠️ refactor, ⌛️ performance

#3237 Fix "Refused vaccine" label
  config/locales/status.en.yml
  spec/features/parental_consent_refused_spec.rb
Labels: 🧑‍🎨 design tweak

#3238 Set session outcome to absent from session
  app/components/app_outcome_banner_component.rb
  app/models/patient_session/register_outcome.rb
  app/models/patient_session/session_outcome.rb
  spec/features/manage_attendance_spec.rb
  spec/models/patient_session/session_outcome_spec.rb
Labels: 🐞 bug

#3255 Small tidy ups to GitHub Actions
  .github/workflows/build-and-push-image.yml
  .github/workflows/continuous-deployment.yml
  .github/workflows/continuous_deployment.yml
  .github/workflows/deploy-application.yml
  .github/workflows/deploy-infrastructure.yml
Labels: 🛠️ refactor

#3276 Patch application deployment workflow
  .github/workflows/deploy-application.yml
  terraform/app/env/qa.tfvars
  terraform/scripts/check_task_definition.sh
Labels: 🛠️ refactor

#3279 MAV-929: Update SSH script
  script/shell.sh
  terraform/scripts/shell-access.sh
Labels: 🗄️ operations

#2902 Remove recipient_deterministic column
  app/models/notify_log_entry.rb
  db/migrate/20250128112422_remove_recipient_deterministic_from_notify_log_entries.rb
  db/schema.rb
Labels: 📐 data_consistency, 🛠️ refactor

#3247 Delete PilotController
  app/controllers/pilot_controller.rb
  app/models/notify_log_entry.rb
  db/migrate/20250128112422_remove_recipient_deterministic_from_notify_log_entries.rb
  db/schema.rb
Labels: 🛠️ refactor

#3259 Add a Rake task for generating fake data
  lib/tasks/performance.rake
Labels: ⌛️ performance

#3286 Prevent concurrent deployment workflows targeting same environment
  .github/workflows/deploy-application.yml
  .github/workflows/deploy-infrastructure.yml
  .github/workflows/deploy-mavis.yml
Labels: 🛠️ refactor

#3289 Avoid N+1 issue on school moves page
  app/controllers/school_moves_controller.rb
Labels: ⌛️ performance

#3272 Cache programme status in database
  app/components/app_outcome_banner_component.rb
  app/components/app_patient_page_component.html.erb
  app/components/app_patient_search_result_card_component.rb
  app/components/app_patient_session_search_result_card_component.rb
  app/components/app_simple_status_banner_component.rb
  app/controllers/draft_vaccination_records_controller.rb
  app/controllers/programmes_controller.rb
  app/controllers/triages_controller.rb
  app/controllers/vaccination_records_controller.rb
  app/forms/search_form.rb
  app/jobs/concerns/send_clinic_invitations_concern.rb
  app/jobs/school_consent_reminders_job.rb
  app/jobs/school_consent_requests_job.rb
  app/jobs/school_session_reminders_job.rb
  app/lib/reports/offline_session_exporter.rb
  app/lib/status_updater.rb
  app/lib/vaccinated_criteria.rb
  app/models/concerns/patient_session_status_concern.rb
  app/models/immunisation_import.rb
  app/models/patient.rb
  app/models/patient/next_activity.rb
  app/models/patient/programme_outcome.rb
  app/models/patient/triage_status.rb
  app/models/patient/vaccination_status.rb
  app/models/patient_session.rb
  app/views/patient_sessions/_header.html.erb
  app/views/programmes/patients.html.erb
  db/migrate/20250324195409_create_patient_vaccination_status.rb
  db/schema.rb
  spec/components/app_outcome_banner_component_spec.rb
  spec/components/app_simple_status_banner_component_spec.rb
  spec/factories/patient_sessions.rb
  spec/factories/patient_vaccination_statuses.rb
  spec/factories/patients.rb
  spec/jobs/send_clinic_subsequent_invitations_job_spec.rb
  spec/lib/status_updater_spec.rb
  spec/lib/vaccinated_criteria_spec.rb
  spec/models/patient/next_activity_spec.rb
  spec/models/patient/programme_outcome_spec.rb
  spec/models/patient/vaccination_status_spec.rb
  spec/models/patient_session_spec.rb
Labels: ⌛️ performance
