Repository nhsuk/manage-vaccinations-in-schools, pull requests merged in 2025-01, with the labels that each got.

#2805 Fix specs that assume a specific patient age so they pass in 2025
  spec/features/import_child_records_with_duplicates_spec.rb
  spec/features/patient_sorting_filtering_spec.rb
Labels: 🐞 bug, ruby

#2777 Include consent and session notifications when merging patients
  app/lib/patient_merger.rb
  spec/lib/patient_merger_spec.rb
Labels: 🐞 bug

#2782 Handle errors in ISO-8859-1 values
  config/initializers/i18n_nhs_design_system_date_interpolation.rb
  spec/fixtures/cohort_import/invalid_iso_8859_1_encoding.csv
  spec/models/cohort_import_spec.rb
Labels: 🐞 bug

#2789 Fix bug where nurses can't sort with blank postcodes
  app/controllers/concerns/patient_sorting_concern.rb
  spec/controllers/concerns/patient_sorting_concern_spec.rb
Labels: 🐞 bug

#2796 Align Careplus report date filtering with Mavis report logic
  app/lib/reports/careplus_exporter.rb
  spec/lib/reports/careplus_exporter_spec.rb
Labels: 🛠️ refactor, ✨ feature

#2817 Fix bug where nurses can't sort with blank postcodes
  app/controllers/concerns/patient_sorting_concern.rb
  spec/controllers/concerns/patient_sorting_concern_spec.rb
Labels: 🛠️ refactor

#2809 Upgrade Brakeman
  Gemfile.lock
  config/brakeman.ignore
Labels: 🛠️ refactor

#2819 Refactor AppOutcomeBannerComponent
  app/components/app_outcome_banner_component.rb
Labels: 🐞 bug, 🛠️ refactor

#2820 Handle invalid characters when encoding as UTF-8
  config/initializers/i18n_nhs_design_system_date_interpolation.rb
Labels: 🐞 bug

#2821 Fix bug where nurses can't sort with blank postcodes
  app/controllers/concerns/patient_sorting_concern.rb
  spec/controllers/concerns/patient_sorting_concern_spec.rb
Labels: 🐞 bug

#2779 Remove consent_form_patient
  app/components/app_compare_consent_form_and_patient_component.html.erb
  app/components/app_compare_consent_form_and_patient_component.rb
Labels: 🛠️ refactor

#2806 Patient factory: randomise the date of birth logic and align more obviously with year group calculations
  spec/factories/patients.rb
Labels: 🛠️ refactor, ruby

#2800 Use `Rails.env.local?`
  app/controllers/application_controller.rb
  app/lib/govuk_notify_personalisation.rb
  config/initializers/devise.rb
  config/initializers/log_public_assets.rb
  config/routes.rb
Labels: 🛠️ refactor

#2780 Allow specifying year group when importing
  app/components/app_import_format_details_component.rb
  app/components/app_patient_summary_component.rb
  app/models/cohort.rb
  app/models/concerns/year_group_concern.rb
  app/models/immunisation_import_row.rb
  app/models/patient.rb
  app/models/patient_import_row.rb
  app/models/school_move.rb
  config/locales/en.yml
  db/migrate/20241218155027_add_birth_academic_year_to_patients.rb
  db/schema.rb
  lib/core_ext/date/year_group.rb
  spec/components/app_import_format_details_component_spec.rb
  spec/factories/patients.rb
  spec/features/dev_reset_organisation_spec.rb
  spec/features/import_child_records_spec.rb
  spec/features/import_vaccination_records_spec.rb
  spec/features/parental_consent_create_patient_spec.rb
  spec/fixtures/class_import/valid.csv
  spec/fixtures/cohort_import/valid.csv
  spec/models/class_import_row_spec.rb
  spec/models/class_import_spec.rb
  spec/models/cohort_import_row_spec.rb
  spec/models/cohort_import_spec.rb
  spec/models/concerns/pending_changes_concern_spec.rb
  spec/models/immunisation_import_row_spec.rb
  spec/models/patient_spec.rb
Labels: 🛠️ refactor, ✨ feature

#2825 Validate date of birth in past
  app/models/immunisation_import_row.rb
  config/locales/en.yml
  spec/models/immunisation_import_row_spec.rb
Labels: 🐞 bug

#2798 Update erroneously added primary school URN to the correct secondary school URN
  config/onboarding/coventry-production.yaml
Labels: 🐞 bug

#2826 Avoid duplicate `DATE_OF_BIRTH` errors
  app/models/cohort.rb
  app/models/concerns/year_group_concern.rb
  app/models/immunisation_import_row.rb
  app/models/patient.rb
  app/models/patient_import_row.rb
  config/locales/en.yml
  spec/models/class_import_row_spec.rb
  spec/models/cohort_import_row_spec.rb
  spec/models/immunisation_import_row_spec.rb
Labels: 🐞 bug

#2757 Record PDS error responses in Sentry
  app/lib/nhs/pds.rb
Labels: 🗄️ operations

#2823 Ensure `subsequent_session_dates_offered_message` is present
  app/lib/govuk_notify_personalisation.rb
  spec/lib/govuk_notify_personalisation_spec.rb
  spec/mailers/session_mailer_spec.rb
Labels: 🐞 bug

#2827 Ignore restricted patients from sorting and filtering
  app/controllers/concerns/patient_sorting_concern.rb
  spec/controllers/concerns/patient_sorting_concern_spec.rb
  spec/features/patient_sorting_filtering_spec.rb
Labels: 🐞 bug

#2801 Use `params.expect`
  app/controllers/batches_controller.rb
  app/controllers/consents_controller.rb
  app/controllers/gillick_assessments_controller.rb
  app/controllers/offline_passwords_controller.rb
  app/controllers/session_attendances_controller.rb
  app/controllers/session_dates_controller.rb
  app/controllers/sessions/edit_controller.rb
  app/controllers/triages_controller.rb
  app/controllers/vaccination_reports_controller.rb
  app/controllers/vaccinations_controller.rb
Labels: 🛠️ refactor

#2831 Improve email address and phone number normalisation
  app/lib/email_address_normaliser.rb
  app/lib/phone_number_normaliser.rb
  app/models/consent_form.rb
  app/models/organisation.rb
  app/models/parent.rb
  app/models/team.rb
  app/models/user.rb
  spec/components/app_consent_form_summary_component_spec.rb
  spec/features/parental_consent_refused_spec.rb
  spec/features/parental_consent_spec.rb
  spec/features/verbal_consent_given_by_new_parental_contact_spec.rb
  spec/jobs/text_delivery_job_spec.rb
  spec/mailers/session_mailer_spec.rb
  spec/models/consent_form_spec.rb
  spec/models/organisation_spec.rb
  spec/models/parent_spec.rb
  spec/models/team_spec.rb
  spec/models/user_spec.rb
  spec/support/shared_examples/a_model_with_a_normalised_email_address.rb
  spec/support/shared_examples/a_model_with_a_normalised_phone_number.rb
Labels: 📐 data_consistency, 🛠️ refactor

#2832 Link text delivery with GOV.UK Notify IDs
  app/jobs/text_delivery_job.rb
  app/models/notify_log_entry.rb
  db/migrate/20250113142937_add_delivery_id_to_notify_log_entries.rb
  db/schema.rb
  spec/factories/notify_log_entries.rb
  spec/jobs/text_delivery_job_spec.rb
  spec/models/notify_log_entry_spec.rb
Labels: 🛠️ refactor

#2808 Add counts to navigation bar items
  app/assets/stylesheets/_count.scss
  app/assets/stylesheets/_header.scss
  app/components/app_header_navigation_item_component.rb
  app/models/patient.rb
  app/models/user.rb
  app/policies/consent_form_policy.rb
  app/policies/patient_policy.rb
  app/policies/school_move_policy.rb
  app/views/layouts/_header.html.erb
  config/locales/en.yml
  spec/features/import_class_lists_move_spec.rb
  spec/features/manage_children_spec.rb
  spec/features/parental_consent_clinic_spec.rb
  spec/features/parental_consent_create_patient_spec.rb
Labels: ✨ feature

#2797 Class list uploads: make it easier to tell which school the upload is for, and to navigate back to the school
  app/components/app_imports_table_component.html.erb
  app/components/app_imports_table_component.rb
  app/views/imports/show.html.erb
  spec/components/app_imports_table_component_spec.rb
  spec/features/import_class_lists_spec.rb
Labels: ✨ feature

#2843 Update docker build step packages
  Dockerfile
Labels: 🛠️ refactor

#2845 Small updates to header navigation item counts
  app/views/layouts/_header.html.erb
  app/views/school_moves/index.html.erb
Labels: ✨ feature

#2807 Add .cursorrules
  .cursorrules
Labels: 🛠️ refactor

#2851 Reword consent form "Mark as invalid"
  app/controllers/consent_forms_controller.rb
  app/models/batch.rb
  app/models/concerns/archivable.rb
  app/models/consent_form.rb
  app/views/consent_forms/archive.html.erb
  app/views/consent_forms/index.html.erb
  app/views/layouts/_header.html.erb
  config/routes.rb
  db/migrate/20250115123804_rename_consent_form_invalidated_at_to_archived_at.rb
  db/schema.rb
  spec/factories/consent_forms.rb
  spec/features/parental_consent_manual_matching_spec.rb
  spec/models/consent_form_spec.rb
Labels: ✨ feature

#2854 Only consider triage status if consent is given
  app/controllers/draft_consents_controller.rb
  app/models/concerns/patient_session_status_concern.rb
  spec/factories/patients.rb
  spec/features/triage_then_parenal_consent_refused_spec.rb
  spec/models/concerns/patient_session_status_concern_spec.rb
Labels: 🐞 bug

#2855 Rename "Safe to vaccinate"
  config/locales/patient_session_statuses.en.yml
  spec/components/app_simple_status_banner_component_spec.rb
Labels: 🗄️ operations

#2748 Add Reply-To IDs to teams
  app/mailers/application_mailer.rb
  app/models/team.rb
  db/migrate/20240214115829_add_reply_to_id_to_teams_old.rb
  db/migrate/20241213195932_add_reply_to_id_to_teams.rb
  db/schema.rb
  docs/onboarding.md
  spec/factories/teams.rb
  spec/fixtures/files/onboarding/valid.yaml
  spec/mailers/application_mailer_spec.rb
  spec/models/onboarding_spec.rb
  spec/models/team_spec.rb
Labels: 📐 data_consistency

#2822 Show environment banner on staging environments
  app/assets/stylesheets/_environment.scss
  app/assets/stylesheets/_tag.scss
  app/assets/stylesheets/application.scss
  app/components/app_hosting_environment_component.rb
  app/views/layouts/_header.html.erb
  config/initializers/inflections.rb
  config/locales/en.yml
Labels: ✨ feature

#2852 Rename "Responses" header link
  config/locales/en.yml
  spec/features/parental_consent_create_patient_spec.rb
Labels: 🗄️ operations

#2778 Allow community clinic ODS codes to be optional
  app/models/location.rb
  config/onboarding/coventry-model-office.yaml
  config/onboarding/coventry-production.yaml
  config/onboarding/hertfordshire-training-with-sessions.yaml
  config/onboarding/hertfordshire-training.yaml
  spec/fixtures/files/onboarding/valid.yaml
  spec/models/location_spec.rb
  spec/models/onboarding_spec.rb
Labels: 🗄️ operations, 🛠️ refactor

#2749 Add privacy notice URL to organisations
  app/lib/govuk_notify_personalisation.rb
  app/models/organisation.rb
  config/onboarding/coventry-model-office.yaml
  db/migrate/20241213205328_add_data_sharing_agreement_url_to_organisations.rb
  db/schema.rb
  docs/onboarding.md
  spec/factories/organisations.rb
  spec/fixtures/files/onboarding/valid.yaml
  spec/lib/govuk_notify_personalisation_spec.rb
  spec/models/onboarding_spec.rb
  spec/models/organisation_spec.rb
Labels: 📐 data_consistency

#2849 Allow creating patients from consent without NHS numbers
  app/controllers/consent_forms_controller.rb
  app/models/patient.rb
  app/views/consent_forms/index.html.erb
  spec/features/parental_consent_create_patient_spec.rb
Labels: ✨ feature

#2840 Refactor SMS delivery
  .rubocop.yml
  app/controllers/concerns/consent_form_mailer_concern.rb
  app/controllers/concerns/triage_mailer_concern.rb
  app/controllers/concerns/vaccination_mailer_concern.rb
  app/jobs/notify_delivery_job.rb
  app/jobs/sms_delivery_job.rb
  app/models/consent_notification.rb
  app/models/notify_log_entry.rb
  app/models/session_notification.rb
  config/initializers/govuk_notify.rb
  config/initializers/inflections.rb
  spec/controllers/concerns/consent_form_mailer_concern_spec.rb
  spec/controllers/concerns/triage_mailer_concern_spec.rb
  spec/controllers/concerns/vaccination_mailer_concern_spec.rb
  spec/factories/notify_log_entries.rb
  spec/features/hpv_vaccination_administered_spec.rb
  spec/features/hpv_vaccination_already_had_spec.rb
  spec/features/hpv_vaccination_clinic_spec.rb
  spec/features/hpv_vaccination_delayed_spec.rb
  spec/features/hpv_vaccination_offline_spec.rb
  spec/features/parental_consent_refused_spec.rb
  spec/features/parental_consent_send_request_spec.rb
  spec/features/parental_consent_spec.rb
  spec/features/scheduled_consent_requests_spec.rb
  spec/features/verbal_consent_given_by_new_parental_contact_spec.rb
  spec/features/verbal_consent_given_spec.rb
  spec/features/verbal_consent_given_when_previously_refused_spec.rb
  spec/features/verbal_consent_refused_personal_choice_spec.rb
  spec/features/verbal_consent_refused_spec.rb
  spec/jobs/sms_delivery_job_spec.rb
  spec/models/consent_notification_spec.rb
  spec/models/session_notification_spec.rb
  spec/spec_helper.rb
  spec/support/matchers/have_delivered_sms.rb
  spec/support/sms_expectations.rb
  spec/support/text_expectations.rb
Labels: 🛠️ refactor

#2853 Add `delivery_status` column to `notify_log_entries`
  app/models/notify_log_entry.rb
  db/migrate/20250116090241_add_delivery_status_to_notify_log_entries.rb
  db/schema.rb
  spec/factories/notify_log_entries.rb
  spec/models/notify_log_entry_spec.rb
Labels: 🛠️ refactor

#2756 Validate community clinic ODS code doesn't match organisation
  app/models/location.rb
  spec/models/location_spec.rb
Labels: 📐 data_consistency

#2833 Retry text delivery server errors
  app/jobs/notify_delivery_job.rb
Labels: 🗄️ operations

#2868 Add controller to handle GOV.UK Notify callbacks
  app/controllers/notifications_controller.rb
  app/models/notify_log_entry.rb
  config/routes.rb
  config/settings.yml
  config/settings/development.yml
  config/settings/test.yml
  db/migrate/20250116093944_add_index_on_notify_log_entries_delivery_id.rb
  db/schema.rb
  spec/controllers/notifications_controller_spec.rb
  spec/factories/notify_log_entries.rb
  spec/models/notify_log_entry_spec.rb
Labels: 🗄️ operations

#2848 Validate batch numbers using separate worksheet(s)
  Gemfile
  Gemfile.lock
  app/lib/reports/offline_session_exporter.rb
  spec/lib/reports/offline_session_exporter_spec.rb
Labels: 🐞 bug

#2841 Use GOV.UK Notify directly to send emails
  .rubocop.yml
  app/controllers/concerns/consent_form_mailer_concern.rb
  app/controllers/concerns/triage_mailer_concern.rb
  app/controllers/concerns/vaccination_mailer_concern.rb
  app/jobs/email_delivery_job.rb
  app/models/consent_notification.rb
  app/models/session_notification.rb
  spec/controllers/concerns/consent_form_mailer_concern_spec.rb
  spec/controllers/concerns/triage_mailer_concern_spec.rb
  spec/controllers/concerns/vaccination_mailer_concern_spec.rb
  spec/features/delete_vaccination_record_spec.rb
  spec/features/edit_vaccination_record_spec.rb
  spec/features/scheduled_consent_requests_spec.rb
  spec/jobs/email_delivery_job_spec.rb
  spec/models/consent_notification_spec.rb
  spec/models/session_notification_spec.rb
  spec/spec_helper.rb
  spec/support/email_expectations.rb
  spec/support/matchers/have_delivered_email.rb
Labels: 🛠️ refactor

#2870 Link parents with notify log entries
  app/jobs/email_delivery_job.rb
  app/jobs/sms_delivery_job.rb
  app/models/notify_log_entry.rb
  app/models/parent.rb
  db/migrate/20250121112644_add_parent_to_notify_log_entries.rb
  db/schema.rb
  spec/factories/notify_log_entries.rb
  spec/jobs/email_delivery_job_spec.rb
  spec/jobs/sms_delivery_job_spec.rb
  spec/models/notify_log_entry_spec.rb
Labels: 🛠️ refactor

#2869 Add /sha endpoint to deployed environments
  .gitignore
  Dockerfile
Labels: 🗄️ operations

#2874 Ensure patients with pre-screenings can be merged
  app/lib/patient_merger.rb
  app/models/pre_screening.rb
  spec/lib/patient_merger_spec.rb
Labels: 🐞 bug

#2873 Don't pass GOV.UK Notify reply-to if nil
  app/jobs/email_delivery_job.rb
  spec/jobs/email_delivery_job_spec.rb
Labels: 🐞 bug

#2872 Audit SchoolMove
  app/models/school_move.rb
Labels: 🗄️ operations

#2879 Update privacy_notice_url for Herfordshire ymls
  config/onboarding/coventry-production.yaml
  config/onboarding/hertfordshire-training-with-sessions.yaml
  config/onboarding/hertfordshire-training.yaml
Labels: 🗄️ operations

#2878 Fix flaky offline session report test
  spec/lib/reports/offline_session_exporter_spec.rb
Labels: 🛠️ refactor

#2877 Add /sha endpoint to deployed environments
  .github/workflows/_deploy-template.yml
  .gitignore
Labels: 🗄️ operations

#2875 Update Coventry onboarding
  config/onboarding/coventry-production.yaml
Labels: 📐 data_consistency

#2884 Stage entire address as a pending change
  app/models/patient_import_row.rb
  spec/models/class_import_row_spec.rb
Labels: 🐞 bug

#2886 Preload parents with merging NHS numbers
  app/controllers/patients/edit_controller.rb
Labels: 🛠️ refactor

#2883 Ensure self-consent overrides parental consent
  app/models/concerns/patient_session_status_concern.rb
  spec/models/patient_session_spec.rb
Labels: 🐞 bug

#2881 Update patient card to match latest designs
  app/components/app_parent_summary_component.rb
  app/components/app_patient_card_component.rb
  app/components/app_patient_summary_component.rb
  app/views/consents/show.html.erb
  app/views/draft_consents/confirm.html.erb
  spec/components/app_parent_summary_component_spec.rb
  spec/components/app_patient_card_component_spec.rb
  spec/components/app_patient_page_component_spec.rb
  spec/components/app_patient_summary_component_spec.rb
  spec/features/import_vaccination_records_spec.rb
Labels: ✨ feature

#2882 Show delivery status next to parent contact details
  app/assets/stylesheets/_status.scss
  app/components/app_notice_status_component.rb
  app/components/app_parent_summary_component.rb
  app/components/app_patient_card_component.rb
  app/components/app_status_component.rb
  app/models/notify_log_entry.rb
  app/models/parent.rb
  spec/components/app_parent_summary_component_spec.rb
  spec/features/verbal_consent_given_by_new_parental_contact_spec.rb
  spec/features/verbal_consent_given_spec.rb
  spec/features/verbal_consent_refused_personal_choice_spec.rb
  spec/features/verbal_consent_refused_spec.rb
  spec/models/parent_spec.rb
Labels: ✨ feature

#2888 Refactor how conflicting consent status is calculated
  app/models/concerns/patient_session_status_concern.rb
  app/models/patient_session.rb
  spec/models/patient_session_stats_spec.rb
Labels: 🐞 bug

#2891 Add deterministic recipient column
  app/jobs/email_delivery_job.rb
  app/jobs/sms_delivery_job.rb
  app/mailers/application_mailer.rb
  app/models/notify_log_entry.rb
  app/models/parent.rb
  db/migrate/20250127133639_add_recipient_deterministic_to_notify_log_entries.rb
  db/schema.rb
  lib/tasks/notify_log_entries.rake
  spec/components/app_parent_summary_component_spec.rb
  spec/factories/notify_log_entries.rb
  spec/jobs/email_delivery_job_spec.rb
  spec/jobs/sms_delivery_job_spec.rb
  spec/models/notify_log_entry_spec.rb
  spec/models/parent_spec.rb
Labels: 📐 data_consistency, 🛠️ refactor

#2903 Improve session slug string sequence generation
  spec/factories/sessions.rb
Labels: 📐 data_consistency

#2904 Ensure duplicate school moves are removed when merging
  app/lib/patient_merger.rb
  spec/lib/patient_merger_spec.rb
Labels: 🐞 bug

#2905 Handle consent label without a relationship
  app/models/consent.rb
Labels: 🐞 bug

#2909 Bump number of containers from 2 to 3
  copilot/webapp/manifest.yml
Labels: ⌛️ performance

#2910 Bump number of containers from 2 to 3
  copilot/webapp/manifest.yml
Labels: ⌛️ performance

#2880 Record school move log entries
  app/controllers/dev_controller.rb
  app/controllers/school_moves_controller.rb
  app/forms/school_move_form.rb
  app/models/patient.rb
  app/models/school_move.rb
  app/models/school_move_log_entry.rb
  db/migrate/20250122155821_create_school_move_log_entries.rb
  db/schema.rb
  spec/factories/school_move_log_entries.rb
  spec/models/school_move_log_entry_spec.rb
  spec/models/school_move_spec.rb
Labels: 🗄️ operations, 🛠️ refactor

#2916 Add patient_date_of_birth personalisation
  app/lib/govuk_notify_personalisation.rb
  spec/lib/govuk_notify_personalisation_spec.rb
Labels: 🗄️ operations, 🛠️ refactor
